// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: limen/portal/v1/portal.proto

package portalv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LinkState mirrors the per-(user,upstream) link lifecycle.
type LinkState int32

const (
	LinkState_LINK_STATE_UNSPECIFIED   LinkState = 0
	LinkState_LINK_STATE_NONE          LinkState = 1
	LinkState_LINK_STATE_CONNECTED     LinkState = 2
	LinkState_LINK_STATE_DISABLED      LinkState = 3
	LinkState_LINK_STATE_AUTO_DISABLED LinkState = 4
	LinkState_LINK_STATE_NEEDS_RELINK  LinkState = 5
)

// Enum value maps for LinkState.
var (
	LinkState_name = map[int32]string{
		0: "LINK_STATE_UNSPECIFIED",
		1: "LINK_STATE_NONE",
		2: "LINK_STATE_CONNECTED",
		3: "LINK_STATE_DISABLED",
		4: "LINK_STATE_AUTO_DISABLED",
		5: "LINK_STATE_NEEDS_RELINK",
	}
	LinkState_value = map[string]int32{
		"LINK_STATE_UNSPECIFIED":   0,
		"LINK_STATE_NONE":          1,
		"LINK_STATE_CONNECTED":     2,
		"LINK_STATE_DISABLED":      3,
		"LINK_STATE_AUTO_DISABLED": 4,
		"LINK_STATE_NEEDS_RELINK":  5,
	}
)

func (x LinkState) Enum() *LinkState {
	p := new(LinkState)
	*p = x
	return p
}

func (x LinkState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LinkState) Descriptor() protoreflect.EnumDescriptor {
	return file_limen_portal_v1_portal_proto_enumTypes[0].Descriptor()
}

func (LinkState) Type() protoreflect.EnumType {
	return &file_limen_portal_v1_portal_proto_enumTypes[0]
}

func (x LinkState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LinkState.Descriptor instead.
func (LinkState) EnumDescriptor() ([]byte, []int) {
	return file_limen_portal_v1_portal_proto_rawDescGZIP(), []int{0}
}

// StaticHeaderMode controls whether per-user API key overrides are
// allowed for the static_header strategy.
type StaticHeaderMode int32

const (
	StaticHeaderMode_STATIC_HEADER_MODE_UNSPECIFIED StaticHeaderMode = 0
	// tenant_owner — the admin secret is shared by every caller.
	StaticHeaderMode_STATIC_HEADER_MODE_SHARED StaticHeaderMode = 1
	// byok — each user submits their own API key.
	StaticHeaderMode_STATIC_HEADER_MODE_OVERRIDE StaticHeaderMode = 2
)

// Enum value maps for StaticHeaderMode.
var (
	StaticHeaderMode_name = map[int32]string{
		0: "STATIC_HEADER_MODE_UNSPECIFIED",
		1: "STATIC_HEADER_MODE_SHARED",
		2: "STATIC_HEADER_MODE_OVERRIDE",
	}
	StaticHeaderMode_value = map[string]int32{
		"STATIC_HEADER_MODE_UNSPECIFIED": 0,
		"STATIC_HEADER_MODE_SHARED":      1,
		"STATIC_HEADER_MODE_OVERRIDE":    2,
	}
)

func (x StaticHeaderMode) Enum() *StaticHeaderMode {
	p := new(StaticHeaderMode)
	*p = x
	return p
}

func (x StaticHeaderMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StaticHeaderMode) Descriptor() protoreflect.EnumDescriptor {
	return file_limen_portal_v1_portal_proto_enumTypes[1].Descriptor()
}

func (StaticHeaderMode) Type() protoreflect.EnumType {
	return &file_limen_portal_v1_portal_proto_enumTypes[1]
}

func (x StaticHeaderMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StaticHeaderMode.Descriptor instead.
func (StaticHeaderMode) EnumDescriptor() ([]byte, []int) {
	return file_limen_portal_v1_portal_proto_rawDescGZIP(), []int{1}
}

type ListUpstreamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUpstreamsRequest) Reset() {
	*x = ListUpstreamsRequest{}
	mi := &file_limen_portal_v1_portal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUpstreamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUpstreamsRequest) ProtoMessage() {}

func (x *ListUpstreamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_limen_portal_v1_portal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUpstreamsRequest.ProtoReflect.Descriptor instead.
func (*ListUpstreamsRequest) Descriptor() ([]byte, []int) {
	return file_limen_portal_v1_portal_proto_rawDescGZIP(), []int{0}
}

type ListUpstreamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Upstreams     []*UpstreamSummary     `protobuf:"bytes,1,rep,name=upstreams,proto3" json:"upstreams,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUpstreamsResponse) Reset() {
	*x = ListUpstreamsResponse{}
	mi := &file_limen_portal_v1_portal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUpstreamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUpstreamsResponse) ProtoMessage() {}

func (x *ListUpstreamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_limen_portal_v1_portal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUpstreamsResponse.ProtoReflect.Descriptor instead.
func (*ListUpstreamsResponse) Descriptor() ([]byte, []int) {
	return file_limen_portal_v1_portal_proto_rawDescGZIP(), []int{1}
}

func (x *ListUpstreamsResponse) GetUpstreams() []*UpstreamSummary {
	if x != nil {
		return x.Upstreams
	}
	return nil
}

type UpstreamSummary struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	PublicId     string                 `protobuf:"bytes,1,opt,name=public_id,json=publicId,proto3" json:"public_id,omitempty"`
	Identifier   string                 `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
	DisplayName  string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	McpUrl       string                 `protobuf:"bytes,4,opt,name=mcp_url,json=mcpUrl,proto3" json:"mcp_url,omitempty"`
	StrategyType string                 `protobuf:"bytes,5,opt,name=strategy_type,json=strategyType,proto3" json:"strategy_type,omitempty"`
	// String representation of static_header_mode for backward
	// compatibility: "tenant_owner" / "byok". Empty for strategies
	// without a sub-mode.
	StrategySubMode string    `protobuf:"bytes,6,opt,name=strategy_sub_mode,json=strategySubMode,proto3" json:"strategy_sub_mode,omitempty"`
	RequiresLink    bool      `protobuf:"varint,7,opt,name=requires_link,json=requiresLink,proto3" json:"requires_link,omitempty"`
	LinkState       LinkState `protobuf:"varint,8,opt,name=link_state,json=linkState,proto3,enum=limen.portal.v1.LinkState" json:"link_state,omitempty"`
	LastErrorReason string    `protobuf:"bytes,9,opt,name=last_error_reason,json=lastErrorReason,proto3" json:"last_error_reason,omitempty"`
	// RFC3339; empty when no failure has been recorded.
	LastErrorAt string `protobuf:"bytes,10,opt,name=last_error_at,json=lastErrorAt,proto3" json:"last_error_at,omitempty"`
	// Cached tool catalog for this upstream (populated by the indexer on
	// provision / link / refresh). Same for every user of the upstream;
	// the SPA renders these in a spoiler under the card.
	Tools []*UpstreamTool `protobuf:"bytes,11,rep,name=tools,proto3" json:"tools,omitempty"`
	// Derived prefix aliases (Phase 15) after the tenant-wide collision
	// pass — e.g. ["jira", "confluence"] for the Atlassian upstream.
	Aliases []string `protobuf:"bytes,12,rep,name=aliases,proto3" json:"aliases,omitempty"`
	// `static_header` with `strategy_sub_mode == "override"`: true when
	// the user has submitted their own override key (ExtraJSON populated
	// on the link). Drives the portal CTA between Submit and Rotate/Clear.
	// Always false for shared sub-mode and for other strategies.
	HasUserOverride bool `protobuf:"varint,13,opt,name=has_user_override,json=hasUserOverride,proto3" json:"has_user_override,omitempty"`
	// True when the upstream has an active UpstreamTenantLink row
	// (admin has configured credentials). Used by both the admin SPA
	// (health monitoring) and portal SPA ("upstream not configured yet" banner).
	HasTenantLink bool `protobuf:"varint,15,opt,name=has_tenant_link,json=hasTenantLink,proto3" json:"has_tenant_link,omitempty"`
	// Health state of the tenant-level credentials. UNSPECIFIED when
	// has_tenant_link is false. Reuses LinkState since the state
	// machine is identical (connected, needs_relink, auto_disabled).
	TenantLinkState LinkState `protobuf:"varint,16,opt,name=tenant_link_state,json=tenantLinkState,proto3,enum=limen.portal.v1.LinkState" json:"tenant_link_state,omitempty"`
	// Typed enum mirroring strategy_sub_mode. SHARED / OVERRIDE for
	// static_header; UNSPECIFIED for other strategies.
	StaticHeaderMode StaticHeaderMode `protobuf:"varint,14,opt,name=static_header_mode,json=staticHeaderMode,proto3,enum=limen.portal.v1.StaticHeaderMode" json:"static_header_mode,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpstreamSummary) Reset() {
	*x = UpstreamSummary{}
	mi := &file_limen_portal_v1_portal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpstreamSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpstreamSummary) ProtoMessage() {}

func (x *UpstreamSummary) ProtoReflect() protoreflect.Message {
	mi := &file_limen_portal_v1_portal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpstreamSummary.ProtoReflect.Descriptor instead.
func (*UpstreamSummary) Descriptor() ([]byte, []int) {
	return file_limen_portal_v1_portal_proto_rawDescGZIP(), []int{2}
}

func (x *UpstreamSummary) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

func (x *UpstreamSummary) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *UpstreamSummary) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *UpstreamSummary) GetMcpUrl() string {
	if x != nil {
		return x.McpUrl
	}
	return ""
}

func (x *UpstreamSummary) GetStrategyType() string {
	if x != nil {
		return x.StrategyType
	}
	return ""
}

func (x *UpstreamSummary) GetStrategySubMode() string {
	if x != nil {
		return x.StrategySubMode
	}
	return ""
}

func (x *UpstreamSummary) GetRequiresLink() bool {
	if x != nil {
		return x.RequiresLink
	}
	return false
}

func (x *UpstreamSummary) GetLinkState() LinkState {
	if x != nil {
		return x.LinkState
	}
	return LinkState_LINK_STATE_UNSPECIFIED
}

func (x *UpstreamSummary) GetLastErrorReason() string {
	if x != nil {
		return x.LastErrorReason
	}
	return ""
}

func (x *UpstreamSummary) GetLastErrorAt() string {
	if x != nil {
		return x.LastErrorAt
	}
	return ""
}

func (x *UpstreamSummary) GetTools() []*UpstreamTool {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *UpstreamSummary) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

func (x *UpstreamSummary) GetHasUserOverride() bool {
	if x != nil {
		return x.HasUserOverride
	}
	return false
}

func (x *UpstreamSummary) GetHasTenantLink() bool {
	if x != nil {
		return x.HasTenantLink
	}
	return false
}

func (x *UpstreamSummary) GetTenantLinkState() LinkState {
	if x != nil {
		return x.TenantLinkState
	}
	return LinkState_LINK_STATE_UNSPECIFIED
}

func (x *UpstreamSummary) GetStaticHeaderMode() StaticHeaderMode {
	if x != nil {
		return x.StaticHeaderMode
	}
	return StaticHeaderMode_STATIC_HEADER_MODE_UNSPECIFIED
}

type UpstreamTool struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpstreamTool) Reset() {
	*x = UpstreamTool{}
	mi := &file_limen_portal_v1_portal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpstreamTool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpstreamTool) ProtoMessage() {}

func (x *UpstreamTool) ProtoReflect() protoreflect.Message {
	mi := &file_limen_portal_v1_portal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpstreamTool.ProtoReflect.Descriptor instead.
func (*UpstreamTool) Descriptor() ([]byte, []int) {
	return file_limen_portal_v1_portal_proto_rawDescGZIP(), []int{3}
}

func (x *UpstreamTool) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpstreamTool) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type StartConnectRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UpstreamPublicId string                 `protobuf:"bytes,1,opt,name=upstream_public_id,json=upstreamPublicId,proto3" json:"upstream_public_id,omitempty"`
	// Path the SPA wants the browser to return to after the dance.
	ReturnTo      string `protobuf:"bytes,2,opt,name=return_to,json=returnTo,proto3" json:"return_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartConnectRequest) Reset() {
	*x = StartConnectRequest{}
	mi := &file_limen_portal_v1_portal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartConnectRequest) ProtoMessage() {}

func (x *StartConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_limen_portal_v1_portal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartConnectRequest.ProtoReflect.Descriptor instead.
func (*StartConnectRequest) Descriptor() ([]byte, []int) {
	return file_limen_portal_v1_portal_proto_rawDescGZIP(), []int{4}
}

func (x *StartConnectRequest) GetUpstreamPublicId() string {
	if x != nil {
		return x.UpstreamPublicId
	}
	return ""
}

func (x *StartConnectRequest) GetReturnTo() string {
	if x != nil {
		return x.ReturnTo
	}
	return ""
}

type StartConnectResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Either an absolute upstream-OAuth authorize URL (mcp_spec) or a
	// relative SPA path that triggers an API-key modal (static_header
	// user-mode). The SPA navigates the browser to this value.
	RedirectUrl   string `protobuf:"bytes,1,opt,name=redirect_url,json=redirectUrl,proto3" json:"redirect_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartConnectResponse) Reset() {
	*x = StartConnectResponse{}
	mi := &file_limen_portal_v1_portal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartConnectResponse) ProtoMessage() {}

func (x *StartConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_limen_portal_v1_portal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartConnectResponse.ProtoReflect.Descriptor instead.
func (*StartConnectResponse) Descriptor() ([]byte, []int) {
	return file_limen_portal_v1_portal_proto_rawDescGZIP(), []int{5}
}

func (x *StartConnectResponse) GetRedirectUrl() string {
	if x != nil {
		return x.RedirectUrl
	}
	return ""
}

type SubmitUpstreamAPIKeyRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UpstreamPublicId string                 `protobuf:"bytes,1,opt,name=upstream_public_id,json=upstreamPublicId,proto3" json:"upstream_public_id,omitempty"`
	ApiKey           string                 `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SubmitUpstreamAPIKeyRequest) Reset() {
	*x = SubmitUpstreamAPIKeyRequest{}
	mi := &file_limen_portal_v1_portal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitUpstreamAPIKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitUpstreamAPIKeyRequest) ProtoMessage() {}

func (x *SubmitUpstreamAPIKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_limen_portal_v1_portal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitUpstreamAPIKeyRequest.ProtoReflect.Descriptor instead.
func (*SubmitUpstreamAPIKeyRequest) Descriptor() ([]byte, []int) {
	return file_limen_portal_v1_portal_proto_rawDescGZIP(), []int{6}
}

func (x *SubmitUpstreamAPIKeyRequest) GetUpstreamPublicId() string {
	if x != nil {
		return x.UpstreamPublicId
	}
	return ""
}

func (x *SubmitUpstreamAPIKeyRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type SubmitUpstreamAPIKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitUpstreamAPIKeyResponse) Reset() {
	*x = SubmitUpstreamAPIKeyResponse{}
	mi := &file_limen_portal_v1_portal_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitUpstreamAPIKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitUpstreamAPIKeyResponse) ProtoMessage() {}

func (x *SubmitUpstreamAPIKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_limen_portal_v1_portal_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitUpstreamAPIKeyResponse.ProtoReflect.Descriptor instead.
func (*SubmitUpstreamAPIKeyResponse) Descriptor() ([]byte, []int) {
	return file_limen_portal_v1_portal_proto_rawDescGZIP(), []int{7}
}

type ClearUpstreamOverrideRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UpstreamPublicId string                 `protobuf:"bytes,1,opt,name=upstream_public_id,json=upstreamPublicId,proto3" json:"upstream_public_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ClearUpstreamOverrideRequest) Reset() {
	*x = ClearUpstreamOverrideRequest{}
	mi := &file_limen_portal_v1_portal_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearUpstreamOverrideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearUpstreamOverrideRequest) ProtoMessage() {}

func (x *ClearUpstreamOverrideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_limen_portal_v1_portal_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearUpstreamOverrideRequest.ProtoReflect.Descriptor instead.
func (*ClearUpstreamOverrideRequest) Descriptor() ([]byte, []int) {
	return file_limen_portal_v1_portal_proto_rawDescGZIP(), []int{8}
}

func (x *ClearUpstreamOverrideRequest) GetUpstreamPublicId() string {
	if x != nil {
		return x.UpstreamPublicId
	}
	return ""
}

type ClearUpstreamOverrideResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearUpstreamOverrideResponse) Reset() {
	*x = ClearUpstreamOverrideResponse{}
	mi := &file_limen_portal_v1_portal_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearUpstreamOverrideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearUpstreamOverrideResponse) ProtoMessage() {}

func (x *ClearUpstreamOverrideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_limen_portal_v1_portal_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearUpstreamOverrideResponse.ProtoReflect.Descriptor instead.
func (*ClearUpstreamOverrideResponse) Descriptor() ([]byte, []int) {
	return file_limen_portal_v1_portal_proto_rawDescGZIP(), []int{9}
}

type SetUpstreamLinkEnabledRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UpstreamPublicId string                 `protobuf:"bytes,1,opt,name=upstream_public_id,json=upstreamPublicId,proto3" json:"upstream_public_id,omitempty"`
	Enabled          bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SetUpstreamLinkEnabledRequest) Reset() {
	*x = SetUpstreamLinkEnabledRequest{}
	mi := &file_limen_portal_v1_portal_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUpstreamLinkEnabledRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUpstreamLinkEnabledRequest) ProtoMessage() {}

func (x *SetUpstreamLinkEnabledRequest) ProtoReflect() protoreflect.Message {
	mi := &file_limen_portal_v1_portal_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUpstreamLinkEnabledRequest.ProtoReflect.Descriptor instead.
func (*SetUpstreamLinkEnabledRequest) Descriptor() ([]byte, []int) {
	return file_limen_portal_v1_portal_proto_rawDescGZIP(), []int{10}
}

func (x *SetUpstreamLinkEnabledRequest) GetUpstreamPublicId() string {
	if x != nil {
		return x.UpstreamPublicId
	}
	return ""
}

func (x *SetUpstreamLinkEnabledRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type SetUpstreamLinkEnabledResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUpstreamLinkEnabledResponse) Reset() {
	*x = SetUpstreamLinkEnabledResponse{}
	mi := &file_limen_portal_v1_portal_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUpstreamLinkEnabledResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUpstreamLinkEnabledResponse) ProtoMessage() {}

func (x *SetUpstreamLinkEnabledResponse) ProtoReflect() protoreflect.Message {
	mi := &file_limen_portal_v1_portal_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUpstreamLinkEnabledResponse.ProtoReflect.Descriptor instead.
func (*SetUpstreamLinkEnabledResponse) Descriptor() ([]byte, []int) {
	return file_limen_portal_v1_portal_proto_rawDescGZIP(), []int{11}
}

type DisconnectRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UpstreamPublicId string                 `protobuf:"bytes,1,opt,name=upstream_public_id,json=upstreamPublicId,proto3" json:"upstream_public_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DisconnectRequest) Reset() {
	*x = DisconnectRequest{}
	mi := &file_limen_portal_v1_portal_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectRequest) ProtoMessage() {}

func (x *DisconnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_limen_portal_v1_portal_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectRequest.ProtoReflect.Descriptor instead.
func (*DisconnectRequest) Descriptor() ([]byte, []int) {
	return file_limen_portal_v1_portal_proto_rawDescGZIP(), []int{12}
}

func (x *DisconnectRequest) GetUpstreamPublicId() string {
	if x != nil {
		return x.UpstreamPublicId
	}
	return ""
}

type DisconnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectResponse) Reset() {
	*x = DisconnectResponse{}
	mi := &file_limen_portal_v1_portal_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectResponse) ProtoMessage() {}

func (x *DisconnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_limen_portal_v1_portal_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectResponse.ProtoReflect.Descriptor instead.
func (*DisconnectResponse) Descriptor() ([]byte, []int) {
	return file_limen_portal_v1_portal_proto_rawDescGZIP(), []int{13}
}

type ListMCPClientsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMCPClientsRequest) Reset() {
	*x = ListMCPClientsRequest{}
	mi := &file_limen_portal_v1_portal_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMCPClientsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMCPClientsRequest) ProtoMessage() {}

func (x *ListMCPClientsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_limen_portal_v1_portal_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMCPClientsRequest.ProtoReflect.Descriptor instead.
func (*ListMCPClientsRequest) Descriptor() ([]byte, []int) {
	return file_limen_portal_v1_portal_proto_rawDescGZIP(), []int{14}
}

type ListMCPClientsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clients       []*MCPClient           `protobuf:"bytes,1,rep,name=clients,proto3" json:"clients,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMCPClientsResponse) Reset() {
	*x = ListMCPClientsResponse{}
	mi := &file_limen_portal_v1_portal_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMCPClientsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMCPClientsResponse) ProtoMessage() {}

func (x *ListMCPClientsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_limen_portal_v1_portal_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMCPClientsResponse.ProtoReflect.Descriptor instead.
func (*ListMCPClientsResponse) Descriptor() ([]byte, []int) {
	return file_limen_portal_v1_portal_proto_rawDescGZIP(), []int{15}
}

func (x *ListMCPClientsResponse) GetClients() []*MCPClient {
	if x != nil {
		return x.Clients
	}
	return nil
}

type MCPClient struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PublicId        string                 `protobuf:"bytes,1,opt,name=public_id,json=publicId,proto3" json:"public_id,omitempty"`
	ClientId        string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Name            string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	SoftwareId      string                 `protobuf:"bytes,4,opt,name=software_id,json=softwareId,proto3" json:"software_id,omitempty"`
	SoftwareVersion string                 `protobuf:"bytes,5,opt,name=software_version,json=softwareVersion,proto3" json:"software_version,omitempty"`
	// RFC3339.
	CreatedAt     string `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPClient) Reset() {
	*x = MCPClient{}
	mi := &file_limen_portal_v1_portal_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPClient) ProtoMessage() {}

func (x *MCPClient) ProtoReflect() protoreflect.Message {
	mi := &file_limen_portal_v1_portal_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPClient.ProtoReflect.Descriptor instead.
func (*MCPClient) Descriptor() ([]byte, []int) {
	return file_limen_portal_v1_portal_proto_rawDescGZIP(), []int{16}
}

func (x *MCPClient) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

func (x *MCPClient) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *MCPClient) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MCPClient) GetSoftwareId() string {
	if x != nil {
		return x.SoftwareId
	}
	return ""
}

func (x *MCPClient) GetSoftwareVersion() string {
	if x != nil {
		return x.SoftwareVersion
	}
	return ""
}

func (x *MCPClient) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type RevokeMCPClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicId      string                 `protobuf:"bytes,1,opt,name=public_id,json=publicId,proto3" json:"public_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeMCPClientRequest) Reset() {
	*x = RevokeMCPClientRequest{}
	mi := &file_limen_portal_v1_portal_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeMCPClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeMCPClientRequest) ProtoMessage() {}

func (x *RevokeMCPClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_limen_portal_v1_portal_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeMCPClientRequest.ProtoReflect.Descriptor instead.
func (*RevokeMCPClientRequest) Descriptor() ([]byte, []int) {
	return file_limen_portal_v1_portal_proto_rawDescGZIP(), []int{17}
}

func (x *RevokeMCPClientRequest) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

type RevokeMCPClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeMCPClientResponse) Reset() {
	*x = RevokeMCPClientResponse{}
	mi := &file_limen_portal_v1_portal_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeMCPClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeMCPClientResponse) ProtoMessage() {}

func (x *RevokeMCPClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_limen_portal_v1_portal_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeMCPClientResponse.ProtoReflect.Descriptor instead.
func (*RevokeMCPClientResponse) Descriptor() ([]byte, []int) {
	return file_limen_portal_v1_portal_proto_rawDescGZIP(), []int{18}
}

type GetBillingSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBillingSummaryRequest) Reset() {
	*x = GetBillingSummaryRequest{}
	mi := &file_limen_portal_v1_portal_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBillingSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBillingSummaryRequest) ProtoMessage() {}

func (x *GetBillingSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_limen_portal_v1_portal_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBillingSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetBillingSummaryRequest) Descriptor() ([]byte, []int) {
	return file_limen_portal_v1_portal_proto_rawDescGZIP(), []int{19}
}

type GetBillingSummaryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current plan: "developer" or "team".
	Plan string `protobuf:"bytes,1,opt,name=plan,proto3" json:"plan,omitempty"`
	// Subscription status: "none", "trialing", "active", "past_due", "canceled", "incomplete", "incomplete_expired", "unpaid".
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// Current billing period active user count.
	ActiveUserCount int32 `protobuf:"varint,3,opt,name=active_user_count,json=activeUserCount,proto3" json:"active_user_count,omitempty"`
	// Current billing period SA connection count.
	ActiveSaConnectionCount int32 `protobuf:"varint,4,opt,name=active_sa_connection_count,json=activeSaConnectionCount,proto3" json:"active_sa_connection_count,omitempty"`
	// Stripe publishable key for the SPA to initialize Stripe.js.
	StripePublishableKey string `protobuf:"bytes,5,opt,name=stripe_publishable_key,json=stripePublishableKey,proto3" json:"stripe_publishable_key,omitempty"`
	// RFC3339 timestamp of the current period end, or empty if no subscription.
	CurrentPeriodEnd string `protobuf:"bytes,6,opt,name=current_period_end,json=currentPeriodEnd,proto3" json:"current_period_end,omitempty"`
	// True if the subscription will cancel at period end.
	CancelAtPeriodEnd bool `protobuf:"varint,7,opt,name=cancel_at_period_end,json=cancelAtPeriodEnd,proto3" json:"cancel_at_period_end,omitempty"`
	// RFC3339 timestamp of grace period expiry, or empty if not in grace.
	GraceUntil    string `protobuf:"bytes,8,opt,name=grace_until,json=graceUntil,proto3" json:"grace_until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBillingSummaryResponse) Reset() {
	*x = GetBillingSummaryResponse{}
	mi := &file_limen_portal_v1_portal_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBillingSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBillingSummaryResponse) ProtoMessage() {}

func (x *GetBillingSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_limen_portal_v1_portal_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBillingSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetBillingSummaryResponse) Descriptor() ([]byte, []int) {
	return file_limen_portal_v1_portal_proto_rawDescGZIP(), []int{20}
}

func (x *GetBillingSummaryResponse) GetPlan() string {
	if x != nil {
		return x.Plan
	}
	return ""
}

func (x *GetBillingSummaryResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetBillingSummaryResponse) GetActiveUserCount() int32 {
	if x != nil {
		return x.ActiveUserCount
	}
	return 0
}

func (x *GetBillingSummaryResponse) GetActiveSaConnectionCount() int32 {
	if x != nil {
		return x.ActiveSaConnectionCount
	}
	return 0
}

func (x *GetBillingSummaryResponse) GetStripePublishableKey() string {
	if x != nil {
		return x.StripePublishableKey
	}
	return ""
}

func (x *GetBillingSummaryResponse) GetCurrentPeriodEnd() string {
	if x != nil {
		return x.CurrentPeriodEnd
	}
	return ""
}

func (x *GetBillingSummaryResponse) GetCancelAtPeriodEnd() bool {
	if x != nil {
		return x.CancelAtPeriodEnd
	}
	return false
}

func (x *GetBillingSummaryResponse) GetGraceUntil() string {
	if x != nil {
		return x.GraceUntil
	}
	return ""
}

type CreateCheckoutSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The URL the SPA wants the browser to return to after checkout.
	ReturnTo      string `protobuf:"bytes,1,opt,name=return_to,json=returnTo,proto3" json:"return_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCheckoutSessionRequest) Reset() {
	*x = CreateCheckoutSessionRequest{}
	mi := &file_limen_portal_v1_portal_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCheckoutSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCheckoutSessionRequest) ProtoMessage() {}

func (x *CreateCheckoutSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_limen_portal_v1_portal_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCheckoutSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateCheckoutSessionRequest) Descriptor() ([]byte, []int) {
	return file_limen_portal_v1_portal_proto_rawDescGZIP(), []int{21}
}

func (x *CreateCheckoutSessionRequest) GetReturnTo() string {
	if x != nil {
		return x.ReturnTo
	}
	return ""
}

type CreateCheckoutSessionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Absolute Stripe Checkout URL. The SPA navigates the browser to this.
	RedirectUrl   string `protobuf:"bytes,1,opt,name=redirect_url,json=redirectUrl,proto3" json:"redirect_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCheckoutSessionResponse) Reset() {
	*x = CreateCheckoutSessionResponse{}
	mi := &file_limen_portal_v1_portal_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCheckoutSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCheckoutSessionResponse) ProtoMessage() {}

func (x *CreateCheckoutSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_limen_portal_v1_portal_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCheckoutSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateCheckoutSessionResponse) Descriptor() ([]byte, []int) {
	return file_limen_portal_v1_portal_proto_rawDescGZIP(), []int{22}
}

func (x *CreateCheckoutSessionResponse) GetRedirectUrl() string {
	if x != nil {
		return x.RedirectUrl
	}
	return ""
}

type OpenCustomerPortalRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The URL the SPA wants the browser to return to after the portal.
	ReturnTo      string `protobuf:"bytes,1,opt,name=return_to,json=returnTo,proto3" json:"return_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenCustomerPortalRequest) Reset() {
	*x = OpenCustomerPortalRequest{}
	mi := &file_limen_portal_v1_portal_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenCustomerPortalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenCustomerPortalRequest) ProtoMessage() {}

func (x *OpenCustomerPortalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_limen_portal_v1_portal_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenCustomerPortalRequest.ProtoReflect.Descriptor instead.
func (*OpenCustomerPortalRequest) Descriptor() ([]byte, []int) {
	return file_limen_portal_v1_portal_proto_rawDescGZIP(), []int{23}
}

func (x *OpenCustomerPortalRequest) GetReturnTo() string {
	if x != nil {
		return x.ReturnTo
	}
	return ""
}

type OpenCustomerPortalResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Absolute Stripe Customer Portal URL.
	RedirectUrl   string `protobuf:"bytes,1,opt,name=redirect_url,json=redirectUrl,proto3" json:"redirect_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenCustomerPortalResponse) Reset() {
	*x = OpenCustomerPortalResponse{}
	mi := &file_limen_portal_v1_portal_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenCustomerPortalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenCustomerPortalResponse) ProtoMessage() {}

func (x *OpenCustomerPortalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_limen_portal_v1_portal_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenCustomerPortalResponse.ProtoReflect.Descriptor instead.
func (*OpenCustomerPortalResponse) Descriptor() ([]byte, []int) {
	return file_limen_portal_v1_portal_proto_rawDescGZIP(), []int{24}
}

func (x *OpenCustomerPortalResponse) GetRedirectUrl() string {
	if x != nil {
		return x.RedirectUrl
	}
	return ""
}

var File_limen_portal_v1_portal_proto protoreflect.FileDescriptor

const file_limen_portal_v1_portal_proto_rawDesc = "" +
	"\n" +
	"\x1climen/portal/v1/portal.proto\x12\x0flimen.portal.v1\"\x16\n" +
	"\x14ListUpstreamsRequest\"W\n" +
	"\x15ListUpstreamsResponse\x12>\n" +
	"\tupstreams\x18\x01 \x03(\v2 .limen.portal.v1.UpstreamSummaryR\tupstreams\"\xc7\x05\n" +
	"\x0fUpstreamSummary\x12\x1b\n" +
	"\tpublic_id\x18\x01 \x01(\tR\bpublicId\x12\x1e\n" +
	"\n" +
	"identifier\x18\x02 \x01(\tR\n" +
	"identifier\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x17\n" +
	"\amcp_url\x18\x04 \x01(\tR\x06mcpUrl\x12#\n" +
	"\rstrategy_type\x18\x05 \x01(\tR\fstrategyType\x12*\n" +
	"\x11strategy_sub_mode\x18\x06 \x01(\tR\x0fstrategySubMode\x12#\n" +
	"\rrequires_link\x18\a \x01(\bR\frequiresLink\x129\n" +
	"\n" +
	"link_state\x18\b \x01(\x0e2\x1a.limen.portal.v1.LinkStateR\tlinkState\x12*\n" +
	"\x11last_error_reason\x18\t \x01(\tR\x0flastErrorReason\x12\"\n" +
	"\rlast_error_at\x18\n" +
	" \x01(\tR\vlastErrorAt\x123\n" +
	"\x05tools\x18\v \x03(\v2\x1d.limen.portal.v1.UpstreamToolR\x05tools\x12\x18\n" +
	"\aaliases\x18\f \x03(\tR\aaliases\x12*\n" +
	"\x11has_user_override\x18\r \x01(\bR\x0fhasUserOverride\x12&\n" +
	"\x0fhas_tenant_link\x18\x0f \x01(\bR\rhasTenantLink\x12F\n" +
	"\x11tenant_link_state\x18\x10 \x01(\x0e2\x1a.limen.portal.v1.LinkStateR\x0ftenantLinkState\x12O\n" +
	"\x12static_header_mode\x18\x0e \x01(\x0e2!.limen.portal.v1.StaticHeaderModeR\x10staticHeaderMode\"D\n" +
	"\fUpstreamTool\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"`\n" +
	"\x13StartConnectRequest\x12,\n" +
	"\x12upstream_public_id\x18\x01 \x01(\tR\x10upstreamPublicId\x12\x1b\n" +
	"\treturn_to\x18\x02 \x01(\tR\breturnTo\"9\n" +
	"\x14StartConnectResponse\x12!\n" +
	"\fredirect_url\x18\x01 \x01(\tR\vredirectUrl\"d\n" +
	"\x1bSubmitUpstreamAPIKeyRequest\x12,\n" +
	"\x12upstream_public_id\x18\x01 \x01(\tR\x10upstreamPublicId\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\"\x1e\n" +
	"\x1cSubmitUpstreamAPIKeyResponse\"L\n" +
	"\x1cClearUpstreamOverrideRequest\x12,\n" +
	"\x12upstream_public_id\x18\x01 \x01(\tR\x10upstreamPublicId\"\x1f\n" +
	"\x1dClearUpstreamOverrideResponse\"g\n" +
	"\x1dSetUpstreamLinkEnabledRequest\x12,\n" +
	"\x12upstream_public_id\x18\x01 \x01(\tR\x10upstreamPublicId\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\" \n" +
	"\x1eSetUpstreamLinkEnabledResponse\"A\n" +
	"\x11DisconnectRequest\x12,\n" +
	"\x12upstream_public_id\x18\x01 \x01(\tR\x10upstreamPublicId\"\x14\n" +
	"\x12DisconnectResponse\"\x17\n" +
	"\x15ListMCPClientsRequest\"N\n" +
	"\x16ListMCPClientsResponse\x124\n" +
	"\aclients\x18\x01 \x03(\v2\x1a.limen.portal.v1.MCPClientR\aclients\"\xc4\x01\n" +
	"\tMCPClient\x12\x1b\n" +
	"\tpublic_id\x18\x01 \x01(\tR\bpublicId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1f\n" +
	"\vsoftware_id\x18\x04 \x01(\tR\n" +
	"softwareId\x12)\n" +
	"\x10software_version\x18\x05 \x01(\tR\x0fsoftwareVersion\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\"5\n" +
	"\x16RevokeMCPClientRequest\x12\x1b\n" +
	"\tpublic_id\x18\x01 \x01(\tR\bpublicId\"\x19\n" +
	"\x17RevokeMCPClientResponse\"\x1a\n" +
	"\x18GetBillingSummaryRequest\"\xe6\x02\n" +
	"\x19GetBillingSummaryResponse\x12\x12\n" +
	"\x04plan\x18\x01 \x01(\tR\x04plan\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12*\n" +
	"\x11active_user_count\x18\x03 \x01(\x05R\x0factiveUserCount\x12;\n" +
	"\x1aactive_sa_connection_count\x18\x04 \x01(\x05R\x17activeSaConnectionCount\x124\n" +
	"\x16stripe_publishable_key\x18\x05 \x01(\tR\x14stripePublishableKey\x12,\n" +
	"\x12current_period_end\x18\x06 \x01(\tR\x10currentPeriodEnd\x12/\n" +
	"\x14cancel_at_period_end\x18\a \x01(\bR\x11cancelAtPeriodEnd\x12\x1f\n" +
	"\vgrace_until\x18\b \x01(\tR\n" +
	"graceUntil\";\n" +
	"\x1cCreateCheckoutSessionRequest\x12\x1b\n" +
	"\treturn_to\x18\x01 \x01(\tR\breturnTo\"B\n" +
	"\x1dCreateCheckoutSessionResponse\x12!\n" +
	"\fredirect_url\x18\x01 \x01(\tR\vredirectUrl\"8\n" +
	"\x19OpenCustomerPortalRequest\x12\x1b\n" +
	"\treturn_to\x18\x01 \x01(\tR\breturnTo\"?\n" +
	"\x1aOpenCustomerPortalResponse\x12!\n" +
	"\fredirect_url\x18\x01 \x01(\tR\vredirectUrl*\xaa\x01\n" +
	"\tLinkState\x12\x1a\n" +
	"\x16LINK_STATE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fLINK_STATE_NONE\x10\x01\x12\x18\n" +
	"\x14LINK_STATE_CONNECTED\x10\x02\x12\x17\n" +
	"\x13LINK_STATE_DISABLED\x10\x03\x12\x1c\n" +
	"\x18LINK_STATE_AUTO_DISABLED\x10\x04\x12\x1b\n" +
	"\x17LINK_STATE_NEEDS_RELINK\x10\x05*v\n" +
	"\x10StaticHeaderMode\x12\"\n" +
	"\x1eSTATIC_HEADER_MODE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19STATIC_HEADER_MODE_SHARED\x10\x01\x12\x1f\n" +
	"\x1bSTATIC_HEADER_MODE_OVERRIDE\x10\x022\xd4\x06\n" +
	"\rPortalService\x12^\n" +
	"\rListUpstreams\x12%.limen.portal.v1.ListUpstreamsRequest\x1a&.limen.portal.v1.ListUpstreamsResponse\x12[\n" +
	"\fStartConnect\x12$.limen.portal.v1.StartConnectRequest\x1a%.limen.portal.v1.StartConnectResponse\x12s\n" +
	"\x14SubmitUpstreamAPIKey\x12,.limen.portal.v1.SubmitUpstreamAPIKeyRequest\x1a-.limen.portal.v1.SubmitUpstreamAPIKeyResponse\x12v\n" +
	"\x15ClearUpstreamOverride\x12-.limen.portal.v1.ClearUpstreamOverrideRequest\x1a..limen.portal.v1.ClearUpstreamOverrideResponse\x12y\n" +
	"\x16SetUpstreamLinkEnabled\x12..limen.portal.v1.SetUpstreamLinkEnabledRequest\x1a/.limen.portal.v1.SetUpstreamLinkEnabledResponse\x12U\n" +
	"\n" +
	"Disconnect\x12\".limen.portal.v1.DisconnectRequest\x1a#.limen.portal.v1.DisconnectResponse\x12a\n" +
	"\x0eListMCPClients\x12&.limen.portal.v1.ListMCPClientsRequest\x1a'.limen.portal.v1.ListMCPClientsResponse\x12d\n" +
	"\x0fRevokeMCPClient\x12'.limen.portal.v1.RevokeMCPClientRequest\x1a(.limen.portal.v1.RevokeMCPClientResponse2\xe3\x02\n" +
	"\x0eBillingService\x12j\n" +
	"\x11GetBillingSummary\x12).limen.portal.v1.GetBillingSummaryRequest\x1a*.limen.portal.v1.GetBillingSummaryResponse\x12v\n" +
	"\x15CreateCheckoutSession\x12-.limen.portal.v1.CreateCheckoutSessionRequest\x1a..limen.portal.v1.CreateCheckoutSessionResponse\x12m\n" +
	"\x12OpenCustomerPortal\x12*.limen.portal.v1.OpenCustomerPortalRequest\x1a+.limen.portal.v1.OpenCustomerPortalResponseB>Z<github.com/belphemur/limen/internal/portal/portalv1;portalv1b\x06proto3"

var (
	file_limen_portal_v1_portal_proto_rawDescOnce sync.Once
	file_limen_portal_v1_portal_proto_rawDescData []byte
)

func file_limen_portal_v1_portal_proto_rawDescGZIP() []byte {
	file_limen_portal_v1_portal_proto_rawDescOnce.Do(func() {
		file_limen_portal_v1_portal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_limen_portal_v1_portal_proto_rawDesc), len(file_limen_portal_v1_portal_proto_rawDesc)))
	})
	return file_limen_portal_v1_portal_proto_rawDescData
}

var file_limen_portal_v1_portal_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_limen_portal_v1_portal_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_limen_portal_v1_portal_proto_goTypes = []any{
	(LinkState)(0),                         // 0: limen.portal.v1.LinkState
	(StaticHeaderMode)(0),                  // 1: limen.portal.v1.StaticHeaderMode
	(*ListUpstreamsRequest)(nil),           // 2: limen.portal.v1.ListUpstreamsRequest
	(*ListUpstreamsResponse)(nil),          // 3: limen.portal.v1.ListUpstreamsResponse
	(*UpstreamSummary)(nil),                // 4: limen.portal.v1.UpstreamSummary
	(*UpstreamTool)(nil),                   // 5: limen.portal.v1.UpstreamTool
	(*StartConnectRequest)(nil),            // 6: limen.portal.v1.StartConnectRequest
	(*StartConnectResponse)(nil),           // 7: limen.portal.v1.StartConnectResponse
	(*SubmitUpstreamAPIKeyRequest)(nil),    // 8: limen.portal.v1.SubmitUpstreamAPIKeyRequest
	(*SubmitUpstreamAPIKeyResponse)(nil),   // 9: limen.portal.v1.SubmitUpstreamAPIKeyResponse
	(*ClearUpstreamOverrideRequest)(nil),   // 10: limen.portal.v1.ClearUpstreamOverrideRequest
	(*ClearUpstreamOverrideResponse)(nil),  // 11: limen.portal.v1.ClearUpstreamOverrideResponse
	(*SetUpstreamLinkEnabledRequest)(nil),  // 12: limen.portal.v1.SetUpstreamLinkEnabledRequest
	(*SetUpstreamLinkEnabledResponse)(nil), // 13: limen.portal.v1.SetUpstreamLinkEnabledResponse
	(*DisconnectRequest)(nil),              // 14: limen.portal.v1.DisconnectRequest
	(*DisconnectResponse)(nil),             // 15: limen.portal.v1.DisconnectResponse
	(*ListMCPClientsRequest)(nil),          // 16: limen.portal.v1.ListMCPClientsRequest
	(*ListMCPClientsResponse)(nil),         // 17: limen.portal.v1.ListMCPClientsResponse
	(*MCPClient)(nil),                      // 18: limen.portal.v1.MCPClient
	(*RevokeMCPClientRequest)(nil),         // 19: limen.portal.v1.RevokeMCPClientRequest
	(*RevokeMCPClientResponse)(nil),        // 20: limen.portal.v1.RevokeMCPClientResponse
	(*GetBillingSummaryRequest)(nil),       // 21: limen.portal.v1.GetBillingSummaryRequest
	(*GetBillingSummaryResponse)(nil),      // 22: limen.portal.v1.GetBillingSummaryResponse
	(*CreateCheckoutSessionRequest)(nil),   // 23: limen.portal.v1.CreateCheckoutSessionRequest
	(*CreateCheckoutSessionResponse)(nil),  // 24: limen.portal.v1.CreateCheckoutSessionResponse
	(*OpenCustomerPortalRequest)(nil),      // 25: limen.portal.v1.OpenCustomerPortalRequest
	(*OpenCustomerPortalResponse)(nil),     // 26: limen.portal.v1.OpenCustomerPortalResponse
}
var file_limen_portal_v1_portal_proto_depIdxs = []int32{
	4,  // 0: limen.portal.v1.ListUpstreamsResponse.upstreams:type_name -> limen.portal.v1.UpstreamSummary
	0,  // 1: limen.portal.v1.UpstreamSummary.link_state:type_name -> limen.portal.v1.LinkState
	5,  // 2: limen.portal.v1.UpstreamSummary.tools:type_name -> limen.portal.v1.UpstreamTool
	0,  // 3: limen.portal.v1.UpstreamSummary.tenant_link_state:type_name -> limen.portal.v1.LinkState
	1,  // 4: limen.portal.v1.UpstreamSummary.static_header_mode:type_name -> limen.portal.v1.StaticHeaderMode
	18, // 5: limen.portal.v1.ListMCPClientsResponse.clients:type_name -> limen.portal.v1.MCPClient
	2,  // 6: limen.portal.v1.PortalService.ListUpstreams:input_type -> limen.portal.v1.ListUpstreamsRequest
	6,  // 7: limen.portal.v1.PortalService.StartConnect:input_type -> limen.portal.v1.StartConnectRequest
	8,  // 8: limen.portal.v1.PortalService.SubmitUpstreamAPIKey:input_type -> limen.portal.v1.SubmitUpstreamAPIKeyRequest
	10, // 9: limen.portal.v1.PortalService.ClearUpstreamOverride:input_type -> limen.portal.v1.ClearUpstreamOverrideRequest
	12, // 10: limen.portal.v1.PortalService.SetUpstreamLinkEnabled:input_type -> limen.portal.v1.SetUpstreamLinkEnabledRequest
	14, // 11: limen.portal.v1.PortalService.Disconnect:input_type -> limen.portal.v1.DisconnectRequest
	16, // 12: limen.portal.v1.PortalService.ListMCPClients:input_type -> limen.portal.v1.ListMCPClientsRequest
	19, // 13: limen.portal.v1.PortalService.RevokeMCPClient:input_type -> limen.portal.v1.RevokeMCPClientRequest
	21, // 14: limen.portal.v1.BillingService.GetBillingSummary:input_type -> limen.portal.v1.GetBillingSummaryRequest
	23, // 15: limen.portal.v1.BillingService.CreateCheckoutSession:input_type -> limen.portal.v1.CreateCheckoutSessionRequest
	25, // 16: limen.portal.v1.BillingService.OpenCustomerPortal:input_type -> limen.portal.v1.OpenCustomerPortalRequest
	3,  // 17: limen.portal.v1.PortalService.ListUpstreams:output_type -> limen.portal.v1.ListUpstreamsResponse
	7,  // 18: limen.portal.v1.PortalService.StartConnect:output_type -> limen.portal.v1.StartConnectResponse
	9,  // 19: limen.portal.v1.PortalService.SubmitUpstreamAPIKey:output_type -> limen.portal.v1.SubmitUpstreamAPIKeyResponse
	11, // 20: limen.portal.v1.PortalService.ClearUpstreamOverride:output_type -> limen.portal.v1.ClearUpstreamOverrideResponse
	13, // 21: limen.portal.v1.PortalService.SetUpstreamLinkEnabled:output_type -> limen.portal.v1.SetUpstreamLinkEnabledResponse
	15, // 22: limen.portal.v1.PortalService.Disconnect:output_type -> limen.portal.v1.DisconnectResponse
	17, // 23: limen.portal.v1.PortalService.ListMCPClients:output_type -> limen.portal.v1.ListMCPClientsResponse
	20, // 24: limen.portal.v1.PortalService.RevokeMCPClient:output_type -> limen.portal.v1.RevokeMCPClientResponse
	22, // 25: limen.portal.v1.BillingService.GetBillingSummary:output_type -> limen.portal.v1.GetBillingSummaryResponse
	24, // 26: limen.portal.v1.BillingService.CreateCheckoutSession:output_type -> limen.portal.v1.CreateCheckoutSessionResponse
	26, // 27: limen.portal.v1.BillingService.OpenCustomerPortal:output_type -> limen.portal.v1.OpenCustomerPortalResponse
	17, // [17:28] is the sub-list for method output_type
	6,  // [6:17] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_limen_portal_v1_portal_proto_init() }
func file_limen_portal_v1_portal_proto_init() {
	if File_limen_portal_v1_portal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_limen_portal_v1_portal_proto_rawDesc), len(file_limen_portal_v1_portal_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_limen_portal_v1_portal_proto_goTypes,
		DependencyIndexes: file_limen_portal_v1_portal_proto_depIdxs,
		EnumInfos:         file_limen_portal_v1_portal_proto_enumTypes,
		MessageInfos:      file_limen_portal_v1_portal_proto_msgTypes,
	}.Build()
	File_limen_portal_v1_portal_proto = out.File
	file_limen_portal_v1_portal_proto_goTypes = nil
	file_limen_portal_v1_portal_proto_depIdxs = nil
}
