// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: limen/admin/v1/admin.proto

package adminv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	adminv1 "github.com/belphemur/limen/internal/admin/adminv1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AdminServiceName is the fully-qualified name of the AdminService service.
	AdminServiceName = "limen.admin.v1.AdminService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AdminServiceCreateUpstreamProcedure is the fully-qualified name of the AdminService's
	// CreateUpstream RPC.
	AdminServiceCreateUpstreamProcedure = "/limen.admin.v1.AdminService/CreateUpstream"
	// AdminServiceUpdateUpstreamProcedure is the fully-qualified name of the AdminService's
	// UpdateUpstream RPC.
	AdminServiceUpdateUpstreamProcedure = "/limen.admin.v1.AdminService/UpdateUpstream"
	// AdminServiceDeleteUpstreamProcedure is the fully-qualified name of the AdminService's
	// DeleteUpstream RPC.
	AdminServiceDeleteUpstreamProcedure = "/limen.admin.v1.AdminService/DeleteUpstream"
	// AdminServiceReindexUpstreamCatalogProcedure is the fully-qualified name of the AdminService's
	// ReindexUpstreamCatalog RPC.
	AdminServiceReindexUpstreamCatalogProcedure = "/limen.admin.v1.AdminService/ReindexUpstreamCatalog"
	// AdminServicePreviewUpstreamContextProcedure is the fully-qualified name of the AdminService's
	// PreviewUpstreamContext RPC.
	AdminServicePreviewUpstreamContextProcedure = "/limen.admin.v1.AdminService/PreviewUpstreamContext"
	// AdminServiceUpdateTenantSettingsProcedure is the fully-qualified name of the AdminService's
	// UpdateTenantSettings RPC.
	AdminServiceUpdateTenantSettingsProcedure = "/limen.admin.v1.AdminService/UpdateTenantSettings"
	// AdminServiceDeleteTenantProcedure is the fully-qualified name of the AdminService's DeleteTenant
	// RPC.
	AdminServiceDeleteTenantProcedure = "/limen.admin.v1.AdminService/DeleteTenant"
)

// AdminServiceClient is a client for the limen.admin.v1.AdminService service.
type AdminServiceClient interface {
	// Upstream catalog CRUD + tenant-wide tool-catalog ops. Admin floor.
	CreateUpstream(context.Context, *connect.Request[adminv1.CreateUpstreamRequest]) (*connect.Response[adminv1.CreateUpstreamResponse], error)
	UpdateUpstream(context.Context, *connect.Request[adminv1.UpdateUpstreamRequest]) (*connect.Response[adminv1.UpdateUpstreamResponse], error)
	DeleteUpstream(context.Context, *connect.Request[adminv1.DeleteUpstreamRequest]) (*connect.Response[adminv1.DeleteUpstreamResponse], error)
	ReindexUpstreamCatalog(context.Context, *connect.Request[adminv1.ReindexUpstreamCatalogRequest]) (*connect.Response[adminv1.ReindexUpstreamCatalogResponse], error)
	PreviewUpstreamContext(context.Context, *connect.Request[adminv1.PreviewUpstreamContextRequest]) (*connect.Response[adminv1.PreviewUpstreamContextResponse], error)
	// Tenant settings + dashboard step-completion toggles. Admin floor.
	UpdateTenantSettings(context.Context, *connect.Request[adminv1.UpdateTenantSettingsRequest]) (*connect.Response[adminv1.UpdateTenantSettingsResponse], error)
	// Owner-only. Limen-side soft-delete; Zitadel org cleanup is manual.
	DeleteTenant(context.Context, *connect.Request[adminv1.DeleteTenantRequest]) (*connect.Response[adminv1.DeleteTenantResponse], error)
}

// NewAdminServiceClient constructs a client for the limen.admin.v1.AdminService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAdminServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AdminServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	adminServiceMethods := adminv1.File_limen_admin_v1_admin_proto.Services().ByName("AdminService").Methods()
	return &adminServiceClient{
		createUpstream: connect.NewClient[adminv1.CreateUpstreamRequest, adminv1.CreateUpstreamResponse](
			httpClient,
			baseURL+AdminServiceCreateUpstreamProcedure,
			connect.WithSchema(adminServiceMethods.ByName("CreateUpstream")),
			connect.WithClientOptions(opts...),
		),
		updateUpstream: connect.NewClient[adminv1.UpdateUpstreamRequest, adminv1.UpdateUpstreamResponse](
			httpClient,
			baseURL+AdminServiceUpdateUpstreamProcedure,
			connect.WithSchema(adminServiceMethods.ByName("UpdateUpstream")),
			connect.WithClientOptions(opts...),
		),
		deleteUpstream: connect.NewClient[adminv1.DeleteUpstreamRequest, adminv1.DeleteUpstreamResponse](
			httpClient,
			baseURL+AdminServiceDeleteUpstreamProcedure,
			connect.WithSchema(adminServiceMethods.ByName("DeleteUpstream")),
			connect.WithClientOptions(opts...),
		),
		reindexUpstreamCatalog: connect.NewClient[adminv1.ReindexUpstreamCatalogRequest, adminv1.ReindexUpstreamCatalogResponse](
			httpClient,
			baseURL+AdminServiceReindexUpstreamCatalogProcedure,
			connect.WithSchema(adminServiceMethods.ByName("ReindexUpstreamCatalog")),
			connect.WithClientOptions(opts...),
		),
		previewUpstreamContext: connect.NewClient[adminv1.PreviewUpstreamContextRequest, adminv1.PreviewUpstreamContextResponse](
			httpClient,
			baseURL+AdminServicePreviewUpstreamContextProcedure,
			connect.WithSchema(adminServiceMethods.ByName("PreviewUpstreamContext")),
			connect.WithClientOptions(opts...),
		),
		updateTenantSettings: connect.NewClient[adminv1.UpdateTenantSettingsRequest, adminv1.UpdateTenantSettingsResponse](
			httpClient,
			baseURL+AdminServiceUpdateTenantSettingsProcedure,
			connect.WithSchema(adminServiceMethods.ByName("UpdateTenantSettings")),
			connect.WithClientOptions(opts...),
		),
		deleteTenant: connect.NewClient[adminv1.DeleteTenantRequest, adminv1.DeleteTenantResponse](
			httpClient,
			baseURL+AdminServiceDeleteTenantProcedure,
			connect.WithSchema(adminServiceMethods.ByName("DeleteTenant")),
			connect.WithClientOptions(opts...),
		),
	}
}

// adminServiceClient implements AdminServiceClient.
type adminServiceClient struct {
	createUpstream         *connect.Client[adminv1.CreateUpstreamRequest, adminv1.CreateUpstreamResponse]
	updateUpstream         *connect.Client[adminv1.UpdateUpstreamRequest, adminv1.UpdateUpstreamResponse]
	deleteUpstream         *connect.Client[adminv1.DeleteUpstreamRequest, adminv1.DeleteUpstreamResponse]
	reindexUpstreamCatalog *connect.Client[adminv1.ReindexUpstreamCatalogRequest, adminv1.ReindexUpstreamCatalogResponse]
	previewUpstreamContext *connect.Client[adminv1.PreviewUpstreamContextRequest, adminv1.PreviewUpstreamContextResponse]
	updateTenantSettings   *connect.Client[adminv1.UpdateTenantSettingsRequest, adminv1.UpdateTenantSettingsResponse]
	deleteTenant           *connect.Client[adminv1.DeleteTenantRequest, adminv1.DeleteTenantResponse]
}

// CreateUpstream calls limen.admin.v1.AdminService.CreateUpstream.
func (c *adminServiceClient) CreateUpstream(ctx context.Context, req *connect.Request[adminv1.CreateUpstreamRequest]) (*connect.Response[adminv1.CreateUpstreamResponse], error) {
	return c.createUpstream.CallUnary(ctx, req)
}

// UpdateUpstream calls limen.admin.v1.AdminService.UpdateUpstream.
func (c *adminServiceClient) UpdateUpstream(ctx context.Context, req *connect.Request[adminv1.UpdateUpstreamRequest]) (*connect.Response[adminv1.UpdateUpstreamResponse], error) {
	return c.updateUpstream.CallUnary(ctx, req)
}

// DeleteUpstream calls limen.admin.v1.AdminService.DeleteUpstream.
func (c *adminServiceClient) DeleteUpstream(ctx context.Context, req *connect.Request[adminv1.DeleteUpstreamRequest]) (*connect.Response[adminv1.DeleteUpstreamResponse], error) {
	return c.deleteUpstream.CallUnary(ctx, req)
}

// ReindexUpstreamCatalog calls limen.admin.v1.AdminService.ReindexUpstreamCatalog.
func (c *adminServiceClient) ReindexUpstreamCatalog(ctx context.Context, req *connect.Request[adminv1.ReindexUpstreamCatalogRequest]) (*connect.Response[adminv1.ReindexUpstreamCatalogResponse], error) {
	return c.reindexUpstreamCatalog.CallUnary(ctx, req)
}

// PreviewUpstreamContext calls limen.admin.v1.AdminService.PreviewUpstreamContext.
func (c *adminServiceClient) PreviewUpstreamContext(ctx context.Context, req *connect.Request[adminv1.PreviewUpstreamContextRequest]) (*connect.Response[adminv1.PreviewUpstreamContextResponse], error) {
	return c.previewUpstreamContext.CallUnary(ctx, req)
}

// UpdateTenantSettings calls limen.admin.v1.AdminService.UpdateTenantSettings.
func (c *adminServiceClient) UpdateTenantSettings(ctx context.Context, req *connect.Request[adminv1.UpdateTenantSettingsRequest]) (*connect.Response[adminv1.UpdateTenantSettingsResponse], error) {
	return c.updateTenantSettings.CallUnary(ctx, req)
}

// DeleteTenant calls limen.admin.v1.AdminService.DeleteTenant.
func (c *adminServiceClient) DeleteTenant(ctx context.Context, req *connect.Request[adminv1.DeleteTenantRequest]) (*connect.Response[adminv1.DeleteTenantResponse], error) {
	return c.deleteTenant.CallUnary(ctx, req)
}

// AdminServiceHandler is an implementation of the limen.admin.v1.AdminService service.
type AdminServiceHandler interface {
	// Upstream catalog CRUD + tenant-wide tool-catalog ops. Admin floor.
	CreateUpstream(context.Context, *connect.Request[adminv1.CreateUpstreamRequest]) (*connect.Response[adminv1.CreateUpstreamResponse], error)
	UpdateUpstream(context.Context, *connect.Request[adminv1.UpdateUpstreamRequest]) (*connect.Response[adminv1.UpdateUpstreamResponse], error)
	DeleteUpstream(context.Context, *connect.Request[adminv1.DeleteUpstreamRequest]) (*connect.Response[adminv1.DeleteUpstreamResponse], error)
	ReindexUpstreamCatalog(context.Context, *connect.Request[adminv1.ReindexUpstreamCatalogRequest]) (*connect.Response[adminv1.ReindexUpstreamCatalogResponse], error)
	PreviewUpstreamContext(context.Context, *connect.Request[adminv1.PreviewUpstreamContextRequest]) (*connect.Response[adminv1.PreviewUpstreamContextResponse], error)
	// Tenant settings + dashboard step-completion toggles. Admin floor.
	UpdateTenantSettings(context.Context, *connect.Request[adminv1.UpdateTenantSettingsRequest]) (*connect.Response[adminv1.UpdateTenantSettingsResponse], error)
	// Owner-only. Limen-side soft-delete; Zitadel org cleanup is manual.
	DeleteTenant(context.Context, *connect.Request[adminv1.DeleteTenantRequest]) (*connect.Response[adminv1.DeleteTenantResponse], error)
}

// NewAdminServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAdminServiceHandler(svc AdminServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	adminServiceMethods := adminv1.File_limen_admin_v1_admin_proto.Services().ByName("AdminService").Methods()
	adminServiceCreateUpstreamHandler := connect.NewUnaryHandler(
		AdminServiceCreateUpstreamProcedure,
		svc.CreateUpstream,
		connect.WithSchema(adminServiceMethods.ByName("CreateUpstream")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceUpdateUpstreamHandler := connect.NewUnaryHandler(
		AdminServiceUpdateUpstreamProcedure,
		svc.UpdateUpstream,
		connect.WithSchema(adminServiceMethods.ByName("UpdateUpstream")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceDeleteUpstreamHandler := connect.NewUnaryHandler(
		AdminServiceDeleteUpstreamProcedure,
		svc.DeleteUpstream,
		connect.WithSchema(adminServiceMethods.ByName("DeleteUpstream")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceReindexUpstreamCatalogHandler := connect.NewUnaryHandler(
		AdminServiceReindexUpstreamCatalogProcedure,
		svc.ReindexUpstreamCatalog,
		connect.WithSchema(adminServiceMethods.ByName("ReindexUpstreamCatalog")),
		connect.WithHandlerOptions(opts...),
	)
	adminServicePreviewUpstreamContextHandler := connect.NewUnaryHandler(
		AdminServicePreviewUpstreamContextProcedure,
		svc.PreviewUpstreamContext,
		connect.WithSchema(adminServiceMethods.ByName("PreviewUpstreamContext")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceUpdateTenantSettingsHandler := connect.NewUnaryHandler(
		AdminServiceUpdateTenantSettingsProcedure,
		svc.UpdateTenantSettings,
		connect.WithSchema(adminServiceMethods.ByName("UpdateTenantSettings")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceDeleteTenantHandler := connect.NewUnaryHandler(
		AdminServiceDeleteTenantProcedure,
		svc.DeleteTenant,
		connect.WithSchema(adminServiceMethods.ByName("DeleteTenant")),
		connect.WithHandlerOptions(opts...),
	)
	return "/limen.admin.v1.AdminService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AdminServiceCreateUpstreamProcedure:
			adminServiceCreateUpstreamHandler.ServeHTTP(w, r)
		case AdminServiceUpdateUpstreamProcedure:
			adminServiceUpdateUpstreamHandler.ServeHTTP(w, r)
		case AdminServiceDeleteUpstreamProcedure:
			adminServiceDeleteUpstreamHandler.ServeHTTP(w, r)
		case AdminServiceReindexUpstreamCatalogProcedure:
			adminServiceReindexUpstreamCatalogHandler.ServeHTTP(w, r)
		case AdminServicePreviewUpstreamContextProcedure:
			adminServicePreviewUpstreamContextHandler.ServeHTTP(w, r)
		case AdminServiceUpdateTenantSettingsProcedure:
			adminServiceUpdateTenantSettingsHandler.ServeHTTP(w, r)
		case AdminServiceDeleteTenantProcedure:
			adminServiceDeleteTenantHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAdminServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAdminServiceHandler struct{}

func (UnimplementedAdminServiceHandler) CreateUpstream(context.Context, *connect.Request[adminv1.CreateUpstreamRequest]) (*connect.Response[adminv1.CreateUpstreamResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("limen.admin.v1.AdminService.CreateUpstream is not implemented"))
}

func (UnimplementedAdminServiceHandler) UpdateUpstream(context.Context, *connect.Request[adminv1.UpdateUpstreamRequest]) (*connect.Response[adminv1.UpdateUpstreamResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("limen.admin.v1.AdminService.UpdateUpstream is not implemented"))
}

func (UnimplementedAdminServiceHandler) DeleteUpstream(context.Context, *connect.Request[adminv1.DeleteUpstreamRequest]) (*connect.Response[adminv1.DeleteUpstreamResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("limen.admin.v1.AdminService.DeleteUpstream is not implemented"))
}

func (UnimplementedAdminServiceHandler) ReindexUpstreamCatalog(context.Context, *connect.Request[adminv1.ReindexUpstreamCatalogRequest]) (*connect.Response[adminv1.ReindexUpstreamCatalogResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("limen.admin.v1.AdminService.ReindexUpstreamCatalog is not implemented"))
}

func (UnimplementedAdminServiceHandler) PreviewUpstreamContext(context.Context, *connect.Request[adminv1.PreviewUpstreamContextRequest]) (*connect.Response[adminv1.PreviewUpstreamContextResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("limen.admin.v1.AdminService.PreviewUpstreamContext is not implemented"))
}

func (UnimplementedAdminServiceHandler) UpdateTenantSettings(context.Context, *connect.Request[adminv1.UpdateTenantSettingsRequest]) (*connect.Response[adminv1.UpdateTenantSettingsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("limen.admin.v1.AdminService.UpdateTenantSettings is not implemented"))
}

func (UnimplementedAdminServiceHandler) DeleteTenant(context.Context, *connect.Request[adminv1.DeleteTenantRequest]) (*connect.Response[adminv1.DeleteTenantResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("limen.admin.v1.AdminService.DeleteTenant is not implemented"))
}
