// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: limen/admin/v1/admin.proto

package adminv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	adminv1 "github.com/belphemur/limen/internal/admin/adminv1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AdminServiceName is the fully-qualified name of the AdminService service.
	AdminServiceName = "limen.admin.v1.AdminService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AdminServiceCreateUpstreamProcedure is the fully-qualified name of the AdminService's
	// CreateUpstream RPC.
	AdminServiceCreateUpstreamProcedure = "/limen.admin.v1.AdminService/CreateUpstream"
	// AdminServiceUpdateUpstreamProcedure is the fully-qualified name of the AdminService's
	// UpdateUpstream RPC.
	AdminServiceUpdateUpstreamProcedure = "/limen.admin.v1.AdminService/UpdateUpstream"
	// AdminServiceDeleteUpstreamProcedure is the fully-qualified name of the AdminService's
	// DeleteUpstream RPC.
	AdminServiceDeleteUpstreamProcedure = "/limen.admin.v1.AdminService/DeleteUpstream"
	// AdminServiceReindexUpstreamCatalogProcedure is the fully-qualified name of the AdminService's
	// ReindexUpstreamCatalog RPC.
	AdminServiceReindexUpstreamCatalogProcedure = "/limen.admin.v1.AdminService/ReindexUpstreamCatalog"
	// AdminServicePreviewUpstreamContextProcedure is the fully-qualified name of the AdminService's
	// PreviewUpstreamContext RPC.
	AdminServicePreviewUpstreamContextProcedure = "/limen.admin.v1.AdminService/PreviewUpstreamContext"
	// AdminServiceGetTenantSettingsProcedure is the fully-qualified name of the AdminService's
	// GetTenantSettings RPC.
	AdminServiceGetTenantSettingsProcedure = "/limen.admin.v1.AdminService/GetTenantSettings"
	// AdminServiceUpdateTenantSettingsProcedure is the fully-qualified name of the AdminService's
	// UpdateTenantSettings RPC.
	AdminServiceUpdateTenantSettingsProcedure = "/limen.admin.v1.AdminService/UpdateTenantSettings"
	// AdminServiceListIDEPresetsProcedure is the fully-qualified name of the AdminService's
	// ListIDEPresets RPC.
	AdminServiceListIDEPresetsProcedure = "/limen.admin.v1.AdminService/ListIDEPresets"
	// AdminServiceListAllowlistEntriesProcedure is the fully-qualified name of the AdminService's
	// ListAllowlistEntries RPC.
	AdminServiceListAllowlistEntriesProcedure = "/limen.admin.v1.AdminService/ListAllowlistEntries"
	// AdminServiceAddAllowlistEntryProcedure is the fully-qualified name of the AdminService's
	// AddAllowlistEntry RPC.
	AdminServiceAddAllowlistEntryProcedure = "/limen.admin.v1.AdminService/AddAllowlistEntry"
	// AdminServiceUpdateAllowlistEntryProcedure is the fully-qualified name of the AdminService's
	// UpdateAllowlistEntry RPC.
	AdminServiceUpdateAllowlistEntryProcedure = "/limen.admin.v1.AdminService/UpdateAllowlistEntry"
	// AdminServiceRemoveAllowlistEntryProcedure is the fully-qualified name of the AdminService's
	// RemoveAllowlistEntry RPC.
	AdminServiceRemoveAllowlistEntryProcedure = "/limen.admin.v1.AdminService/RemoveAllowlistEntry"
	// AdminServiceApplyIDEPresetProcedure is the fully-qualified name of the AdminService's
	// ApplyIDEPreset RPC.
	AdminServiceApplyIDEPresetProcedure = "/limen.admin.v1.AdminService/ApplyIDEPreset"
	// AdminServiceRemoveIDEPresetProcedure is the fully-qualified name of the AdminService's
	// RemoveIDEPreset RPC.
	AdminServiceRemoveIDEPresetProcedure = "/limen.admin.v1.AdminService/RemoveIDEPreset"
	// AdminServiceMarkIDEChoiceSkippedProcedure is the fully-qualified name of the AdminService's
	// MarkIDEChoiceSkipped RPC.
	AdminServiceMarkIDEChoiceSkippedProcedure = "/limen.admin.v1.AdminService/MarkIDEChoiceSkipped"
	// AdminServiceDeleteTenantProcedure is the fully-qualified name of the AdminService's DeleteTenant
	// RPC.
	AdminServiceDeleteTenantProcedure = "/limen.admin.v1.AdminService/DeleteTenant"
	// AdminServiceListMembersProcedure is the fully-qualified name of the AdminService's ListMembers
	// RPC.
	AdminServiceListMembersProcedure = "/limen.admin.v1.AdminService/ListMembers"
	// AdminServiceInviteMemberProcedure is the fully-qualified name of the AdminService's InviteMember
	// RPC.
	AdminServiceInviteMemberProcedure = "/limen.admin.v1.AdminService/InviteMember"
	// AdminServiceUpdateMemberRoleProcedure is the fully-qualified name of the AdminService's
	// UpdateMemberRole RPC.
	AdminServiceUpdateMemberRoleProcedure = "/limen.admin.v1.AdminService/UpdateMemberRole"
	// AdminServiceRemoveMemberProcedure is the fully-qualified name of the AdminService's RemoveMember
	// RPC.
	AdminServiceRemoveMemberProcedure = "/limen.admin.v1.AdminService/RemoveMember"
	// AdminServiceCreateServiceAccountProcedure is the fully-qualified name of the AdminService's
	// CreateServiceAccount RPC.
	AdminServiceCreateServiceAccountProcedure = "/limen.admin.v1.AdminService/CreateServiceAccount"
	// AdminServiceGetServiceAccountProcedure is the fully-qualified name of the AdminService's
	// GetServiceAccount RPC.
	AdminServiceGetServiceAccountProcedure = "/limen.admin.v1.AdminService/GetServiceAccount"
	// AdminServiceUpdateServiceAccountProcedure is the fully-qualified name of the AdminService's
	// UpdateServiceAccount RPC.
	AdminServiceUpdateServiceAccountProcedure = "/limen.admin.v1.AdminService/UpdateServiceAccount"
	// AdminServiceListServiceAccountsProcedure is the fully-qualified name of the AdminService's
	// ListServiceAccounts RPC.
	AdminServiceListServiceAccountsProcedure = "/limen.admin.v1.AdminService/ListServiceAccounts"
	// AdminServiceDeleteServiceAccountProcedure is the fully-qualified name of the AdminService's
	// DeleteServiceAccount RPC.
	AdminServiceDeleteServiceAccountProcedure = "/limen.admin.v1.AdminService/DeleteServiceAccount"
	// AdminServiceRegenerateServiceAccountTokenProcedure is the fully-qualified name of the
	// AdminService's RegenerateServiceAccountToken RPC.
	AdminServiceRegenerateServiceAccountTokenProcedure = "/limen.admin.v1.AdminService/RegenerateServiceAccountToken"
	// AdminServiceListServiceAccountUpstreamLinksProcedure is the fully-qualified name of the
	// AdminService's ListServiceAccountUpstreamLinks RPC.
	AdminServiceListServiceAccountUpstreamLinksProcedure = "/limen.admin.v1.AdminService/ListServiceAccountUpstreamLinks"
	// AdminServiceSetServiceAccountLinkEnabledProcedure is the fully-qualified name of the
	// AdminService's SetServiceAccountLinkEnabled RPC.
	AdminServiceSetServiceAccountLinkEnabledProcedure = "/limen.admin.v1.AdminService/SetServiceAccountLinkEnabled"
	// AdminServiceStartServiceAccountConnectProcedure is the fully-qualified name of the AdminService's
	// StartServiceAccountConnect RPC.
	AdminServiceStartServiceAccountConnectProcedure = "/limen.admin.v1.AdminService/StartServiceAccountConnect"
	// AdminServiceSubmitServiceAccountAPIKeyProcedure is the fully-qualified name of the AdminService's
	// SubmitServiceAccountAPIKey RPC.
	AdminServiceSubmitServiceAccountAPIKeyProcedure = "/limen.admin.v1.AdminService/SubmitServiceAccountAPIKey"
	// AdminServiceClearServiceAccountOverrideProcedure is the fully-qualified name of the
	// AdminService's ClearServiceAccountOverride RPC.
	AdminServiceClearServiceAccountOverrideProcedure = "/limen.admin.v1.AdminService/ClearServiceAccountOverride"
	// AdminServiceDisconnectServiceAccountUpstreamProcedure is the fully-qualified name of the
	// AdminService's DisconnectServiceAccountUpstream RPC.
	AdminServiceDisconnectServiceAccountUpstreamProcedure = "/limen.admin.v1.AdminService/DisconnectServiceAccountUpstream"
)

// AdminServiceClient is a client for the limen.admin.v1.AdminService service.
type AdminServiceClient interface {
	// Upstream catalog CRUD + tenant-wide tool-catalog ops. Admin floor.
	CreateUpstream(context.Context, *connect.Request[adminv1.CreateUpstreamRequest]) (*connect.Response[adminv1.CreateUpstreamResponse], error)
	UpdateUpstream(context.Context, *connect.Request[adminv1.UpdateUpstreamRequest]) (*connect.Response[adminv1.UpdateUpstreamResponse], error)
	DeleteUpstream(context.Context, *connect.Request[adminv1.DeleteUpstreamRequest]) (*connect.Response[adminv1.DeleteUpstreamResponse], error)
	ReindexUpstreamCatalog(context.Context, *connect.Request[adminv1.ReindexUpstreamCatalogRequest]) (*connect.Response[adminv1.ReindexUpstreamCatalogResponse], error)
	PreviewUpstreamContext(context.Context, *connect.Request[adminv1.PreviewUpstreamContextRequest]) (*connect.Response[adminv1.PreviewUpstreamContextResponse], error)
	// Tenant settings + dashboard step-completion toggles. Admin floor.
	GetTenantSettings(context.Context, *connect.Request[adminv1.GetTenantSettingsRequest]) (*connect.Response[adminv1.GetTenantSettingsResponse], error)
	UpdateTenantSettings(context.Context, *connect.Request[adminv1.UpdateTenantSettingsRequest]) (*connect.Response[adminv1.UpdateTenantSettingsResponse], error)
	// IDE presets + per-tenant redirect-URI allowlist. Admin floor.
	// See docs/phases/phase-09f-ide-presets-and-allowlist.md.
	ListIDEPresets(context.Context, *connect.Request[adminv1.ListIDEPresetsRequest]) (*connect.Response[adminv1.ListIDEPresetsResponse], error)
	ListAllowlistEntries(context.Context, *connect.Request[adminv1.ListAllowlistEntriesRequest]) (*connect.Response[adminv1.ListAllowlistEntriesResponse], error)
	AddAllowlistEntry(context.Context, *connect.Request[adminv1.AddAllowlistEntryRequest]) (*connect.Response[adminv1.AddAllowlistEntryResponse], error)
	UpdateAllowlistEntry(context.Context, *connect.Request[adminv1.UpdateAllowlistEntryRequest]) (*connect.Response[adminv1.UpdateAllowlistEntryResponse], error)
	RemoveAllowlistEntry(context.Context, *connect.Request[adminv1.RemoveAllowlistEntryRequest]) (*connect.Response[adminv1.RemoveAllowlistEntryResponse], error)
	ApplyIDEPreset(context.Context, *connect.Request[adminv1.ApplyIDEPresetRequest]) (*connect.Response[adminv1.ApplyIDEPresetResponse], error)
	RemoveIDEPreset(context.Context, *connect.Request[adminv1.RemoveIDEPresetRequest]) (*connect.Response[adminv1.RemoveIDEPresetResponse], error)
	MarkIDEChoiceSkipped(context.Context, *connect.Request[adminv1.MarkIDEChoiceSkippedRequest]) (*connect.Response[adminv1.MarkIDEChoiceSkippedResponse], error)
	// Owner-only. Limen-side soft-delete; Zitadel org cleanup is manual.
	DeleteTenant(context.Context, *connect.Request[adminv1.DeleteTenantRequest]) (*connect.Response[adminv1.DeleteTenantResponse], error)
	// Member management. Pass-through to Zitadel User V2 +
	// Authorization V2; Limen stores no mirror tables. See
	// docs/phases/phase-09c-tenant-admin-spa.md "Member management".
	// All four require admin (owner satisfies admin).
	ListMembers(context.Context, *connect.Request[adminv1.ListMembersRequest]) (*connect.Response[adminv1.ListMembersResponse], error)
	InviteMember(context.Context, *connect.Request[adminv1.InviteMemberRequest]) (*connect.Response[adminv1.InviteMemberResponse], error)
	UpdateMemberRole(context.Context, *connect.Request[adminv1.UpdateMemberRoleRequest]) (*connect.Response[adminv1.UpdateMemberRoleResponse], error)
	RemoveMember(context.Context, *connect.Request[adminv1.RemoveMemberRequest]) (*connect.Response[adminv1.RemoveMemberResponse], error)
	// Service account management. Admin floor.
	// Service accounts are Zitadel machine users mirrored locally. See
	// docs/phases/phase-09i-service-accounts.md.
	CreateServiceAccount(context.Context, *connect.Request[adminv1.CreateServiceAccountRequest]) (*connect.Response[adminv1.CreateServiceAccountResponse], error)
	GetServiceAccount(context.Context, *connect.Request[adminv1.GetServiceAccountRequest]) (*connect.Response[adminv1.GetServiceAccountResponse], error)
	UpdateServiceAccount(context.Context, *connect.Request[adminv1.UpdateServiceAccountRequest]) (*connect.Response[adminv1.UpdateServiceAccountResponse], error)
	ListServiceAccounts(context.Context, *connect.Request[adminv1.ListServiceAccountsRequest]) (*connect.Response[adminv1.ListServiceAccountsResponse], error)
	DeleteServiceAccount(context.Context, *connect.Request[adminv1.DeleteServiceAccountRequest]) (*connect.Response[adminv1.DeleteServiceAccountResponse], error)
	RegenerateServiceAccountToken(context.Context, *connect.Request[adminv1.RegenerateServiceAccountTokenRequest]) (*connect.Response[adminv1.RegenerateServiceAccountTokenResponse], error)
	// Service account upstream link management. Admin floor.
	ListServiceAccountUpstreamLinks(context.Context, *connect.Request[adminv1.ListServiceAccountUpstreamLinksRequest]) (*connect.Response[adminv1.ListServiceAccountUpstreamLinksResponse], error)
	SetServiceAccountLinkEnabled(context.Context, *connect.Request[adminv1.SetServiceAccountLinkEnabledRequest]) (*connect.Response[adminv1.SetServiceAccountLinkEnabledResponse], error)
	// Service account upstream linking — full lifecycle (OAuth, API key,
	// disconnect). Admin floor. See docs/phases/phase-09k-sa-upstream-linking.md.
	StartServiceAccountConnect(context.Context, *connect.Request[adminv1.StartServiceAccountConnectRequest]) (*connect.Response[adminv1.StartServiceAccountConnectResponse], error)
	SubmitServiceAccountAPIKey(context.Context, *connect.Request[adminv1.SubmitServiceAccountAPIKeyRequest]) (*connect.Response[adminv1.SubmitServiceAccountAPIKeyResponse], error)
	ClearServiceAccountOverride(context.Context, *connect.Request[adminv1.ClearServiceAccountOverrideRequest]) (*connect.Response[adminv1.ClearServiceAccountOverrideResponse], error)
	DisconnectServiceAccountUpstream(context.Context, *connect.Request[adminv1.DisconnectServiceAccountUpstreamRequest]) (*connect.Response[adminv1.DisconnectServiceAccountUpstreamResponse], error)
}

// NewAdminServiceClient constructs a client for the limen.admin.v1.AdminService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAdminServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AdminServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	adminServiceMethods := adminv1.File_limen_admin_v1_admin_proto.Services().ByName("AdminService").Methods()
	return &adminServiceClient{
		createUpstream: connect.NewClient[adminv1.CreateUpstreamRequest, adminv1.CreateUpstreamResponse](
			httpClient,
			baseURL+AdminServiceCreateUpstreamProcedure,
			connect.WithSchema(adminServiceMethods.ByName("CreateUpstream")),
			connect.WithClientOptions(opts...),
		),
		updateUpstream: connect.NewClient[adminv1.UpdateUpstreamRequest, adminv1.UpdateUpstreamResponse](
			httpClient,
			baseURL+AdminServiceUpdateUpstreamProcedure,
			connect.WithSchema(adminServiceMethods.ByName("UpdateUpstream")),
			connect.WithClientOptions(opts...),
		),
		deleteUpstream: connect.NewClient[adminv1.DeleteUpstreamRequest, adminv1.DeleteUpstreamResponse](
			httpClient,
			baseURL+AdminServiceDeleteUpstreamProcedure,
			connect.WithSchema(adminServiceMethods.ByName("DeleteUpstream")),
			connect.WithClientOptions(opts...),
		),
		reindexUpstreamCatalog: connect.NewClient[adminv1.ReindexUpstreamCatalogRequest, adminv1.ReindexUpstreamCatalogResponse](
			httpClient,
			baseURL+AdminServiceReindexUpstreamCatalogProcedure,
			connect.WithSchema(adminServiceMethods.ByName("ReindexUpstreamCatalog")),
			connect.WithClientOptions(opts...),
		),
		previewUpstreamContext: connect.NewClient[adminv1.PreviewUpstreamContextRequest, adminv1.PreviewUpstreamContextResponse](
			httpClient,
			baseURL+AdminServicePreviewUpstreamContextProcedure,
			connect.WithSchema(adminServiceMethods.ByName("PreviewUpstreamContext")),
			connect.WithClientOptions(opts...),
		),
		getTenantSettings: connect.NewClient[adminv1.GetTenantSettingsRequest, adminv1.GetTenantSettingsResponse](
			httpClient,
			baseURL+AdminServiceGetTenantSettingsProcedure,
			connect.WithSchema(adminServiceMethods.ByName("GetTenantSettings")),
			connect.WithClientOptions(opts...),
		),
		updateTenantSettings: connect.NewClient[adminv1.UpdateTenantSettingsRequest, adminv1.UpdateTenantSettingsResponse](
			httpClient,
			baseURL+AdminServiceUpdateTenantSettingsProcedure,
			connect.WithSchema(adminServiceMethods.ByName("UpdateTenantSettings")),
			connect.WithClientOptions(opts...),
		),
		listIDEPresets: connect.NewClient[adminv1.ListIDEPresetsRequest, adminv1.ListIDEPresetsResponse](
			httpClient,
			baseURL+AdminServiceListIDEPresetsProcedure,
			connect.WithSchema(adminServiceMethods.ByName("ListIDEPresets")),
			connect.WithClientOptions(opts...),
		),
		listAllowlistEntries: connect.NewClient[adminv1.ListAllowlistEntriesRequest, adminv1.ListAllowlistEntriesResponse](
			httpClient,
			baseURL+AdminServiceListAllowlistEntriesProcedure,
			connect.WithSchema(adminServiceMethods.ByName("ListAllowlistEntries")),
			connect.WithClientOptions(opts...),
		),
		addAllowlistEntry: connect.NewClient[adminv1.AddAllowlistEntryRequest, adminv1.AddAllowlistEntryResponse](
			httpClient,
			baseURL+AdminServiceAddAllowlistEntryProcedure,
			connect.WithSchema(adminServiceMethods.ByName("AddAllowlistEntry")),
			connect.WithClientOptions(opts...),
		),
		updateAllowlistEntry: connect.NewClient[adminv1.UpdateAllowlistEntryRequest, adminv1.UpdateAllowlistEntryResponse](
			httpClient,
			baseURL+AdminServiceUpdateAllowlistEntryProcedure,
			connect.WithSchema(adminServiceMethods.ByName("UpdateAllowlistEntry")),
			connect.WithClientOptions(opts...),
		),
		removeAllowlistEntry: connect.NewClient[adminv1.RemoveAllowlistEntryRequest, adminv1.RemoveAllowlistEntryResponse](
			httpClient,
			baseURL+AdminServiceRemoveAllowlistEntryProcedure,
			connect.WithSchema(adminServiceMethods.ByName("RemoveAllowlistEntry")),
			connect.WithClientOptions(opts...),
		),
		applyIDEPreset: connect.NewClient[adminv1.ApplyIDEPresetRequest, adminv1.ApplyIDEPresetResponse](
			httpClient,
			baseURL+AdminServiceApplyIDEPresetProcedure,
			connect.WithSchema(adminServiceMethods.ByName("ApplyIDEPreset")),
			connect.WithClientOptions(opts...),
		),
		removeIDEPreset: connect.NewClient[adminv1.RemoveIDEPresetRequest, adminv1.RemoveIDEPresetResponse](
			httpClient,
			baseURL+AdminServiceRemoveIDEPresetProcedure,
			connect.WithSchema(adminServiceMethods.ByName("RemoveIDEPreset")),
			connect.WithClientOptions(opts...),
		),
		markIDEChoiceSkipped: connect.NewClient[adminv1.MarkIDEChoiceSkippedRequest, adminv1.MarkIDEChoiceSkippedResponse](
			httpClient,
			baseURL+AdminServiceMarkIDEChoiceSkippedProcedure,
			connect.WithSchema(adminServiceMethods.ByName("MarkIDEChoiceSkipped")),
			connect.WithClientOptions(opts...),
		),
		deleteTenant: connect.NewClient[adminv1.DeleteTenantRequest, adminv1.DeleteTenantResponse](
			httpClient,
			baseURL+AdminServiceDeleteTenantProcedure,
			connect.WithSchema(adminServiceMethods.ByName("DeleteTenant")),
			connect.WithClientOptions(opts...),
		),
		listMembers: connect.NewClient[adminv1.ListMembersRequest, adminv1.ListMembersResponse](
			httpClient,
			baseURL+AdminServiceListMembersProcedure,
			connect.WithSchema(adminServiceMethods.ByName("ListMembers")),
			connect.WithClientOptions(opts...),
		),
		inviteMember: connect.NewClient[adminv1.InviteMemberRequest, adminv1.InviteMemberResponse](
			httpClient,
			baseURL+AdminServiceInviteMemberProcedure,
			connect.WithSchema(adminServiceMethods.ByName("InviteMember")),
			connect.WithClientOptions(opts...),
		),
		updateMemberRole: connect.NewClient[adminv1.UpdateMemberRoleRequest, adminv1.UpdateMemberRoleResponse](
			httpClient,
			baseURL+AdminServiceUpdateMemberRoleProcedure,
			connect.WithSchema(adminServiceMethods.ByName("UpdateMemberRole")),
			connect.WithClientOptions(opts...),
		),
		removeMember: connect.NewClient[adminv1.RemoveMemberRequest, adminv1.RemoveMemberResponse](
			httpClient,
			baseURL+AdminServiceRemoveMemberProcedure,
			connect.WithSchema(adminServiceMethods.ByName("RemoveMember")),
			connect.WithClientOptions(opts...),
		),
		createServiceAccount: connect.NewClient[adminv1.CreateServiceAccountRequest, adminv1.CreateServiceAccountResponse](
			httpClient,
			baseURL+AdminServiceCreateServiceAccountProcedure,
			connect.WithSchema(adminServiceMethods.ByName("CreateServiceAccount")),
			connect.WithClientOptions(opts...),
		),
		getServiceAccount: connect.NewClient[adminv1.GetServiceAccountRequest, adminv1.GetServiceAccountResponse](
			httpClient,
			baseURL+AdminServiceGetServiceAccountProcedure,
			connect.WithSchema(adminServiceMethods.ByName("GetServiceAccount")),
			connect.WithClientOptions(opts...),
		),
		updateServiceAccount: connect.NewClient[adminv1.UpdateServiceAccountRequest, adminv1.UpdateServiceAccountResponse](
			httpClient,
			baseURL+AdminServiceUpdateServiceAccountProcedure,
			connect.WithSchema(adminServiceMethods.ByName("UpdateServiceAccount")),
			connect.WithClientOptions(opts...),
		),
		listServiceAccounts: connect.NewClient[adminv1.ListServiceAccountsRequest, adminv1.ListServiceAccountsResponse](
			httpClient,
			baseURL+AdminServiceListServiceAccountsProcedure,
			connect.WithSchema(adminServiceMethods.ByName("ListServiceAccounts")),
			connect.WithClientOptions(opts...),
		),
		deleteServiceAccount: connect.NewClient[adminv1.DeleteServiceAccountRequest, adminv1.DeleteServiceAccountResponse](
			httpClient,
			baseURL+AdminServiceDeleteServiceAccountProcedure,
			connect.WithSchema(adminServiceMethods.ByName("DeleteServiceAccount")),
			connect.WithClientOptions(opts...),
		),
		regenerateServiceAccountToken: connect.NewClient[adminv1.RegenerateServiceAccountTokenRequest, adminv1.RegenerateServiceAccountTokenResponse](
			httpClient,
			baseURL+AdminServiceRegenerateServiceAccountTokenProcedure,
			connect.WithSchema(adminServiceMethods.ByName("RegenerateServiceAccountToken")),
			connect.WithClientOptions(opts...),
		),
		listServiceAccountUpstreamLinks: connect.NewClient[adminv1.ListServiceAccountUpstreamLinksRequest, adminv1.ListServiceAccountUpstreamLinksResponse](
			httpClient,
			baseURL+AdminServiceListServiceAccountUpstreamLinksProcedure,
			connect.WithSchema(adminServiceMethods.ByName("ListServiceAccountUpstreamLinks")),
			connect.WithClientOptions(opts...),
		),
		setServiceAccountLinkEnabled: connect.NewClient[adminv1.SetServiceAccountLinkEnabledRequest, adminv1.SetServiceAccountLinkEnabledResponse](
			httpClient,
			baseURL+AdminServiceSetServiceAccountLinkEnabledProcedure,
			connect.WithSchema(adminServiceMethods.ByName("SetServiceAccountLinkEnabled")),
			connect.WithClientOptions(opts...),
		),
		startServiceAccountConnect: connect.NewClient[adminv1.StartServiceAccountConnectRequest, adminv1.StartServiceAccountConnectResponse](
			httpClient,
			baseURL+AdminServiceStartServiceAccountConnectProcedure,
			connect.WithSchema(adminServiceMethods.ByName("StartServiceAccountConnect")),
			connect.WithClientOptions(opts...),
		),
		submitServiceAccountAPIKey: connect.NewClient[adminv1.SubmitServiceAccountAPIKeyRequest, adminv1.SubmitServiceAccountAPIKeyResponse](
			httpClient,
			baseURL+AdminServiceSubmitServiceAccountAPIKeyProcedure,
			connect.WithSchema(adminServiceMethods.ByName("SubmitServiceAccountAPIKey")),
			connect.WithClientOptions(opts...),
		),
		clearServiceAccountOverride: connect.NewClient[adminv1.ClearServiceAccountOverrideRequest, adminv1.ClearServiceAccountOverrideResponse](
			httpClient,
			baseURL+AdminServiceClearServiceAccountOverrideProcedure,
			connect.WithSchema(adminServiceMethods.ByName("ClearServiceAccountOverride")),
			connect.WithClientOptions(opts...),
		),
		disconnectServiceAccountUpstream: connect.NewClient[adminv1.DisconnectServiceAccountUpstreamRequest, adminv1.DisconnectServiceAccountUpstreamResponse](
			httpClient,
			baseURL+AdminServiceDisconnectServiceAccountUpstreamProcedure,
			connect.WithSchema(adminServiceMethods.ByName("DisconnectServiceAccountUpstream")),
			connect.WithClientOptions(opts...),
		),
	}
}

// adminServiceClient implements AdminServiceClient.
type adminServiceClient struct {
	createUpstream                   *connect.Client[adminv1.CreateUpstreamRequest, adminv1.CreateUpstreamResponse]
	updateUpstream                   *connect.Client[adminv1.UpdateUpstreamRequest, adminv1.UpdateUpstreamResponse]
	deleteUpstream                   *connect.Client[adminv1.DeleteUpstreamRequest, adminv1.DeleteUpstreamResponse]
	reindexUpstreamCatalog           *connect.Client[adminv1.ReindexUpstreamCatalogRequest, adminv1.ReindexUpstreamCatalogResponse]
	previewUpstreamContext           *connect.Client[adminv1.PreviewUpstreamContextRequest, adminv1.PreviewUpstreamContextResponse]
	getTenantSettings                *connect.Client[adminv1.GetTenantSettingsRequest, adminv1.GetTenantSettingsResponse]
	updateTenantSettings             *connect.Client[adminv1.UpdateTenantSettingsRequest, adminv1.UpdateTenantSettingsResponse]
	listIDEPresets                   *connect.Client[adminv1.ListIDEPresetsRequest, adminv1.ListIDEPresetsResponse]
	listAllowlistEntries             *connect.Client[adminv1.ListAllowlistEntriesRequest, adminv1.ListAllowlistEntriesResponse]
	addAllowlistEntry                *connect.Client[adminv1.AddAllowlistEntryRequest, adminv1.AddAllowlistEntryResponse]
	updateAllowlistEntry             *connect.Client[adminv1.UpdateAllowlistEntryRequest, adminv1.UpdateAllowlistEntryResponse]
	removeAllowlistEntry             *connect.Client[adminv1.RemoveAllowlistEntryRequest, adminv1.RemoveAllowlistEntryResponse]
	applyIDEPreset                   *connect.Client[adminv1.ApplyIDEPresetRequest, adminv1.ApplyIDEPresetResponse]
	removeIDEPreset                  *connect.Client[adminv1.RemoveIDEPresetRequest, adminv1.RemoveIDEPresetResponse]
	markIDEChoiceSkipped             *connect.Client[adminv1.MarkIDEChoiceSkippedRequest, adminv1.MarkIDEChoiceSkippedResponse]
	deleteTenant                     *connect.Client[adminv1.DeleteTenantRequest, adminv1.DeleteTenantResponse]
	listMembers                      *connect.Client[adminv1.ListMembersRequest, adminv1.ListMembersResponse]
	inviteMember                     *connect.Client[adminv1.InviteMemberRequest, adminv1.InviteMemberResponse]
	updateMemberRole                 *connect.Client[adminv1.UpdateMemberRoleRequest, adminv1.UpdateMemberRoleResponse]
	removeMember                     *connect.Client[adminv1.RemoveMemberRequest, adminv1.RemoveMemberResponse]
	createServiceAccount             *connect.Client[adminv1.CreateServiceAccountRequest, adminv1.CreateServiceAccountResponse]
	getServiceAccount                *connect.Client[adminv1.GetServiceAccountRequest, adminv1.GetServiceAccountResponse]
	updateServiceAccount             *connect.Client[adminv1.UpdateServiceAccountRequest, adminv1.UpdateServiceAccountResponse]
	listServiceAccounts              *connect.Client[adminv1.ListServiceAccountsRequest, adminv1.ListServiceAccountsResponse]
	deleteServiceAccount             *connect.Client[adminv1.DeleteServiceAccountRequest, adminv1.DeleteServiceAccountResponse]
	regenerateServiceAccountToken    *connect.Client[adminv1.RegenerateServiceAccountTokenRequest, adminv1.RegenerateServiceAccountTokenResponse]
	listServiceAccountUpstreamLinks  *connect.Client[adminv1.ListServiceAccountUpstreamLinksRequest, adminv1.ListServiceAccountUpstreamLinksResponse]
	setServiceAccountLinkEnabled     *connect.Client[adminv1.SetServiceAccountLinkEnabledRequest, adminv1.SetServiceAccountLinkEnabledResponse]
	startServiceAccountConnect       *connect.Client[adminv1.StartServiceAccountConnectRequest, adminv1.StartServiceAccountConnectResponse]
	submitServiceAccountAPIKey       *connect.Client[adminv1.SubmitServiceAccountAPIKeyRequest, adminv1.SubmitServiceAccountAPIKeyResponse]
	clearServiceAccountOverride      *connect.Client[adminv1.ClearServiceAccountOverrideRequest, adminv1.ClearServiceAccountOverrideResponse]
	disconnectServiceAccountUpstream *connect.Client[adminv1.DisconnectServiceAccountUpstreamRequest, adminv1.DisconnectServiceAccountUpstreamResponse]
}

// CreateUpstream calls limen.admin.v1.AdminService.CreateUpstream.
func (c *adminServiceClient) CreateUpstream(ctx context.Context, req *connect.Request[adminv1.CreateUpstreamRequest]) (*connect.Response[adminv1.CreateUpstreamResponse], error) {
	return c.createUpstream.CallUnary(ctx, req)
}

// UpdateUpstream calls limen.admin.v1.AdminService.UpdateUpstream.
func (c *adminServiceClient) UpdateUpstream(ctx context.Context, req *connect.Request[adminv1.UpdateUpstreamRequest]) (*connect.Response[adminv1.UpdateUpstreamResponse], error) {
	return c.updateUpstream.CallUnary(ctx, req)
}

// DeleteUpstream calls limen.admin.v1.AdminService.DeleteUpstream.
func (c *adminServiceClient) DeleteUpstream(ctx context.Context, req *connect.Request[adminv1.DeleteUpstreamRequest]) (*connect.Response[adminv1.DeleteUpstreamResponse], error) {
	return c.deleteUpstream.CallUnary(ctx, req)
}

// ReindexUpstreamCatalog calls limen.admin.v1.AdminService.ReindexUpstreamCatalog.
func (c *adminServiceClient) ReindexUpstreamCatalog(ctx context.Context, req *connect.Request[adminv1.ReindexUpstreamCatalogRequest]) (*connect.Response[adminv1.ReindexUpstreamCatalogResponse], error) {
	return c.reindexUpstreamCatalog.CallUnary(ctx, req)
}

// PreviewUpstreamContext calls limen.admin.v1.AdminService.PreviewUpstreamContext.
func (c *adminServiceClient) PreviewUpstreamContext(ctx context.Context, req *connect.Request[adminv1.PreviewUpstreamContextRequest]) (*connect.Response[adminv1.PreviewUpstreamContextResponse], error) {
	return c.previewUpstreamContext.CallUnary(ctx, req)
}

// GetTenantSettings calls limen.admin.v1.AdminService.GetTenantSettings.
func (c *adminServiceClient) GetTenantSettings(ctx context.Context, req *connect.Request[adminv1.GetTenantSettingsRequest]) (*connect.Response[adminv1.GetTenantSettingsResponse], error) {
	return c.getTenantSettings.CallUnary(ctx, req)
}

// UpdateTenantSettings calls limen.admin.v1.AdminService.UpdateTenantSettings.
func (c *adminServiceClient) UpdateTenantSettings(ctx context.Context, req *connect.Request[adminv1.UpdateTenantSettingsRequest]) (*connect.Response[adminv1.UpdateTenantSettingsResponse], error) {
	return c.updateTenantSettings.CallUnary(ctx, req)
}

// ListIDEPresets calls limen.admin.v1.AdminService.ListIDEPresets.
func (c *adminServiceClient) ListIDEPresets(ctx context.Context, req *connect.Request[adminv1.ListIDEPresetsRequest]) (*connect.Response[adminv1.ListIDEPresetsResponse], error) {
	return c.listIDEPresets.CallUnary(ctx, req)
}

// ListAllowlistEntries calls limen.admin.v1.AdminService.ListAllowlistEntries.
func (c *adminServiceClient) ListAllowlistEntries(ctx context.Context, req *connect.Request[adminv1.ListAllowlistEntriesRequest]) (*connect.Response[adminv1.ListAllowlistEntriesResponse], error) {
	return c.listAllowlistEntries.CallUnary(ctx, req)
}

// AddAllowlistEntry calls limen.admin.v1.AdminService.AddAllowlistEntry.
func (c *adminServiceClient) AddAllowlistEntry(ctx context.Context, req *connect.Request[adminv1.AddAllowlistEntryRequest]) (*connect.Response[adminv1.AddAllowlistEntryResponse], error) {
	return c.addAllowlistEntry.CallUnary(ctx, req)
}

// UpdateAllowlistEntry calls limen.admin.v1.AdminService.UpdateAllowlistEntry.
func (c *adminServiceClient) UpdateAllowlistEntry(ctx context.Context, req *connect.Request[adminv1.UpdateAllowlistEntryRequest]) (*connect.Response[adminv1.UpdateAllowlistEntryResponse], error) {
	return c.updateAllowlistEntry.CallUnary(ctx, req)
}

// RemoveAllowlistEntry calls limen.admin.v1.AdminService.RemoveAllowlistEntry.
func (c *adminServiceClient) RemoveAllowlistEntry(ctx context.Context, req *connect.Request[adminv1.RemoveAllowlistEntryRequest]) (*connect.Response[adminv1.RemoveAllowlistEntryResponse], error) {
	return c.removeAllowlistEntry.CallUnary(ctx, req)
}

// ApplyIDEPreset calls limen.admin.v1.AdminService.ApplyIDEPreset.
func (c *adminServiceClient) ApplyIDEPreset(ctx context.Context, req *connect.Request[adminv1.ApplyIDEPresetRequest]) (*connect.Response[adminv1.ApplyIDEPresetResponse], error) {
	return c.applyIDEPreset.CallUnary(ctx, req)
}

// RemoveIDEPreset calls limen.admin.v1.AdminService.RemoveIDEPreset.
func (c *adminServiceClient) RemoveIDEPreset(ctx context.Context, req *connect.Request[adminv1.RemoveIDEPresetRequest]) (*connect.Response[adminv1.RemoveIDEPresetResponse], error) {
	return c.removeIDEPreset.CallUnary(ctx, req)
}

// MarkIDEChoiceSkipped calls limen.admin.v1.AdminService.MarkIDEChoiceSkipped.
func (c *adminServiceClient) MarkIDEChoiceSkipped(ctx context.Context, req *connect.Request[adminv1.MarkIDEChoiceSkippedRequest]) (*connect.Response[adminv1.MarkIDEChoiceSkippedResponse], error) {
	return c.markIDEChoiceSkipped.CallUnary(ctx, req)
}

// DeleteTenant calls limen.admin.v1.AdminService.DeleteTenant.
func (c *adminServiceClient) DeleteTenant(ctx context.Context, req *connect.Request[adminv1.DeleteTenantRequest]) (*connect.Response[adminv1.DeleteTenantResponse], error) {
	return c.deleteTenant.CallUnary(ctx, req)
}

// ListMembers calls limen.admin.v1.AdminService.ListMembers.
func (c *adminServiceClient) ListMembers(ctx context.Context, req *connect.Request[adminv1.ListMembersRequest]) (*connect.Response[adminv1.ListMembersResponse], error) {
	return c.listMembers.CallUnary(ctx, req)
}

// InviteMember calls limen.admin.v1.AdminService.InviteMember.
func (c *adminServiceClient) InviteMember(ctx context.Context, req *connect.Request[adminv1.InviteMemberRequest]) (*connect.Response[adminv1.InviteMemberResponse], error) {
	return c.inviteMember.CallUnary(ctx, req)
}

// UpdateMemberRole calls limen.admin.v1.AdminService.UpdateMemberRole.
func (c *adminServiceClient) UpdateMemberRole(ctx context.Context, req *connect.Request[adminv1.UpdateMemberRoleRequest]) (*connect.Response[adminv1.UpdateMemberRoleResponse], error) {
	return c.updateMemberRole.CallUnary(ctx, req)
}

// RemoveMember calls limen.admin.v1.AdminService.RemoveMember.
func (c *adminServiceClient) RemoveMember(ctx context.Context, req *connect.Request[adminv1.RemoveMemberRequest]) (*connect.Response[adminv1.RemoveMemberResponse], error) {
	return c.removeMember.CallUnary(ctx, req)
}

// CreateServiceAccount calls limen.admin.v1.AdminService.CreateServiceAccount.
func (c *adminServiceClient) CreateServiceAccount(ctx context.Context, req *connect.Request[adminv1.CreateServiceAccountRequest]) (*connect.Response[adminv1.CreateServiceAccountResponse], error) {
	return c.createServiceAccount.CallUnary(ctx, req)
}

// GetServiceAccount calls limen.admin.v1.AdminService.GetServiceAccount.
func (c *adminServiceClient) GetServiceAccount(ctx context.Context, req *connect.Request[adminv1.GetServiceAccountRequest]) (*connect.Response[adminv1.GetServiceAccountResponse], error) {
	return c.getServiceAccount.CallUnary(ctx, req)
}

// UpdateServiceAccount calls limen.admin.v1.AdminService.UpdateServiceAccount.
func (c *adminServiceClient) UpdateServiceAccount(ctx context.Context, req *connect.Request[adminv1.UpdateServiceAccountRequest]) (*connect.Response[adminv1.UpdateServiceAccountResponse], error) {
	return c.updateServiceAccount.CallUnary(ctx, req)
}

// ListServiceAccounts calls limen.admin.v1.AdminService.ListServiceAccounts.
func (c *adminServiceClient) ListServiceAccounts(ctx context.Context, req *connect.Request[adminv1.ListServiceAccountsRequest]) (*connect.Response[adminv1.ListServiceAccountsResponse], error) {
	return c.listServiceAccounts.CallUnary(ctx, req)
}

// DeleteServiceAccount calls limen.admin.v1.AdminService.DeleteServiceAccount.
func (c *adminServiceClient) DeleteServiceAccount(ctx context.Context, req *connect.Request[adminv1.DeleteServiceAccountRequest]) (*connect.Response[adminv1.DeleteServiceAccountResponse], error) {
	return c.deleteServiceAccount.CallUnary(ctx, req)
}

// RegenerateServiceAccountToken calls limen.admin.v1.AdminService.RegenerateServiceAccountToken.
func (c *adminServiceClient) RegenerateServiceAccountToken(ctx context.Context, req *connect.Request[adminv1.RegenerateServiceAccountTokenRequest]) (*connect.Response[adminv1.RegenerateServiceAccountTokenResponse], error) {
	return c.regenerateServiceAccountToken.CallUnary(ctx, req)
}

// ListServiceAccountUpstreamLinks calls
// limen.admin.v1.AdminService.ListServiceAccountUpstreamLinks.
func (c *adminServiceClient) ListServiceAccountUpstreamLinks(ctx context.Context, req *connect.Request[adminv1.ListServiceAccountUpstreamLinksRequest]) (*connect.Response[adminv1.ListServiceAccountUpstreamLinksResponse], error) {
	return c.listServiceAccountUpstreamLinks.CallUnary(ctx, req)
}

// SetServiceAccountLinkEnabled calls limen.admin.v1.AdminService.SetServiceAccountLinkEnabled.
func (c *adminServiceClient) SetServiceAccountLinkEnabled(ctx context.Context, req *connect.Request[adminv1.SetServiceAccountLinkEnabledRequest]) (*connect.Response[adminv1.SetServiceAccountLinkEnabledResponse], error) {
	return c.setServiceAccountLinkEnabled.CallUnary(ctx, req)
}

// StartServiceAccountConnect calls limen.admin.v1.AdminService.StartServiceAccountConnect.
func (c *adminServiceClient) StartServiceAccountConnect(ctx context.Context, req *connect.Request[adminv1.StartServiceAccountConnectRequest]) (*connect.Response[adminv1.StartServiceAccountConnectResponse], error) {
	return c.startServiceAccountConnect.CallUnary(ctx, req)
}

// SubmitServiceAccountAPIKey calls limen.admin.v1.AdminService.SubmitServiceAccountAPIKey.
func (c *adminServiceClient) SubmitServiceAccountAPIKey(ctx context.Context, req *connect.Request[adminv1.SubmitServiceAccountAPIKeyRequest]) (*connect.Response[adminv1.SubmitServiceAccountAPIKeyResponse], error) {
	return c.submitServiceAccountAPIKey.CallUnary(ctx, req)
}

// ClearServiceAccountOverride calls limen.admin.v1.AdminService.ClearServiceAccountOverride.
func (c *adminServiceClient) ClearServiceAccountOverride(ctx context.Context, req *connect.Request[adminv1.ClearServiceAccountOverrideRequest]) (*connect.Response[adminv1.ClearServiceAccountOverrideResponse], error) {
	return c.clearServiceAccountOverride.CallUnary(ctx, req)
}

// DisconnectServiceAccountUpstream calls
// limen.admin.v1.AdminService.DisconnectServiceAccountUpstream.
func (c *adminServiceClient) DisconnectServiceAccountUpstream(ctx context.Context, req *connect.Request[adminv1.DisconnectServiceAccountUpstreamRequest]) (*connect.Response[adminv1.DisconnectServiceAccountUpstreamResponse], error) {
	return c.disconnectServiceAccountUpstream.CallUnary(ctx, req)
}

// AdminServiceHandler is an implementation of the limen.admin.v1.AdminService service.
type AdminServiceHandler interface {
	// Upstream catalog CRUD + tenant-wide tool-catalog ops. Admin floor.
	CreateUpstream(context.Context, *connect.Request[adminv1.CreateUpstreamRequest]) (*connect.Response[adminv1.CreateUpstreamResponse], error)
	UpdateUpstream(context.Context, *connect.Request[adminv1.UpdateUpstreamRequest]) (*connect.Response[adminv1.UpdateUpstreamResponse], error)
	DeleteUpstream(context.Context, *connect.Request[adminv1.DeleteUpstreamRequest]) (*connect.Response[adminv1.DeleteUpstreamResponse], error)
	ReindexUpstreamCatalog(context.Context, *connect.Request[adminv1.ReindexUpstreamCatalogRequest]) (*connect.Response[adminv1.ReindexUpstreamCatalogResponse], error)
	PreviewUpstreamContext(context.Context, *connect.Request[adminv1.PreviewUpstreamContextRequest]) (*connect.Response[adminv1.PreviewUpstreamContextResponse], error)
	// Tenant settings + dashboard step-completion toggles. Admin floor.
	GetTenantSettings(context.Context, *connect.Request[adminv1.GetTenantSettingsRequest]) (*connect.Response[adminv1.GetTenantSettingsResponse], error)
	UpdateTenantSettings(context.Context, *connect.Request[adminv1.UpdateTenantSettingsRequest]) (*connect.Response[adminv1.UpdateTenantSettingsResponse], error)
	// IDE presets + per-tenant redirect-URI allowlist. Admin floor.
	// See docs/phases/phase-09f-ide-presets-and-allowlist.md.
	ListIDEPresets(context.Context, *connect.Request[adminv1.ListIDEPresetsRequest]) (*connect.Response[adminv1.ListIDEPresetsResponse], error)
	ListAllowlistEntries(context.Context, *connect.Request[adminv1.ListAllowlistEntriesRequest]) (*connect.Response[adminv1.ListAllowlistEntriesResponse], error)
	AddAllowlistEntry(context.Context, *connect.Request[adminv1.AddAllowlistEntryRequest]) (*connect.Response[adminv1.AddAllowlistEntryResponse], error)
	UpdateAllowlistEntry(context.Context, *connect.Request[adminv1.UpdateAllowlistEntryRequest]) (*connect.Response[adminv1.UpdateAllowlistEntryResponse], error)
	RemoveAllowlistEntry(context.Context, *connect.Request[adminv1.RemoveAllowlistEntryRequest]) (*connect.Response[adminv1.RemoveAllowlistEntryResponse], error)
	ApplyIDEPreset(context.Context, *connect.Request[adminv1.ApplyIDEPresetRequest]) (*connect.Response[adminv1.ApplyIDEPresetResponse], error)
	RemoveIDEPreset(context.Context, *connect.Request[adminv1.RemoveIDEPresetRequest]) (*connect.Response[adminv1.RemoveIDEPresetResponse], error)
	MarkIDEChoiceSkipped(context.Context, *connect.Request[adminv1.MarkIDEChoiceSkippedRequest]) (*connect.Response[adminv1.MarkIDEChoiceSkippedResponse], error)
	// Owner-only. Limen-side soft-delete; Zitadel org cleanup is manual.
	DeleteTenant(context.Context, *connect.Request[adminv1.DeleteTenantRequest]) (*connect.Response[adminv1.DeleteTenantResponse], error)
	// Member management. Pass-through to Zitadel User V2 +
	// Authorization V2; Limen stores no mirror tables. See
	// docs/phases/phase-09c-tenant-admin-spa.md "Member management".
	// All four require admin (owner satisfies admin).
	ListMembers(context.Context, *connect.Request[adminv1.ListMembersRequest]) (*connect.Response[adminv1.ListMembersResponse], error)
	InviteMember(context.Context, *connect.Request[adminv1.InviteMemberRequest]) (*connect.Response[adminv1.InviteMemberResponse], error)
	UpdateMemberRole(context.Context, *connect.Request[adminv1.UpdateMemberRoleRequest]) (*connect.Response[adminv1.UpdateMemberRoleResponse], error)
	RemoveMember(context.Context, *connect.Request[adminv1.RemoveMemberRequest]) (*connect.Response[adminv1.RemoveMemberResponse], error)
	// Service account management. Admin floor.
	// Service accounts are Zitadel machine users mirrored locally. See
	// docs/phases/phase-09i-service-accounts.md.
	CreateServiceAccount(context.Context, *connect.Request[adminv1.CreateServiceAccountRequest]) (*connect.Response[adminv1.CreateServiceAccountResponse], error)
	GetServiceAccount(context.Context, *connect.Request[adminv1.GetServiceAccountRequest]) (*connect.Response[adminv1.GetServiceAccountResponse], error)
	UpdateServiceAccount(context.Context, *connect.Request[adminv1.UpdateServiceAccountRequest]) (*connect.Response[adminv1.UpdateServiceAccountResponse], error)
	ListServiceAccounts(context.Context, *connect.Request[adminv1.ListServiceAccountsRequest]) (*connect.Response[adminv1.ListServiceAccountsResponse], error)
	DeleteServiceAccount(context.Context, *connect.Request[adminv1.DeleteServiceAccountRequest]) (*connect.Response[adminv1.DeleteServiceAccountResponse], error)
	RegenerateServiceAccountToken(context.Context, *connect.Request[adminv1.RegenerateServiceAccountTokenRequest]) (*connect.Response[adminv1.RegenerateServiceAccountTokenResponse], error)
	// Service account upstream link management. Admin floor.
	ListServiceAccountUpstreamLinks(context.Context, *connect.Request[adminv1.ListServiceAccountUpstreamLinksRequest]) (*connect.Response[adminv1.ListServiceAccountUpstreamLinksResponse], error)
	SetServiceAccountLinkEnabled(context.Context, *connect.Request[adminv1.SetServiceAccountLinkEnabledRequest]) (*connect.Response[adminv1.SetServiceAccountLinkEnabledResponse], error)
	// Service account upstream linking — full lifecycle (OAuth, API key,
	// disconnect). Admin floor. See docs/phases/phase-09k-sa-upstream-linking.md.
	StartServiceAccountConnect(context.Context, *connect.Request[adminv1.StartServiceAccountConnectRequest]) (*connect.Response[adminv1.StartServiceAccountConnectResponse], error)
	SubmitServiceAccountAPIKey(context.Context, *connect.Request[adminv1.SubmitServiceAccountAPIKeyRequest]) (*connect.Response[adminv1.SubmitServiceAccountAPIKeyResponse], error)
	ClearServiceAccountOverride(context.Context, *connect.Request[adminv1.ClearServiceAccountOverrideRequest]) (*connect.Response[adminv1.ClearServiceAccountOverrideResponse], error)
	DisconnectServiceAccountUpstream(context.Context, *connect.Request[adminv1.DisconnectServiceAccountUpstreamRequest]) (*connect.Response[adminv1.DisconnectServiceAccountUpstreamResponse], error)
}

// NewAdminServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAdminServiceHandler(svc AdminServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	adminServiceMethods := adminv1.File_limen_admin_v1_admin_proto.Services().ByName("AdminService").Methods()
	adminServiceCreateUpstreamHandler := connect.NewUnaryHandler(
		AdminServiceCreateUpstreamProcedure,
		svc.CreateUpstream,
		connect.WithSchema(adminServiceMethods.ByName("CreateUpstream")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceUpdateUpstreamHandler := connect.NewUnaryHandler(
		AdminServiceUpdateUpstreamProcedure,
		svc.UpdateUpstream,
		connect.WithSchema(adminServiceMethods.ByName("UpdateUpstream")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceDeleteUpstreamHandler := connect.NewUnaryHandler(
		AdminServiceDeleteUpstreamProcedure,
		svc.DeleteUpstream,
		connect.WithSchema(adminServiceMethods.ByName("DeleteUpstream")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceReindexUpstreamCatalogHandler := connect.NewUnaryHandler(
		AdminServiceReindexUpstreamCatalogProcedure,
		svc.ReindexUpstreamCatalog,
		connect.WithSchema(adminServiceMethods.ByName("ReindexUpstreamCatalog")),
		connect.WithHandlerOptions(opts...),
	)
	adminServicePreviewUpstreamContextHandler := connect.NewUnaryHandler(
		AdminServicePreviewUpstreamContextProcedure,
		svc.PreviewUpstreamContext,
		connect.WithSchema(adminServiceMethods.ByName("PreviewUpstreamContext")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceGetTenantSettingsHandler := connect.NewUnaryHandler(
		AdminServiceGetTenantSettingsProcedure,
		svc.GetTenantSettings,
		connect.WithSchema(adminServiceMethods.ByName("GetTenantSettings")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceUpdateTenantSettingsHandler := connect.NewUnaryHandler(
		AdminServiceUpdateTenantSettingsProcedure,
		svc.UpdateTenantSettings,
		connect.WithSchema(adminServiceMethods.ByName("UpdateTenantSettings")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceListIDEPresetsHandler := connect.NewUnaryHandler(
		AdminServiceListIDEPresetsProcedure,
		svc.ListIDEPresets,
		connect.WithSchema(adminServiceMethods.ByName("ListIDEPresets")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceListAllowlistEntriesHandler := connect.NewUnaryHandler(
		AdminServiceListAllowlistEntriesProcedure,
		svc.ListAllowlistEntries,
		connect.WithSchema(adminServiceMethods.ByName("ListAllowlistEntries")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceAddAllowlistEntryHandler := connect.NewUnaryHandler(
		AdminServiceAddAllowlistEntryProcedure,
		svc.AddAllowlistEntry,
		connect.WithSchema(adminServiceMethods.ByName("AddAllowlistEntry")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceUpdateAllowlistEntryHandler := connect.NewUnaryHandler(
		AdminServiceUpdateAllowlistEntryProcedure,
		svc.UpdateAllowlistEntry,
		connect.WithSchema(adminServiceMethods.ByName("UpdateAllowlistEntry")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceRemoveAllowlistEntryHandler := connect.NewUnaryHandler(
		AdminServiceRemoveAllowlistEntryProcedure,
		svc.RemoveAllowlistEntry,
		connect.WithSchema(adminServiceMethods.ByName("RemoveAllowlistEntry")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceApplyIDEPresetHandler := connect.NewUnaryHandler(
		AdminServiceApplyIDEPresetProcedure,
		svc.ApplyIDEPreset,
		connect.WithSchema(adminServiceMethods.ByName("ApplyIDEPreset")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceRemoveIDEPresetHandler := connect.NewUnaryHandler(
		AdminServiceRemoveIDEPresetProcedure,
		svc.RemoveIDEPreset,
		connect.WithSchema(adminServiceMethods.ByName("RemoveIDEPreset")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceMarkIDEChoiceSkippedHandler := connect.NewUnaryHandler(
		AdminServiceMarkIDEChoiceSkippedProcedure,
		svc.MarkIDEChoiceSkipped,
		connect.WithSchema(adminServiceMethods.ByName("MarkIDEChoiceSkipped")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceDeleteTenantHandler := connect.NewUnaryHandler(
		AdminServiceDeleteTenantProcedure,
		svc.DeleteTenant,
		connect.WithSchema(adminServiceMethods.ByName("DeleteTenant")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceListMembersHandler := connect.NewUnaryHandler(
		AdminServiceListMembersProcedure,
		svc.ListMembers,
		connect.WithSchema(adminServiceMethods.ByName("ListMembers")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceInviteMemberHandler := connect.NewUnaryHandler(
		AdminServiceInviteMemberProcedure,
		svc.InviteMember,
		connect.WithSchema(adminServiceMethods.ByName("InviteMember")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceUpdateMemberRoleHandler := connect.NewUnaryHandler(
		AdminServiceUpdateMemberRoleProcedure,
		svc.UpdateMemberRole,
		connect.WithSchema(adminServiceMethods.ByName("UpdateMemberRole")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceRemoveMemberHandler := connect.NewUnaryHandler(
		AdminServiceRemoveMemberProcedure,
		svc.RemoveMember,
		connect.WithSchema(adminServiceMethods.ByName("RemoveMember")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceCreateServiceAccountHandler := connect.NewUnaryHandler(
		AdminServiceCreateServiceAccountProcedure,
		svc.CreateServiceAccount,
		connect.WithSchema(adminServiceMethods.ByName("CreateServiceAccount")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceGetServiceAccountHandler := connect.NewUnaryHandler(
		AdminServiceGetServiceAccountProcedure,
		svc.GetServiceAccount,
		connect.WithSchema(adminServiceMethods.ByName("GetServiceAccount")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceUpdateServiceAccountHandler := connect.NewUnaryHandler(
		AdminServiceUpdateServiceAccountProcedure,
		svc.UpdateServiceAccount,
		connect.WithSchema(adminServiceMethods.ByName("UpdateServiceAccount")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceListServiceAccountsHandler := connect.NewUnaryHandler(
		AdminServiceListServiceAccountsProcedure,
		svc.ListServiceAccounts,
		connect.WithSchema(adminServiceMethods.ByName("ListServiceAccounts")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceDeleteServiceAccountHandler := connect.NewUnaryHandler(
		AdminServiceDeleteServiceAccountProcedure,
		svc.DeleteServiceAccount,
		connect.WithSchema(adminServiceMethods.ByName("DeleteServiceAccount")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceRegenerateServiceAccountTokenHandler := connect.NewUnaryHandler(
		AdminServiceRegenerateServiceAccountTokenProcedure,
		svc.RegenerateServiceAccountToken,
		connect.WithSchema(adminServiceMethods.ByName("RegenerateServiceAccountToken")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceListServiceAccountUpstreamLinksHandler := connect.NewUnaryHandler(
		AdminServiceListServiceAccountUpstreamLinksProcedure,
		svc.ListServiceAccountUpstreamLinks,
		connect.WithSchema(adminServiceMethods.ByName("ListServiceAccountUpstreamLinks")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceSetServiceAccountLinkEnabledHandler := connect.NewUnaryHandler(
		AdminServiceSetServiceAccountLinkEnabledProcedure,
		svc.SetServiceAccountLinkEnabled,
		connect.WithSchema(adminServiceMethods.ByName("SetServiceAccountLinkEnabled")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceStartServiceAccountConnectHandler := connect.NewUnaryHandler(
		AdminServiceStartServiceAccountConnectProcedure,
		svc.StartServiceAccountConnect,
		connect.WithSchema(adminServiceMethods.ByName("StartServiceAccountConnect")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceSubmitServiceAccountAPIKeyHandler := connect.NewUnaryHandler(
		AdminServiceSubmitServiceAccountAPIKeyProcedure,
		svc.SubmitServiceAccountAPIKey,
		connect.WithSchema(adminServiceMethods.ByName("SubmitServiceAccountAPIKey")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceClearServiceAccountOverrideHandler := connect.NewUnaryHandler(
		AdminServiceClearServiceAccountOverrideProcedure,
		svc.ClearServiceAccountOverride,
		connect.WithSchema(adminServiceMethods.ByName("ClearServiceAccountOverride")),
		connect.WithHandlerOptions(opts...),
	)
	adminServiceDisconnectServiceAccountUpstreamHandler := connect.NewUnaryHandler(
		AdminServiceDisconnectServiceAccountUpstreamProcedure,
		svc.DisconnectServiceAccountUpstream,
		connect.WithSchema(adminServiceMethods.ByName("DisconnectServiceAccountUpstream")),
		connect.WithHandlerOptions(opts...),
	)
	return "/limen.admin.v1.AdminService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AdminServiceCreateUpstreamProcedure:
			adminServiceCreateUpstreamHandler.ServeHTTP(w, r)
		case AdminServiceUpdateUpstreamProcedure:
			adminServiceUpdateUpstreamHandler.ServeHTTP(w, r)
		case AdminServiceDeleteUpstreamProcedure:
			adminServiceDeleteUpstreamHandler.ServeHTTP(w, r)
		case AdminServiceReindexUpstreamCatalogProcedure:
			adminServiceReindexUpstreamCatalogHandler.ServeHTTP(w, r)
		case AdminServicePreviewUpstreamContextProcedure:
			adminServicePreviewUpstreamContextHandler.ServeHTTP(w, r)
		case AdminServiceGetTenantSettingsProcedure:
			adminServiceGetTenantSettingsHandler.ServeHTTP(w, r)
		case AdminServiceUpdateTenantSettingsProcedure:
			adminServiceUpdateTenantSettingsHandler.ServeHTTP(w, r)
		case AdminServiceListIDEPresetsProcedure:
			adminServiceListIDEPresetsHandler.ServeHTTP(w, r)
		case AdminServiceListAllowlistEntriesProcedure:
			adminServiceListAllowlistEntriesHandler.ServeHTTP(w, r)
		case AdminServiceAddAllowlistEntryProcedure:
			adminServiceAddAllowlistEntryHandler.ServeHTTP(w, r)
		case AdminServiceUpdateAllowlistEntryProcedure:
			adminServiceUpdateAllowlistEntryHandler.ServeHTTP(w, r)
		case AdminServiceRemoveAllowlistEntryProcedure:
			adminServiceRemoveAllowlistEntryHandler.ServeHTTP(w, r)
		case AdminServiceApplyIDEPresetProcedure:
			adminServiceApplyIDEPresetHandler.ServeHTTP(w, r)
		case AdminServiceRemoveIDEPresetProcedure:
			adminServiceRemoveIDEPresetHandler.ServeHTTP(w, r)
		case AdminServiceMarkIDEChoiceSkippedProcedure:
			adminServiceMarkIDEChoiceSkippedHandler.ServeHTTP(w, r)
		case AdminServiceDeleteTenantProcedure:
			adminServiceDeleteTenantHandler.ServeHTTP(w, r)
		case AdminServiceListMembersProcedure:
			adminServiceListMembersHandler.ServeHTTP(w, r)
		case AdminServiceInviteMemberProcedure:
			adminServiceInviteMemberHandler.ServeHTTP(w, r)
		case AdminServiceUpdateMemberRoleProcedure:
			adminServiceUpdateMemberRoleHandler.ServeHTTP(w, r)
		case AdminServiceRemoveMemberProcedure:
			adminServiceRemoveMemberHandler.ServeHTTP(w, r)
		case AdminServiceCreateServiceAccountProcedure:
			adminServiceCreateServiceAccountHandler.ServeHTTP(w, r)
		case AdminServiceGetServiceAccountProcedure:
			adminServiceGetServiceAccountHandler.ServeHTTP(w, r)
		case AdminServiceUpdateServiceAccountProcedure:
			adminServiceUpdateServiceAccountHandler.ServeHTTP(w, r)
		case AdminServiceListServiceAccountsProcedure:
			adminServiceListServiceAccountsHandler.ServeHTTP(w, r)
		case AdminServiceDeleteServiceAccountProcedure:
			adminServiceDeleteServiceAccountHandler.ServeHTTP(w, r)
		case AdminServiceRegenerateServiceAccountTokenProcedure:
			adminServiceRegenerateServiceAccountTokenHandler.ServeHTTP(w, r)
		case AdminServiceListServiceAccountUpstreamLinksProcedure:
			adminServiceListServiceAccountUpstreamLinksHandler.ServeHTTP(w, r)
		case AdminServiceSetServiceAccountLinkEnabledProcedure:
			adminServiceSetServiceAccountLinkEnabledHandler.ServeHTTP(w, r)
		case AdminServiceStartServiceAccountConnectProcedure:
			adminServiceStartServiceAccountConnectHandler.ServeHTTP(w, r)
		case AdminServiceSubmitServiceAccountAPIKeyProcedure:
			adminServiceSubmitServiceAccountAPIKeyHandler.ServeHTTP(w, r)
		case AdminServiceClearServiceAccountOverrideProcedure:
			adminServiceClearServiceAccountOverrideHandler.ServeHTTP(w, r)
		case AdminServiceDisconnectServiceAccountUpstreamProcedure:
			adminServiceDisconnectServiceAccountUpstreamHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAdminServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAdminServiceHandler struct{}

func (UnimplementedAdminServiceHandler) CreateUpstream(context.Context, *connect.Request[adminv1.CreateUpstreamRequest]) (*connect.Response[adminv1.CreateUpstreamResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("limen.admin.v1.AdminService.CreateUpstream is not implemented"))
}

func (UnimplementedAdminServiceHandler) UpdateUpstream(context.Context, *connect.Request[adminv1.UpdateUpstreamRequest]) (*connect.Response[adminv1.UpdateUpstreamResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("limen.admin.v1.AdminService.UpdateUpstream is not implemented"))
}

func (UnimplementedAdminServiceHandler) DeleteUpstream(context.Context, *connect.Request[adminv1.DeleteUpstreamRequest]) (*connect.Response[adminv1.DeleteUpstreamResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("limen.admin.v1.AdminService.DeleteUpstream is not implemented"))
}

func (UnimplementedAdminServiceHandler) ReindexUpstreamCatalog(context.Context, *connect.Request[adminv1.ReindexUpstreamCatalogRequest]) (*connect.Response[adminv1.ReindexUpstreamCatalogResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("limen.admin.v1.AdminService.ReindexUpstreamCatalog is not implemented"))
}

func (UnimplementedAdminServiceHandler) PreviewUpstreamContext(context.Context, *connect.Request[adminv1.PreviewUpstreamContextRequest]) (*connect.Response[adminv1.PreviewUpstreamContextResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("limen.admin.v1.AdminService.PreviewUpstreamContext is not implemented"))
}

func (UnimplementedAdminServiceHandler) GetTenantSettings(context.Context, *connect.Request[adminv1.GetTenantSettingsRequest]) (*connect.Response[adminv1.GetTenantSettingsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("limen.admin.v1.AdminService.GetTenantSettings is not implemented"))
}

func (UnimplementedAdminServiceHandler) UpdateTenantSettings(context.Context, *connect.Request[adminv1.UpdateTenantSettingsRequest]) (*connect.Response[adminv1.UpdateTenantSettingsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("limen.admin.v1.AdminService.UpdateTenantSettings is not implemented"))
}

func (UnimplementedAdminServiceHandler) ListIDEPresets(context.Context, *connect.Request[adminv1.ListIDEPresetsRequest]) (*connect.Response[adminv1.ListIDEPresetsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("limen.admin.v1.AdminService.ListIDEPresets is not implemented"))
}

func (UnimplementedAdminServiceHandler) ListAllowlistEntries(context.Context, *connect.Request[adminv1.ListAllowlistEntriesRequest]) (*connect.Response[adminv1.ListAllowlistEntriesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("limen.admin.v1.AdminService.ListAllowlistEntries is not implemented"))
}

func (UnimplementedAdminServiceHandler) AddAllowlistEntry(context.Context, *connect.Request[adminv1.AddAllowlistEntryRequest]) (*connect.Response[adminv1.AddAllowlistEntryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("limen.admin.v1.AdminService.AddAllowlistEntry is not implemented"))
}

func (UnimplementedAdminServiceHandler) UpdateAllowlistEntry(context.Context, *connect.Request[adminv1.UpdateAllowlistEntryRequest]) (*connect.Response[adminv1.UpdateAllowlistEntryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("limen.admin.v1.AdminService.UpdateAllowlistEntry is not implemented"))
}

func (UnimplementedAdminServiceHandler) RemoveAllowlistEntry(context.Context, *connect.Request[adminv1.RemoveAllowlistEntryRequest]) (*connect.Response[adminv1.RemoveAllowlistEntryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("limen.admin.v1.AdminService.RemoveAllowlistEntry is not implemented"))
}

func (UnimplementedAdminServiceHandler) ApplyIDEPreset(context.Context, *connect.Request[adminv1.ApplyIDEPresetRequest]) (*connect.Response[adminv1.ApplyIDEPresetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("limen.admin.v1.AdminService.ApplyIDEPreset is not implemented"))
}

func (UnimplementedAdminServiceHandler) RemoveIDEPreset(context.Context, *connect.Request[adminv1.RemoveIDEPresetRequest]) (*connect.Response[adminv1.RemoveIDEPresetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("limen.admin.v1.AdminService.RemoveIDEPreset is not implemented"))
}

func (UnimplementedAdminServiceHandler) MarkIDEChoiceSkipped(context.Context, *connect.Request[adminv1.MarkIDEChoiceSkippedRequest]) (*connect.Response[adminv1.MarkIDEChoiceSkippedResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("limen.admin.v1.AdminService.MarkIDEChoiceSkipped is not implemented"))
}

func (UnimplementedAdminServiceHandler) DeleteTenant(context.Context, *connect.Request[adminv1.DeleteTenantRequest]) (*connect.Response[adminv1.DeleteTenantResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("limen.admin.v1.AdminService.DeleteTenant is not implemented"))
}

func (UnimplementedAdminServiceHandler) ListMembers(context.Context, *connect.Request[adminv1.ListMembersRequest]) (*connect.Response[adminv1.ListMembersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("limen.admin.v1.AdminService.ListMembers is not implemented"))
}

func (UnimplementedAdminServiceHandler) InviteMember(context.Context, *connect.Request[adminv1.InviteMemberRequest]) (*connect.Response[adminv1.InviteMemberResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("limen.admin.v1.AdminService.InviteMember is not implemented"))
}

func (UnimplementedAdminServiceHandler) UpdateMemberRole(context.Context, *connect.Request[adminv1.UpdateMemberRoleRequest]) (*connect.Response[adminv1.UpdateMemberRoleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("limen.admin.v1.AdminService.UpdateMemberRole is not implemented"))
}

func (UnimplementedAdminServiceHandler) RemoveMember(context.Context, *connect.Request[adminv1.RemoveMemberRequest]) (*connect.Response[adminv1.RemoveMemberResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("limen.admin.v1.AdminService.RemoveMember is not implemented"))
}

func (UnimplementedAdminServiceHandler) CreateServiceAccount(context.Context, *connect.Request[adminv1.CreateServiceAccountRequest]) (*connect.Response[adminv1.CreateServiceAccountResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("limen.admin.v1.AdminService.CreateServiceAccount is not implemented"))
}

func (UnimplementedAdminServiceHandler) GetServiceAccount(context.Context, *connect.Request[adminv1.GetServiceAccountRequest]) (*connect.Response[adminv1.GetServiceAccountResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("limen.admin.v1.AdminService.GetServiceAccount is not implemented"))
}

func (UnimplementedAdminServiceHandler) UpdateServiceAccount(context.Context, *connect.Request[adminv1.UpdateServiceAccountRequest]) (*connect.Response[adminv1.UpdateServiceAccountResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("limen.admin.v1.AdminService.UpdateServiceAccount is not implemented"))
}

func (UnimplementedAdminServiceHandler) ListServiceAccounts(context.Context, *connect.Request[adminv1.ListServiceAccountsRequest]) (*connect.Response[adminv1.ListServiceAccountsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("limen.admin.v1.AdminService.ListServiceAccounts is not implemented"))
}

func (UnimplementedAdminServiceHandler) DeleteServiceAccount(context.Context, *connect.Request[adminv1.DeleteServiceAccountRequest]) (*connect.Response[adminv1.DeleteServiceAccountResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("limen.admin.v1.AdminService.DeleteServiceAccount is not implemented"))
}

func (UnimplementedAdminServiceHandler) RegenerateServiceAccountToken(context.Context, *connect.Request[adminv1.RegenerateServiceAccountTokenRequest]) (*connect.Response[adminv1.RegenerateServiceAccountTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("limen.admin.v1.AdminService.RegenerateServiceAccountToken is not implemented"))
}

func (UnimplementedAdminServiceHandler) ListServiceAccountUpstreamLinks(context.Context, *connect.Request[adminv1.ListServiceAccountUpstreamLinksRequest]) (*connect.Response[adminv1.ListServiceAccountUpstreamLinksResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("limen.admin.v1.AdminService.ListServiceAccountUpstreamLinks is not implemented"))
}

func (UnimplementedAdminServiceHandler) SetServiceAccountLinkEnabled(context.Context, *connect.Request[adminv1.SetServiceAccountLinkEnabledRequest]) (*connect.Response[adminv1.SetServiceAccountLinkEnabledResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("limen.admin.v1.AdminService.SetServiceAccountLinkEnabled is not implemented"))
}

func (UnimplementedAdminServiceHandler) StartServiceAccountConnect(context.Context, *connect.Request[adminv1.StartServiceAccountConnectRequest]) (*connect.Response[adminv1.StartServiceAccountConnectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("limen.admin.v1.AdminService.StartServiceAccountConnect is not implemented"))
}

func (UnimplementedAdminServiceHandler) SubmitServiceAccountAPIKey(context.Context, *connect.Request[adminv1.SubmitServiceAccountAPIKeyRequest]) (*connect.Response[adminv1.SubmitServiceAccountAPIKeyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("limen.admin.v1.AdminService.SubmitServiceAccountAPIKey is not implemented"))
}

func (UnimplementedAdminServiceHandler) ClearServiceAccountOverride(context.Context, *connect.Request[adminv1.ClearServiceAccountOverrideRequest]) (*connect.Response[adminv1.ClearServiceAccountOverrideResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("limen.admin.v1.AdminService.ClearServiceAccountOverride is not implemented"))
}

func (UnimplementedAdminServiceHandler) DisconnectServiceAccountUpstream(context.Context, *connect.Request[adminv1.DisconnectServiceAccountUpstreamRequest]) (*connect.Response[adminv1.DisconnectServiceAccountUpstreamResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("limen.admin.v1.AdminService.DisconnectServiceAccountUpstream is not implemented"))
}
