// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: limen/signup/v1/signup.proto

package signupv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	signupv1 "github.com/belphemur/limen/internal/signup/signupv1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SignupServiceName is the fully-qualified name of the SignupService service.
	SignupServiceName = "limen.signup.v1.SignupService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SignupServiceStartSignupProcedure is the fully-qualified name of the SignupService's StartSignup
	// RPC.
	SignupServiceStartSignupProcedure = "/limen.signup.v1.SignupService/StartSignup"
	// SignupServiceVerifyEmailProcedure is the fully-qualified name of the SignupService's VerifyEmail
	// RPC.
	SignupServiceVerifyEmailProcedure = "/limen.signup.v1.SignupService/VerifyEmail"
	// SignupServiceCompleteSignupProcedure is the fully-qualified name of the SignupService's
	// CompleteSignup RPC.
	SignupServiceCompleteSignupProcedure = "/limen.signup.v1.SignupService/CompleteSignup"
)

// SignupServiceClient is a client for the limen.signup.v1.SignupService service.
type SignupServiceClient interface {
	StartSignup(context.Context, *connect.Request[signupv1.StartSignupRequest]) (*connect.Response[signupv1.StartSignupResponse], error)
	VerifyEmail(context.Context, *connect.Request[signupv1.VerifyEmailRequest]) (*connect.Response[signupv1.VerifyEmailResponse], error)
	CompleteSignup(context.Context, *connect.Request[signupv1.CompleteSignupRequest]) (*connect.Response[signupv1.CompleteSignupResponse], error)
}

// NewSignupServiceClient constructs a client for the limen.signup.v1.SignupService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSignupServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SignupServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	signupServiceMethods := signupv1.File_limen_signup_v1_signup_proto.Services().ByName("SignupService").Methods()
	return &signupServiceClient{
		startSignup: connect.NewClient[signupv1.StartSignupRequest, signupv1.StartSignupResponse](
			httpClient,
			baseURL+SignupServiceStartSignupProcedure,
			connect.WithSchema(signupServiceMethods.ByName("StartSignup")),
			connect.WithClientOptions(opts...),
		),
		verifyEmail: connect.NewClient[signupv1.VerifyEmailRequest, signupv1.VerifyEmailResponse](
			httpClient,
			baseURL+SignupServiceVerifyEmailProcedure,
			connect.WithSchema(signupServiceMethods.ByName("VerifyEmail")),
			connect.WithClientOptions(opts...),
		),
		completeSignup: connect.NewClient[signupv1.CompleteSignupRequest, signupv1.CompleteSignupResponse](
			httpClient,
			baseURL+SignupServiceCompleteSignupProcedure,
			connect.WithSchema(signupServiceMethods.ByName("CompleteSignup")),
			connect.WithClientOptions(opts...),
		),
	}
}

// signupServiceClient implements SignupServiceClient.
type signupServiceClient struct {
	startSignup    *connect.Client[signupv1.StartSignupRequest, signupv1.StartSignupResponse]
	verifyEmail    *connect.Client[signupv1.VerifyEmailRequest, signupv1.VerifyEmailResponse]
	completeSignup *connect.Client[signupv1.CompleteSignupRequest, signupv1.CompleteSignupResponse]
}

// StartSignup calls limen.signup.v1.SignupService.StartSignup.
func (c *signupServiceClient) StartSignup(ctx context.Context, req *connect.Request[signupv1.StartSignupRequest]) (*connect.Response[signupv1.StartSignupResponse], error) {
	return c.startSignup.CallUnary(ctx, req)
}

// VerifyEmail calls limen.signup.v1.SignupService.VerifyEmail.
func (c *signupServiceClient) VerifyEmail(ctx context.Context, req *connect.Request[signupv1.VerifyEmailRequest]) (*connect.Response[signupv1.VerifyEmailResponse], error) {
	return c.verifyEmail.CallUnary(ctx, req)
}

// CompleteSignup calls limen.signup.v1.SignupService.CompleteSignup.
func (c *signupServiceClient) CompleteSignup(ctx context.Context, req *connect.Request[signupv1.CompleteSignupRequest]) (*connect.Response[signupv1.CompleteSignupResponse], error) {
	return c.completeSignup.CallUnary(ctx, req)
}

// SignupServiceHandler is an implementation of the limen.signup.v1.SignupService service.
type SignupServiceHandler interface {
	StartSignup(context.Context, *connect.Request[signupv1.StartSignupRequest]) (*connect.Response[signupv1.StartSignupResponse], error)
	VerifyEmail(context.Context, *connect.Request[signupv1.VerifyEmailRequest]) (*connect.Response[signupv1.VerifyEmailResponse], error)
	CompleteSignup(context.Context, *connect.Request[signupv1.CompleteSignupRequest]) (*connect.Response[signupv1.CompleteSignupResponse], error)
}

// NewSignupServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSignupServiceHandler(svc SignupServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	signupServiceMethods := signupv1.File_limen_signup_v1_signup_proto.Services().ByName("SignupService").Methods()
	signupServiceStartSignupHandler := connect.NewUnaryHandler(
		SignupServiceStartSignupProcedure,
		svc.StartSignup,
		connect.WithSchema(signupServiceMethods.ByName("StartSignup")),
		connect.WithHandlerOptions(opts...),
	)
	signupServiceVerifyEmailHandler := connect.NewUnaryHandler(
		SignupServiceVerifyEmailProcedure,
		svc.VerifyEmail,
		connect.WithSchema(signupServiceMethods.ByName("VerifyEmail")),
		connect.WithHandlerOptions(opts...),
	)
	signupServiceCompleteSignupHandler := connect.NewUnaryHandler(
		SignupServiceCompleteSignupProcedure,
		svc.CompleteSignup,
		connect.WithSchema(signupServiceMethods.ByName("CompleteSignup")),
		connect.WithHandlerOptions(opts...),
	)
	return "/limen.signup.v1.SignupService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SignupServiceStartSignupProcedure:
			signupServiceStartSignupHandler.ServeHTTP(w, r)
		case SignupServiceVerifyEmailProcedure:
			signupServiceVerifyEmailHandler.ServeHTTP(w, r)
		case SignupServiceCompleteSignupProcedure:
			signupServiceCompleteSignupHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSignupServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSignupServiceHandler struct{}

func (UnimplementedSignupServiceHandler) StartSignup(context.Context, *connect.Request[signupv1.StartSignupRequest]) (*connect.Response[signupv1.StartSignupResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("limen.signup.v1.SignupService.StartSignup is not implemented"))
}

func (UnimplementedSignupServiceHandler) VerifyEmail(context.Context, *connect.Request[signupv1.VerifyEmailRequest]) (*connect.Response[signupv1.VerifyEmailResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("limen.signup.v1.SignupService.VerifyEmail is not implemented"))
}

func (UnimplementedSignupServiceHandler) CompleteSignup(context.Context, *connect.Request[signupv1.CompleteSignupRequest]) (*connect.Response[signupv1.CompleteSignupResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("limen.signup.v1.SignupService.CompleteSignup is not implemented"))
}
