// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: limen/session/v1/session.proto

package sessionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Role int32

const (
	Role_ROLE_UNSPECIFIED Role = 0
	Role_ROLE_MEMBER      Role = 1
	Role_ROLE_ADMIN       Role = 2
	Role_ROLE_OWNER       Role = 3
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ROLE_UNSPECIFIED",
		1: "ROLE_MEMBER",
		2: "ROLE_ADMIN",
		3: "ROLE_OWNER",
	}
	Role_value = map[string]int32{
		"ROLE_UNSPECIFIED": 0,
		"ROLE_MEMBER":      1,
		"ROLE_ADMIN":       2,
		"ROLE_OWNER":       3,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_limen_session_v1_session_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_limen_session_v1_session_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_limen_session_v1_session_proto_rawDescGZIP(), []int{0}
}

type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_limen_session_v1_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_limen_session_v1_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_limen_session_v1_session_proto_rawDescGZIP(), []int{0}
}

// ImpersonationInfo is present in GetSessionResponse when the caller is
// operating under an impersonation session (CookiePayloadV2).
type ImpersonationInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IsImpersonating bool                   `protobuf:"varint,1,opt,name=is_impersonating,json=isImpersonating,proto3" json:"is_impersonating,omitempty"`
	// Zitadel subject of the admin who initiated impersonation.
	ActorUserId    string `protobuf:"bytes,2,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	ActorEmail     string `protobuf:"bytes,3,opt,name=actor_email,json=actorEmail,proto3" json:"actor_email,omitempty"`
	ActorFirstName string `protobuf:"bytes,4,opt,name=actor_first_name,json=actorFirstName,proto3" json:"actor_first_name,omitempty"`
	ActorLastName  string `protobuf:"bytes,5,opt,name=actor_last_name,json=actorLastName,proto3" json:"actor_last_name,omitempty"`
	// Reason provided at impersonation start (may be empty for v1).
	Reason string `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	// "service_account" or "user" — what type of entity is being impersonated.
	TargetUserType string `protobuf:"bytes,7,opt,name=target_user_type,json=targetUserType,proto3" json:"target_user_type,omitempty"`
	// RFC3339 timestamp when the impersonation session expires.
	ExpiresAt     string `protobuf:"bytes,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImpersonationInfo) Reset() {
	*x = ImpersonationInfo{}
	mi := &file_limen_session_v1_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImpersonationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImpersonationInfo) ProtoMessage() {}

func (x *ImpersonationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_limen_session_v1_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImpersonationInfo.ProtoReflect.Descriptor instead.
func (*ImpersonationInfo) Descriptor() ([]byte, []int) {
	return file_limen_session_v1_session_proto_rawDescGZIP(), []int{1}
}

func (x *ImpersonationInfo) GetIsImpersonating() bool {
	if x != nil {
		return x.IsImpersonating
	}
	return false
}

func (x *ImpersonationInfo) GetActorUserId() string {
	if x != nil {
		return x.ActorUserId
	}
	return ""
}

func (x *ImpersonationInfo) GetActorEmail() string {
	if x != nil {
		return x.ActorEmail
	}
	return ""
}

func (x *ImpersonationInfo) GetActorFirstName() string {
	if x != nil {
		return x.ActorFirstName
	}
	return ""
}

func (x *ImpersonationInfo) GetActorLastName() string {
	if x != nil {
		return x.ActorLastName
	}
	return ""
}

func (x *ImpersonationInfo) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ImpersonationInfo) GetTargetUserType() string {
	if x != nil {
		return x.TargetUserType
	}
	return ""
}

func (x *ImpersonationInfo) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

type GetSessionResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Tenant *Tenant                `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	User   *User                  `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Role   Role                   `protobuf:"varint,3,opt,name=role,proto3,enum=limen.session.v1.Role" json:"role,omitempty"`
	// Present only when the session was resolved from an impersonation cookie.
	Impersonation *ImpersonationInfo `protobuf:"bytes,4,opt,name=impersonation,proto3" json:"impersonation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionResponse) Reset() {
	*x = GetSessionResponse{}
	mi := &file_limen_session_v1_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionResponse) ProtoMessage() {}

func (x *GetSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_limen_session_v1_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionResponse.ProtoReflect.Descriptor instead.
func (*GetSessionResponse) Descriptor() ([]byte, []int) {
	return file_limen_session_v1_session_proto_rawDescGZIP(), []int{2}
}

func (x *GetSessionResponse) GetTenant() *Tenant {
	if x != nil {
		return x.Tenant
	}
	return nil
}

func (x *GetSessionResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *GetSessionResponse) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNSPECIFIED
}

func (x *GetSessionResponse) GetImpersonation() *ImpersonationInfo {
	if x != nil {
		return x.Impersonation
	}
	return nil
}

type Tenant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicId      string                 `protobuf:"bytes,1,opt,name=public_id,json=publicId,proto3" json:"public_id,omitempty"` // "tnt_<ULID>"
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tenant) Reset() {
	*x = Tenant{}
	mi := &file_limen_session_v1_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tenant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tenant) ProtoMessage() {}

func (x *Tenant) ProtoReflect() protoreflect.Message {
	mi := &file_limen_session_v1_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tenant.ProtoReflect.Descriptor instead.
func (*Tenant) Descriptor() ([]byte, []int) {
	return file_limen_session_v1_session_proto_rawDescGZIP(), []int{3}
}

func (x *Tenant) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

func (x *Tenant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Zitadel subject
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_limen_session_v1_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_limen_session_v1_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_limen_session_v1_session_proto_rawDescGZIP(), []int{4}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

var File_limen_session_v1_session_proto protoreflect.FileDescriptor

const file_limen_session_v1_session_proto_rawDesc = "" +
	"\n" +
	"\x1elimen/session/v1/session.proto\x12\x10limen.session.v1\"\x13\n" +
	"\x11GetSessionRequest\"\xb6\x02\n" +
	"\x11ImpersonationInfo\x12)\n" +
	"\x10is_impersonating\x18\x01 \x01(\bR\x0fisImpersonating\x12\"\n" +
	"\ractor_user_id\x18\x02 \x01(\tR\vactorUserId\x12\x1f\n" +
	"\vactor_email\x18\x03 \x01(\tR\n" +
	"actorEmail\x12(\n" +
	"\x10actor_first_name\x18\x04 \x01(\tR\x0eactorFirstName\x12&\n" +
	"\x0factor_last_name\x18\x05 \x01(\tR\ractorLastName\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\x12(\n" +
	"\x10target_user_type\x18\a \x01(\tR\x0etargetUserType\x12\x1d\n" +
	"\n" +
	"expires_at\x18\b \x01(\tR\texpiresAt\"\xe9\x01\n" +
	"\x12GetSessionResponse\x120\n" +
	"\x06tenant\x18\x01 \x01(\v2\x18.limen.session.v1.TenantR\x06tenant\x12*\n" +
	"\x04user\x18\x02 \x01(\v2\x16.limen.session.v1.UserR\x04user\x12*\n" +
	"\x04role\x18\x03 \x01(\x0e2\x16.limen.session.v1.RoleR\x04role\x12I\n" +
	"\rimpersonation\x18\x04 \x01(\v2#.limen.session.v1.ImpersonationInfoR\rimpersonation\"9\n" +
	"\x06Tenant\x12\x1b\n" +
	"\tpublic_id\x18\x01 \x01(\tR\bpublicId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"h\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName*M\n" +
	"\x04Role\x12\x14\n" +
	"\x10ROLE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vROLE_MEMBER\x10\x01\x12\x0e\n" +
	"\n" +
	"ROLE_ADMIN\x10\x02\x12\x0e\n" +
	"\n" +
	"ROLE_OWNER\x10\x032i\n" +
	"\x0eSessionService\x12W\n" +
	"\n" +
	"GetSession\x12#.limen.session.v1.GetSessionRequest\x1a$.limen.session.v1.GetSessionResponseBAZ?github.com/belphemur/limen/internal/session/sessionv1;sessionv1b\x06proto3"

var (
	file_limen_session_v1_session_proto_rawDescOnce sync.Once
	file_limen_session_v1_session_proto_rawDescData []byte
)

func file_limen_session_v1_session_proto_rawDescGZIP() []byte {
	file_limen_session_v1_session_proto_rawDescOnce.Do(func() {
		file_limen_session_v1_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_limen_session_v1_session_proto_rawDesc), len(file_limen_session_v1_session_proto_rawDesc)))
	})
	return file_limen_session_v1_session_proto_rawDescData
}

var file_limen_session_v1_session_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_limen_session_v1_session_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_limen_session_v1_session_proto_goTypes = []any{
	(Role)(0),                  // 0: limen.session.v1.Role
	(*GetSessionRequest)(nil),  // 1: limen.session.v1.GetSessionRequest
	(*ImpersonationInfo)(nil),  // 2: limen.session.v1.ImpersonationInfo
	(*GetSessionResponse)(nil), // 3: limen.session.v1.GetSessionResponse
	(*Tenant)(nil),             // 4: limen.session.v1.Tenant
	(*User)(nil),               // 5: limen.session.v1.User
}
var file_limen_session_v1_session_proto_depIdxs = []int32{
	4, // 0: limen.session.v1.GetSessionResponse.tenant:type_name -> limen.session.v1.Tenant
	5, // 1: limen.session.v1.GetSessionResponse.user:type_name -> limen.session.v1.User
	0, // 2: limen.session.v1.GetSessionResponse.role:type_name -> limen.session.v1.Role
	2, // 3: limen.session.v1.GetSessionResponse.impersonation:type_name -> limen.session.v1.ImpersonationInfo
	1, // 4: limen.session.v1.SessionService.GetSession:input_type -> limen.session.v1.GetSessionRequest
	3, // 5: limen.session.v1.SessionService.GetSession:output_type -> limen.session.v1.GetSessionResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_limen_session_v1_session_proto_init() }
func file_limen_session_v1_session_proto_init() {
	if File_limen_session_v1_session_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_limen_session_v1_session_proto_rawDesc), len(file_limen_session_v1_session_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_limen_session_v1_session_proto_goTypes,
		DependencyIndexes: file_limen_session_v1_session_proto_depIdxs,
		EnumInfos:         file_limen_session_v1_session_proto_enumTypes,
		MessageInfos:      file_limen_session_v1_session_proto_msgTypes,
	}.Build()
	File_limen_session_v1_session_proto = out.File
	file_limen_session_v1_session_proto_goTypes = nil
	file_limen_session_v1_session_proto_depIdxs = nil
}
