// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: limen/portal/v1/portal.proto

package portalv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	portalv1 "github.com/belphemur/limen/internal/portal/portalv1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PortalServiceName is the fully-qualified name of the PortalService service.
	PortalServiceName = "limen.portal.v1.PortalService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PortalServiceListUpstreamsProcedure is the fully-qualified name of the PortalService's
	// ListUpstreams RPC.
	PortalServiceListUpstreamsProcedure = "/limen.portal.v1.PortalService/ListUpstreams"
	// PortalServiceStartConnectProcedure is the fully-qualified name of the PortalService's
	// StartConnect RPC.
	PortalServiceStartConnectProcedure = "/limen.portal.v1.PortalService/StartConnect"
	// PortalServiceSubmitUpstreamAPIKeyProcedure is the fully-qualified name of the PortalService's
	// SubmitUpstreamAPIKey RPC.
	PortalServiceSubmitUpstreamAPIKeyProcedure = "/limen.portal.v1.PortalService/SubmitUpstreamAPIKey"
	// PortalServiceSetUpstreamLinkEnabledProcedure is the fully-qualified name of the PortalService's
	// SetUpstreamLinkEnabled RPC.
	PortalServiceSetUpstreamLinkEnabledProcedure = "/limen.portal.v1.PortalService/SetUpstreamLinkEnabled"
	// PortalServiceDisconnectProcedure is the fully-qualified name of the PortalService's Disconnect
	// RPC.
	PortalServiceDisconnectProcedure = "/limen.portal.v1.PortalService/Disconnect"
	// PortalServiceListMCPClientsProcedure is the fully-qualified name of the PortalService's
	// ListMCPClients RPC.
	PortalServiceListMCPClientsProcedure = "/limen.portal.v1.PortalService/ListMCPClients"
	// PortalServiceRevokeMCPClientProcedure is the fully-qualified name of the PortalService's
	// RevokeMCPClient RPC.
	PortalServiceRevokeMCPClientProcedure = "/limen.portal.v1.PortalService/RevokeMCPClient"
)

// PortalServiceClient is a client for the limen.portal.v1.PortalService service.
type PortalServiceClient interface {
	// Authenticated (any role).
	ListUpstreams(context.Context, *connect.Request[portalv1.ListUpstreamsRequest]) (*connect.Response[portalv1.ListUpstreamsResponse], error)
	StartConnect(context.Context, *connect.Request[portalv1.StartConnectRequest]) (*connect.Response[portalv1.StartConnectResponse], error)
	SubmitUpstreamAPIKey(context.Context, *connect.Request[portalv1.SubmitUpstreamAPIKeyRequest]) (*connect.Response[portalv1.SubmitUpstreamAPIKeyResponse], error)
	SetUpstreamLinkEnabled(context.Context, *connect.Request[portalv1.SetUpstreamLinkEnabledRequest]) (*connect.Response[portalv1.SetUpstreamLinkEnabledResponse], error)
	Disconnect(context.Context, *connect.Request[portalv1.DisconnectRequest]) (*connect.Response[portalv1.DisconnectResponse], error)
	ListMCPClients(context.Context, *connect.Request[portalv1.ListMCPClientsRequest]) (*connect.Response[portalv1.ListMCPClientsResponse], error)
	RevokeMCPClient(context.Context, *connect.Request[portalv1.RevokeMCPClientRequest]) (*connect.Response[portalv1.RevokeMCPClientResponse], error)
}

// NewPortalServiceClient constructs a client for the limen.portal.v1.PortalService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPortalServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PortalServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	portalServiceMethods := portalv1.File_limen_portal_v1_portal_proto.Services().ByName("PortalService").Methods()
	return &portalServiceClient{
		listUpstreams: connect.NewClient[portalv1.ListUpstreamsRequest, portalv1.ListUpstreamsResponse](
			httpClient,
			baseURL+PortalServiceListUpstreamsProcedure,
			connect.WithSchema(portalServiceMethods.ByName("ListUpstreams")),
			connect.WithClientOptions(opts...),
		),
		startConnect: connect.NewClient[portalv1.StartConnectRequest, portalv1.StartConnectResponse](
			httpClient,
			baseURL+PortalServiceStartConnectProcedure,
			connect.WithSchema(portalServiceMethods.ByName("StartConnect")),
			connect.WithClientOptions(opts...),
		),
		submitUpstreamAPIKey: connect.NewClient[portalv1.SubmitUpstreamAPIKeyRequest, portalv1.SubmitUpstreamAPIKeyResponse](
			httpClient,
			baseURL+PortalServiceSubmitUpstreamAPIKeyProcedure,
			connect.WithSchema(portalServiceMethods.ByName("SubmitUpstreamAPIKey")),
			connect.WithClientOptions(opts...),
		),
		setUpstreamLinkEnabled: connect.NewClient[portalv1.SetUpstreamLinkEnabledRequest, portalv1.SetUpstreamLinkEnabledResponse](
			httpClient,
			baseURL+PortalServiceSetUpstreamLinkEnabledProcedure,
			connect.WithSchema(portalServiceMethods.ByName("SetUpstreamLinkEnabled")),
			connect.WithClientOptions(opts...),
		),
		disconnect: connect.NewClient[portalv1.DisconnectRequest, portalv1.DisconnectResponse](
			httpClient,
			baseURL+PortalServiceDisconnectProcedure,
			connect.WithSchema(portalServiceMethods.ByName("Disconnect")),
			connect.WithClientOptions(opts...),
		),
		listMCPClients: connect.NewClient[portalv1.ListMCPClientsRequest, portalv1.ListMCPClientsResponse](
			httpClient,
			baseURL+PortalServiceListMCPClientsProcedure,
			connect.WithSchema(portalServiceMethods.ByName("ListMCPClients")),
			connect.WithClientOptions(opts...),
		),
		revokeMCPClient: connect.NewClient[portalv1.RevokeMCPClientRequest, portalv1.RevokeMCPClientResponse](
			httpClient,
			baseURL+PortalServiceRevokeMCPClientProcedure,
			connect.WithSchema(portalServiceMethods.ByName("RevokeMCPClient")),
			connect.WithClientOptions(opts...),
		),
	}
}

// portalServiceClient implements PortalServiceClient.
type portalServiceClient struct {
	listUpstreams          *connect.Client[portalv1.ListUpstreamsRequest, portalv1.ListUpstreamsResponse]
	startConnect           *connect.Client[portalv1.StartConnectRequest, portalv1.StartConnectResponse]
	submitUpstreamAPIKey   *connect.Client[portalv1.SubmitUpstreamAPIKeyRequest, portalv1.SubmitUpstreamAPIKeyResponse]
	setUpstreamLinkEnabled *connect.Client[portalv1.SetUpstreamLinkEnabledRequest, portalv1.SetUpstreamLinkEnabledResponse]
	disconnect             *connect.Client[portalv1.DisconnectRequest, portalv1.DisconnectResponse]
	listMCPClients         *connect.Client[portalv1.ListMCPClientsRequest, portalv1.ListMCPClientsResponse]
	revokeMCPClient        *connect.Client[portalv1.RevokeMCPClientRequest, portalv1.RevokeMCPClientResponse]
}

// ListUpstreams calls limen.portal.v1.PortalService.ListUpstreams.
func (c *portalServiceClient) ListUpstreams(ctx context.Context, req *connect.Request[portalv1.ListUpstreamsRequest]) (*connect.Response[portalv1.ListUpstreamsResponse], error) {
	return c.listUpstreams.CallUnary(ctx, req)
}

// StartConnect calls limen.portal.v1.PortalService.StartConnect.
func (c *portalServiceClient) StartConnect(ctx context.Context, req *connect.Request[portalv1.StartConnectRequest]) (*connect.Response[portalv1.StartConnectResponse], error) {
	return c.startConnect.CallUnary(ctx, req)
}

// SubmitUpstreamAPIKey calls limen.portal.v1.PortalService.SubmitUpstreamAPIKey.
func (c *portalServiceClient) SubmitUpstreamAPIKey(ctx context.Context, req *connect.Request[portalv1.SubmitUpstreamAPIKeyRequest]) (*connect.Response[portalv1.SubmitUpstreamAPIKeyResponse], error) {
	return c.submitUpstreamAPIKey.CallUnary(ctx, req)
}

// SetUpstreamLinkEnabled calls limen.portal.v1.PortalService.SetUpstreamLinkEnabled.
func (c *portalServiceClient) SetUpstreamLinkEnabled(ctx context.Context, req *connect.Request[portalv1.SetUpstreamLinkEnabledRequest]) (*connect.Response[portalv1.SetUpstreamLinkEnabledResponse], error) {
	return c.setUpstreamLinkEnabled.CallUnary(ctx, req)
}

// Disconnect calls limen.portal.v1.PortalService.Disconnect.
func (c *portalServiceClient) Disconnect(ctx context.Context, req *connect.Request[portalv1.DisconnectRequest]) (*connect.Response[portalv1.DisconnectResponse], error) {
	return c.disconnect.CallUnary(ctx, req)
}

// ListMCPClients calls limen.portal.v1.PortalService.ListMCPClients.
func (c *portalServiceClient) ListMCPClients(ctx context.Context, req *connect.Request[portalv1.ListMCPClientsRequest]) (*connect.Response[portalv1.ListMCPClientsResponse], error) {
	return c.listMCPClients.CallUnary(ctx, req)
}

// RevokeMCPClient calls limen.portal.v1.PortalService.RevokeMCPClient.
func (c *portalServiceClient) RevokeMCPClient(ctx context.Context, req *connect.Request[portalv1.RevokeMCPClientRequest]) (*connect.Response[portalv1.RevokeMCPClientResponse], error) {
	return c.revokeMCPClient.CallUnary(ctx, req)
}

// PortalServiceHandler is an implementation of the limen.portal.v1.PortalService service.
type PortalServiceHandler interface {
	// Authenticated (any role).
	ListUpstreams(context.Context, *connect.Request[portalv1.ListUpstreamsRequest]) (*connect.Response[portalv1.ListUpstreamsResponse], error)
	StartConnect(context.Context, *connect.Request[portalv1.StartConnectRequest]) (*connect.Response[portalv1.StartConnectResponse], error)
	SubmitUpstreamAPIKey(context.Context, *connect.Request[portalv1.SubmitUpstreamAPIKeyRequest]) (*connect.Response[portalv1.SubmitUpstreamAPIKeyResponse], error)
	SetUpstreamLinkEnabled(context.Context, *connect.Request[portalv1.SetUpstreamLinkEnabledRequest]) (*connect.Response[portalv1.SetUpstreamLinkEnabledResponse], error)
	Disconnect(context.Context, *connect.Request[portalv1.DisconnectRequest]) (*connect.Response[portalv1.DisconnectResponse], error)
	ListMCPClients(context.Context, *connect.Request[portalv1.ListMCPClientsRequest]) (*connect.Response[portalv1.ListMCPClientsResponse], error)
	RevokeMCPClient(context.Context, *connect.Request[portalv1.RevokeMCPClientRequest]) (*connect.Response[portalv1.RevokeMCPClientResponse], error)
}

// NewPortalServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPortalServiceHandler(svc PortalServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	portalServiceMethods := portalv1.File_limen_portal_v1_portal_proto.Services().ByName("PortalService").Methods()
	portalServiceListUpstreamsHandler := connect.NewUnaryHandler(
		PortalServiceListUpstreamsProcedure,
		svc.ListUpstreams,
		connect.WithSchema(portalServiceMethods.ByName("ListUpstreams")),
		connect.WithHandlerOptions(opts...),
	)
	portalServiceStartConnectHandler := connect.NewUnaryHandler(
		PortalServiceStartConnectProcedure,
		svc.StartConnect,
		connect.WithSchema(portalServiceMethods.ByName("StartConnect")),
		connect.WithHandlerOptions(opts...),
	)
	portalServiceSubmitUpstreamAPIKeyHandler := connect.NewUnaryHandler(
		PortalServiceSubmitUpstreamAPIKeyProcedure,
		svc.SubmitUpstreamAPIKey,
		connect.WithSchema(portalServiceMethods.ByName("SubmitUpstreamAPIKey")),
		connect.WithHandlerOptions(opts...),
	)
	portalServiceSetUpstreamLinkEnabledHandler := connect.NewUnaryHandler(
		PortalServiceSetUpstreamLinkEnabledProcedure,
		svc.SetUpstreamLinkEnabled,
		connect.WithSchema(portalServiceMethods.ByName("SetUpstreamLinkEnabled")),
		connect.WithHandlerOptions(opts...),
	)
	portalServiceDisconnectHandler := connect.NewUnaryHandler(
		PortalServiceDisconnectProcedure,
		svc.Disconnect,
		connect.WithSchema(portalServiceMethods.ByName("Disconnect")),
		connect.WithHandlerOptions(opts...),
	)
	portalServiceListMCPClientsHandler := connect.NewUnaryHandler(
		PortalServiceListMCPClientsProcedure,
		svc.ListMCPClients,
		connect.WithSchema(portalServiceMethods.ByName("ListMCPClients")),
		connect.WithHandlerOptions(opts...),
	)
	portalServiceRevokeMCPClientHandler := connect.NewUnaryHandler(
		PortalServiceRevokeMCPClientProcedure,
		svc.RevokeMCPClient,
		connect.WithSchema(portalServiceMethods.ByName("RevokeMCPClient")),
		connect.WithHandlerOptions(opts...),
	)
	return "/limen.portal.v1.PortalService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PortalServiceListUpstreamsProcedure:
			portalServiceListUpstreamsHandler.ServeHTTP(w, r)
		case PortalServiceStartConnectProcedure:
			portalServiceStartConnectHandler.ServeHTTP(w, r)
		case PortalServiceSubmitUpstreamAPIKeyProcedure:
			portalServiceSubmitUpstreamAPIKeyHandler.ServeHTTP(w, r)
		case PortalServiceSetUpstreamLinkEnabledProcedure:
			portalServiceSetUpstreamLinkEnabledHandler.ServeHTTP(w, r)
		case PortalServiceDisconnectProcedure:
			portalServiceDisconnectHandler.ServeHTTP(w, r)
		case PortalServiceListMCPClientsProcedure:
			portalServiceListMCPClientsHandler.ServeHTTP(w, r)
		case PortalServiceRevokeMCPClientProcedure:
			portalServiceRevokeMCPClientHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPortalServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPortalServiceHandler struct{}

func (UnimplementedPortalServiceHandler) ListUpstreams(context.Context, *connect.Request[portalv1.ListUpstreamsRequest]) (*connect.Response[portalv1.ListUpstreamsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("limen.portal.v1.PortalService.ListUpstreams is not implemented"))
}

func (UnimplementedPortalServiceHandler) StartConnect(context.Context, *connect.Request[portalv1.StartConnectRequest]) (*connect.Response[portalv1.StartConnectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("limen.portal.v1.PortalService.StartConnect is not implemented"))
}

func (UnimplementedPortalServiceHandler) SubmitUpstreamAPIKey(context.Context, *connect.Request[portalv1.SubmitUpstreamAPIKeyRequest]) (*connect.Response[portalv1.SubmitUpstreamAPIKeyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("limen.portal.v1.PortalService.SubmitUpstreamAPIKey is not implemented"))
}

func (UnimplementedPortalServiceHandler) SetUpstreamLinkEnabled(context.Context, *connect.Request[portalv1.SetUpstreamLinkEnabledRequest]) (*connect.Response[portalv1.SetUpstreamLinkEnabledResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("limen.portal.v1.PortalService.SetUpstreamLinkEnabled is not implemented"))
}

func (UnimplementedPortalServiceHandler) Disconnect(context.Context, *connect.Request[portalv1.DisconnectRequest]) (*connect.Response[portalv1.DisconnectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("limen.portal.v1.PortalService.Disconnect is not implemented"))
}

func (UnimplementedPortalServiceHandler) ListMCPClients(context.Context, *connect.Request[portalv1.ListMCPClientsRequest]) (*connect.Response[portalv1.ListMCPClientsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("limen.portal.v1.PortalService.ListMCPClients is not implemented"))
}

func (UnimplementedPortalServiceHandler) RevokeMCPClient(context.Context, *connect.Request[portalv1.RevokeMCPClientRequest]) (*connect.Response[portalv1.RevokeMCPClientResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("limen.portal.v1.PortalService.RevokeMCPClient is not implemented"))
}
