// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: limen/session/v1/session.proto

package sessionv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	sessionv1 "github.com/belphemur/limen/internal/session/sessionv1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SessionServiceName is the fully-qualified name of the SessionService service.
	SessionServiceName = "limen.session.v1.SessionService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SessionServiceGetSessionProcedure is the fully-qualified name of the SessionService's GetSession
	// RPC.
	SessionServiceGetSessionProcedure = "/limen.session.v1.SessionService/GetSession"
)

// SessionServiceClient is a client for the limen.session.v1.SessionService service.
type SessionServiceClient interface {
	// GetSession returns the caller's identity facts derived from the
	// portal cookie. Unauthenticated callers receive Connect
	// `unauthenticated` (HTTP 401); the SPA's router guard turns that
	// into a `/auth/login` redirect.
	GetSession(context.Context, *connect.Request[sessionv1.GetSessionRequest]) (*connect.Response[sessionv1.GetSessionResponse], error)
}

// NewSessionServiceClient constructs a client for the limen.session.v1.SessionService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSessionServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SessionServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	sessionServiceMethods := sessionv1.File_limen_session_v1_session_proto.Services().ByName("SessionService").Methods()
	return &sessionServiceClient{
		getSession: connect.NewClient[sessionv1.GetSessionRequest, sessionv1.GetSessionResponse](
			httpClient,
			baseURL+SessionServiceGetSessionProcedure,
			connect.WithSchema(sessionServiceMethods.ByName("GetSession")),
			connect.WithClientOptions(opts...),
		),
	}
}

// sessionServiceClient implements SessionServiceClient.
type sessionServiceClient struct {
	getSession *connect.Client[sessionv1.GetSessionRequest, sessionv1.GetSessionResponse]
}

// GetSession calls limen.session.v1.SessionService.GetSession.
func (c *sessionServiceClient) GetSession(ctx context.Context, req *connect.Request[sessionv1.GetSessionRequest]) (*connect.Response[sessionv1.GetSessionResponse], error) {
	return c.getSession.CallUnary(ctx, req)
}

// SessionServiceHandler is an implementation of the limen.session.v1.SessionService service.
type SessionServiceHandler interface {
	// GetSession returns the caller's identity facts derived from the
	// portal cookie. Unauthenticated callers receive Connect
	// `unauthenticated` (HTTP 401); the SPA's router guard turns that
	// into a `/auth/login` redirect.
	GetSession(context.Context, *connect.Request[sessionv1.GetSessionRequest]) (*connect.Response[sessionv1.GetSessionResponse], error)
}

// NewSessionServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSessionServiceHandler(svc SessionServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	sessionServiceMethods := sessionv1.File_limen_session_v1_session_proto.Services().ByName("SessionService").Methods()
	sessionServiceGetSessionHandler := connect.NewUnaryHandler(
		SessionServiceGetSessionProcedure,
		svc.GetSession,
		connect.WithSchema(sessionServiceMethods.ByName("GetSession")),
		connect.WithHandlerOptions(opts...),
	)
	return "/limen.session.v1.SessionService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SessionServiceGetSessionProcedure:
			sessionServiceGetSessionHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSessionServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSessionServiceHandler struct{}

func (UnimplementedSessionServiceHandler) GetSession(context.Context, *connect.Request[sessionv1.GetSessionRequest]) (*connect.Response[sessionv1.GetSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("limen.session.v1.SessionService.GetSession is not implemented"))
}
