// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: limen/signup/v1/signup.proto

package signupv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartSignupRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OrganizationName string                 `protobuf:"bytes,1,opt,name=organization_name,json=organizationName,proto3" json:"organization_name,omitempty"`
	OwnerEmail       string                 `protobuf:"bytes,2,opt,name=owner_email,json=ownerEmail,proto3" json:"owner_email,omitempty"`
	OwnerName        string                 `protobuf:"bytes,3,opt,name=owner_name,json=ownerName,proto3" json:"owner_name,omitempty"`
	// Captcha provider's response token (Cloudflare Turnstile in dev).
	CaptchaToken  string `protobuf:"bytes,4,opt,name=captcha_token,json=captchaToken,proto3" json:"captcha_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSignupRequest) Reset() {
	*x = StartSignupRequest{}
	mi := &file_limen_signup_v1_signup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSignupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSignupRequest) ProtoMessage() {}

func (x *StartSignupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_limen_signup_v1_signup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSignupRequest.ProtoReflect.Descriptor instead.
func (*StartSignupRequest) Descriptor() ([]byte, []int) {
	return file_limen_signup_v1_signup_proto_rawDescGZIP(), []int{0}
}

func (x *StartSignupRequest) GetOrganizationName() string {
	if x != nil {
		return x.OrganizationName
	}
	return ""
}

func (x *StartSignupRequest) GetOwnerEmail() string {
	if x != nil {
		return x.OwnerEmail
	}
	return ""
}

func (x *StartSignupRequest) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

func (x *StartSignupRequest) GetCaptchaToken() string {
	if x != nil {
		return x.CaptchaToken
	}
	return ""
}

type StartSignupResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// HMAC-signed token carrying the signup payload + expiry.
	SignupToken string `protobuf:"bytes,1,opt,name=signup_token,json=signupToken,proto3" json:"signup_token,omitempty"`
	// Absolute or SPA-relative URL the SPA should send the browser to
	// (typically /auth/signup?token=<signup_token>).
	SignupUrl     string `protobuf:"bytes,2,opt,name=signup_url,json=signupUrl,proto3" json:"signup_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSignupResponse) Reset() {
	*x = StartSignupResponse{}
	mi := &file_limen_signup_v1_signup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSignupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSignupResponse) ProtoMessage() {}

func (x *StartSignupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_limen_signup_v1_signup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSignupResponse.ProtoReflect.Descriptor instead.
func (*StartSignupResponse) Descriptor() ([]byte, []int) {
	return file_limen_signup_v1_signup_proto_rawDescGZIP(), []int{1}
}

func (x *StartSignupResponse) GetSignupToken() string {
	if x != nil {
		return x.SignupToken
	}
	return ""
}

func (x *StartSignupResponse) GetSignupUrl() string {
	if x != nil {
		return x.SignupUrl
	}
	return ""
}

type CompleteSignupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteSignupRequest) Reset() {
	*x = CompleteSignupRequest{}
	mi := &file_limen_signup_v1_signup_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteSignupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteSignupRequest) ProtoMessage() {}

func (x *CompleteSignupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_limen_signup_v1_signup_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteSignupRequest.ProtoReflect.Descriptor instead.
func (*CompleteSignupRequest) Descriptor() ([]byte, []int) {
	return file_limen_signup_v1_signup_proto_rawDescGZIP(), []int{2}
}

type CompleteSignupResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TenantPublicId string                 `protobuf:"bytes,1,opt,name=tenant_public_id,json=tenantPublicId,proto3" json:"tenant_public_id,omitempty"`
	// Absolute or SPA-relative URL: /t/<tenant_public_id>/admin/.
	AdminUrl      string `protobuf:"bytes,2,opt,name=admin_url,json=adminUrl,proto3" json:"admin_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteSignupResponse) Reset() {
	*x = CompleteSignupResponse{}
	mi := &file_limen_signup_v1_signup_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteSignupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteSignupResponse) ProtoMessage() {}

func (x *CompleteSignupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_limen_signup_v1_signup_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteSignupResponse.ProtoReflect.Descriptor instead.
func (*CompleteSignupResponse) Descriptor() ([]byte, []int) {
	return file_limen_signup_v1_signup_proto_rawDescGZIP(), []int{3}
}

func (x *CompleteSignupResponse) GetTenantPublicId() string {
	if x != nil {
		return x.TenantPublicId
	}
	return ""
}

func (x *CompleteSignupResponse) GetAdminUrl() string {
	if x != nil {
		return x.AdminUrl
	}
	return ""
}

var File_limen_signup_v1_signup_proto protoreflect.FileDescriptor

const file_limen_signup_v1_signup_proto_rawDesc = "" +
	"\n" +
	"\x1climen/signup/v1/signup.proto\x12\x0flimen.signup.v1\"\xa6\x01\n" +
	"\x12StartSignupRequest\x12+\n" +
	"\x11organization_name\x18\x01 \x01(\tR\x10organizationName\x12\x1f\n" +
	"\vowner_email\x18\x02 \x01(\tR\n" +
	"ownerEmail\x12\x1d\n" +
	"\n" +
	"owner_name\x18\x03 \x01(\tR\townerName\x12#\n" +
	"\rcaptcha_token\x18\x04 \x01(\tR\fcaptchaToken\"W\n" +
	"\x13StartSignupResponse\x12!\n" +
	"\fsignup_token\x18\x01 \x01(\tR\vsignupToken\x12\x1d\n" +
	"\n" +
	"signup_url\x18\x02 \x01(\tR\tsignupUrl\"\x17\n" +
	"\x15CompleteSignupRequest\"_\n" +
	"\x16CompleteSignupResponse\x12(\n" +
	"\x10tenant_public_id\x18\x01 \x01(\tR\x0etenantPublicId\x12\x1b\n" +
	"\tadmin_url\x18\x02 \x01(\tR\badminUrl2\xcc\x01\n" +
	"\rSignupService\x12X\n" +
	"\vStartSignup\x12#.limen.signup.v1.StartSignupRequest\x1a$.limen.signup.v1.StartSignupResponse\x12a\n" +
	"\x0eCompleteSignup\x12&.limen.signup.v1.CompleteSignupRequest\x1a'.limen.signup.v1.CompleteSignupResponseB>Z<github.com/belphemur/limen/internal/signup/signupv1;signupv1b\x06proto3"

var (
	file_limen_signup_v1_signup_proto_rawDescOnce sync.Once
	file_limen_signup_v1_signup_proto_rawDescData []byte
)

func file_limen_signup_v1_signup_proto_rawDescGZIP() []byte {
	file_limen_signup_v1_signup_proto_rawDescOnce.Do(func() {
		file_limen_signup_v1_signup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_limen_signup_v1_signup_proto_rawDesc), len(file_limen_signup_v1_signup_proto_rawDesc)))
	})
	return file_limen_signup_v1_signup_proto_rawDescData
}

var file_limen_signup_v1_signup_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_limen_signup_v1_signup_proto_goTypes = []any{
	(*StartSignupRequest)(nil),     // 0: limen.signup.v1.StartSignupRequest
	(*StartSignupResponse)(nil),    // 1: limen.signup.v1.StartSignupResponse
	(*CompleteSignupRequest)(nil),  // 2: limen.signup.v1.CompleteSignupRequest
	(*CompleteSignupResponse)(nil), // 3: limen.signup.v1.CompleteSignupResponse
}
var file_limen_signup_v1_signup_proto_depIdxs = []int32{
	0, // 0: limen.signup.v1.SignupService.StartSignup:input_type -> limen.signup.v1.StartSignupRequest
	2, // 1: limen.signup.v1.SignupService.CompleteSignup:input_type -> limen.signup.v1.CompleteSignupRequest
	1, // 2: limen.signup.v1.SignupService.StartSignup:output_type -> limen.signup.v1.StartSignupResponse
	3, // 3: limen.signup.v1.SignupService.CompleteSignup:output_type -> limen.signup.v1.CompleteSignupResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_limen_signup_v1_signup_proto_init() }
func file_limen_signup_v1_signup_proto_init() {
	if File_limen_signup_v1_signup_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_limen_signup_v1_signup_proto_rawDesc), len(file_limen_signup_v1_signup_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_limen_signup_v1_signup_proto_goTypes,
		DependencyIndexes: file_limen_signup_v1_signup_proto_depIdxs,
		MessageInfos:      file_limen_signup_v1_signup_proto_msgTypes,
	}.Build()
	File_limen_signup_v1_signup_proto = out.File
	file_limen_signup_v1_signup_proto_goTypes = nil
	file_limen_signup_v1_signup_proto_depIdxs = nil
}
