// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: limen/admin/v1/admin.proto

package adminv1

import (
	portalv1 "github.com/belphemur/limen/internal/portal/portalv1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MemberRole is the closed set of role keys the tenant admin can
// assign on the Limen project. Mirrors the keys seeded by
// scripts/zitadel-bootstrap (member / admin / owner). super_admin is
// staff-only and deliberately absent so it cannot be assigned over
// the wire.
type MemberRole int32

const (
	MemberRole_MEMBER_ROLE_UNSPECIFIED MemberRole = 0
	MemberRole_MEMBER_ROLE_MEMBER      MemberRole = 1
	MemberRole_MEMBER_ROLE_ADMIN       MemberRole = 2
	MemberRole_MEMBER_ROLE_OWNER       MemberRole = 3
)

// Enum value maps for MemberRole.
var (
	MemberRole_name = map[int32]string{
		0: "MEMBER_ROLE_UNSPECIFIED",
		1: "MEMBER_ROLE_MEMBER",
		2: "MEMBER_ROLE_ADMIN",
		3: "MEMBER_ROLE_OWNER",
	}
	MemberRole_value = map[string]int32{
		"MEMBER_ROLE_UNSPECIFIED": 0,
		"MEMBER_ROLE_MEMBER":      1,
		"MEMBER_ROLE_ADMIN":       2,
		"MEMBER_ROLE_OWNER":       3,
	}
)

func (x MemberRole) Enum() *MemberRole {
	p := new(MemberRole)
	*p = x
	return p
}

func (x MemberRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MemberRole) Descriptor() protoreflect.EnumDescriptor {
	return file_limen_admin_v1_admin_proto_enumTypes[0].Descriptor()
}

func (MemberRole) Type() protoreflect.EnumType {
	return &file_limen_admin_v1_admin_proto_enumTypes[0]
}

func (x MemberRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MemberRole.Descriptor instead.
func (MemberRole) EnumDescriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{0}
}

// MemberState mirrors Zitadel's UserState. UNSPECIFIED is returned
// only when Zitadel reports a state Limen does not understand.
type MemberState int32

const (
	MemberState_MEMBER_STATE_UNSPECIFIED MemberState = 0
	MemberState_MEMBER_STATE_ACTIVE      MemberState = 1
	MemberState_MEMBER_STATE_INACTIVE    MemberState = 2
	MemberState_MEMBER_STATE_LOCKED      MemberState = 3
	MemberState_MEMBER_STATE_INITIAL     MemberState = 4
)

// Enum value maps for MemberState.
var (
	MemberState_name = map[int32]string{
		0: "MEMBER_STATE_UNSPECIFIED",
		1: "MEMBER_STATE_ACTIVE",
		2: "MEMBER_STATE_INACTIVE",
		3: "MEMBER_STATE_LOCKED",
		4: "MEMBER_STATE_INITIAL",
	}
	MemberState_value = map[string]int32{
		"MEMBER_STATE_UNSPECIFIED": 0,
		"MEMBER_STATE_ACTIVE":      1,
		"MEMBER_STATE_INACTIVE":    2,
		"MEMBER_STATE_LOCKED":      3,
		"MEMBER_STATE_INITIAL":     4,
	}
)

func (x MemberState) Enum() *MemberState {
	p := new(MemberState)
	*p = x
	return p
}

func (x MemberState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MemberState) Descriptor() protoreflect.EnumDescriptor {
	return file_limen_admin_v1_admin_proto_enumTypes[1].Descriptor()
}

func (MemberState) Type() protoreflect.EnumType {
	return &file_limen_admin_v1_admin_proto_enumTypes[1]
}

func (x MemberState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MemberState.Descriptor instead.
func (MemberState) EnumDescriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{1}
}

// OAuthClientOverride lets the admin pin a pre-registered upstream
// OAuth client (for mcp_spec ASes without DCR). Both fields are
// required when this message is present.
type OAuthClientOverride struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSecret  string                 `protobuf:"bytes,2,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OAuthClientOverride) Reset() {
	*x = OAuthClientOverride{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuthClientOverride) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuthClientOverride) ProtoMessage() {}

func (x *OAuthClientOverride) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuthClientOverride.ProtoReflect.Descriptor instead.
func (*OAuthClientOverride) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{0}
}

func (x *OAuthClientOverride) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *OAuthClientOverride) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

type CreateUpstreamRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Identifier   string                 `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	DisplayName  string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	McpUrl       string                 `protobuf:"bytes,3,opt,name=mcp_url,json=mcpUrl,proto3" json:"mcp_url,omitempty"`
	StrategyType string                 `protobuf:"bytes,4,opt,name=strategy_type,json=strategyType,proto3" json:"strategy_type,omitempty"`
	// e.g. "tenant" / "user" for static_header. Empty otherwise.
	StrategySubMode string `protobuf:"bytes,5,opt,name=strategy_sub_mode,json=strategySubMode,proto3" json:"strategy_sub_mode,omitempty"`
	// Strategy-specific static config (e.g. tenant-wide API key for
	// static_header tenant-mode).
	StrategyConfig map[string]string `protobuf:"bytes,6,rep,name=strategy_config,json=strategyConfig,proto3" json:"strategy_config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Optional pre-registered OAuth client for ASes without DCR.
	OauthClientOverride *OAuthClientOverride `protobuf:"bytes,7,opt,name=oauth_client_override,json=oauthClientOverride,proto3" json:"oauth_client_override,omitempty"`
	// JSON object serialised as a string; validated server-side via
	// gateway.validateContextBlob.
	DefaultsJson  string `protobuf:"bytes,8,opt,name=defaults_json,json=defaultsJson,proto3" json:"defaults_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUpstreamRequest) Reset() {
	*x = CreateUpstreamRequest{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUpstreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUpstreamRequest) ProtoMessage() {}

func (x *CreateUpstreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUpstreamRequest.ProtoReflect.Descriptor instead.
func (*CreateUpstreamRequest) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUpstreamRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *CreateUpstreamRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CreateUpstreamRequest) GetMcpUrl() string {
	if x != nil {
		return x.McpUrl
	}
	return ""
}

func (x *CreateUpstreamRequest) GetStrategyType() string {
	if x != nil {
		return x.StrategyType
	}
	return ""
}

func (x *CreateUpstreamRequest) GetStrategySubMode() string {
	if x != nil {
		return x.StrategySubMode
	}
	return ""
}

func (x *CreateUpstreamRequest) GetStrategyConfig() map[string]string {
	if x != nil {
		return x.StrategyConfig
	}
	return nil
}

func (x *CreateUpstreamRequest) GetOauthClientOverride() *OAuthClientOverride {
	if x != nil {
		return x.OauthClientOverride
	}
	return nil
}

func (x *CreateUpstreamRequest) GetDefaultsJson() string {
	if x != nil {
		return x.DefaultsJson
	}
	return ""
}

type CreateUpstreamResponse struct {
	state    protoimpl.MessageState    `protogen:"open.v1"`
	Upstream *portalv1.UpstreamSummary `protobuf:"bytes,1,opt,name=upstream,proto3" json:"upstream,omitempty"`
	// True when the strategy requires an owner/admin link before the
	// tool catalog can be populated (mcp_spec, static_header user-mode).
	RequiresAdminLink bool `protobuf:"varint,2,opt,name=requires_admin_link,json=requiresAdminLink,proto3" json:"requires_admin_link,omitempty"`
	// Absolute or SPA-relative URL the SPA should open to start the
	// admin-link flow. Empty when requires_admin_link is false.
	ConnectUrl    string `protobuf:"bytes,3,opt,name=connect_url,json=connectUrl,proto3" json:"connect_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUpstreamResponse) Reset() {
	*x = CreateUpstreamResponse{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUpstreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUpstreamResponse) ProtoMessage() {}

func (x *CreateUpstreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUpstreamResponse.ProtoReflect.Descriptor instead.
func (*CreateUpstreamResponse) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{2}
}

func (x *CreateUpstreamResponse) GetUpstream() *portalv1.UpstreamSummary {
	if x != nil {
		return x.Upstream
	}
	return nil
}

func (x *CreateUpstreamResponse) GetRequiresAdminLink() bool {
	if x != nil {
		return x.RequiresAdminLink
	}
	return false
}

func (x *CreateUpstreamResponse) GetConnectUrl() string {
	if x != nil {
		return x.ConnectUrl
	}
	return ""
}

type UpdateUpstreamRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	PublicId string                 `protobuf:"bytes,1,opt,name=public_id,json=publicId,proto3" json:"public_id,omitempty"`
	// Optional. Empty string clears the override; absent leaves it.
	// Use the wrapper-free convention: callers send empty strings to
	// mean "no change" — this matches the rest of PortalService.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Optional. Empty string is interpreted as "no change"; pass "{}"
	// to clear. Validated server-side.
	DefaultsJson  string `protobuf:"bytes,3,opt,name=defaults_json,json=defaultsJson,proto3" json:"defaults_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUpstreamRequest) Reset() {
	*x = UpdateUpstreamRequest{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUpstreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUpstreamRequest) ProtoMessage() {}

func (x *UpdateUpstreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUpstreamRequest.ProtoReflect.Descriptor instead.
func (*UpdateUpstreamRequest) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateUpstreamRequest) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

func (x *UpdateUpstreamRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *UpdateUpstreamRequest) GetDefaultsJson() string {
	if x != nil {
		return x.DefaultsJson
	}
	return ""
}

type UpdateUpstreamResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Upstream      *portalv1.UpstreamSummary `protobuf:"bytes,1,opt,name=upstream,proto3" json:"upstream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUpstreamResponse) Reset() {
	*x = UpdateUpstreamResponse{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUpstreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUpstreamResponse) ProtoMessage() {}

func (x *UpdateUpstreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUpstreamResponse.ProtoReflect.Descriptor instead.
func (*UpdateUpstreamResponse) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateUpstreamResponse) GetUpstream() *portalv1.UpstreamSummary {
	if x != nil {
		return x.Upstream
	}
	return nil
}

type DeleteUpstreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicId      string                 `protobuf:"bytes,1,opt,name=public_id,json=publicId,proto3" json:"public_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUpstreamRequest) Reset() {
	*x = DeleteUpstreamRequest{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUpstreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUpstreamRequest) ProtoMessage() {}

func (x *DeleteUpstreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUpstreamRequest.ProtoReflect.Descriptor instead.
func (*DeleteUpstreamRequest) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteUpstreamRequest) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

type DeleteUpstreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUpstreamResponse) Reset() {
	*x = DeleteUpstreamResponse{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUpstreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUpstreamResponse) ProtoMessage() {}

func (x *DeleteUpstreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUpstreamResponse.ProtoReflect.Descriptor instead.
func (*DeleteUpstreamResponse) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{6}
}

type ReindexUpstreamCatalogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicId      string                 `protobuf:"bytes,1,opt,name=public_id,json=publicId,proto3" json:"public_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReindexUpstreamCatalogRequest) Reset() {
	*x = ReindexUpstreamCatalogRequest{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReindexUpstreamCatalogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReindexUpstreamCatalogRequest) ProtoMessage() {}

func (x *ReindexUpstreamCatalogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReindexUpstreamCatalogRequest.ProtoReflect.Descriptor instead.
func (*ReindexUpstreamCatalogRequest) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{7}
}

func (x *ReindexUpstreamCatalogRequest) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

type ReindexUpstreamCatalogResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Upstream      *portalv1.UpstreamSummary `protobuf:"bytes,1,opt,name=upstream,proto3" json:"upstream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReindexUpstreamCatalogResponse) Reset() {
	*x = ReindexUpstreamCatalogResponse{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReindexUpstreamCatalogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReindexUpstreamCatalogResponse) ProtoMessage() {}

func (x *ReindexUpstreamCatalogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReindexUpstreamCatalogResponse.ProtoReflect.Descriptor instead.
func (*ReindexUpstreamCatalogResponse) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{8}
}

func (x *ReindexUpstreamCatalogResponse) GetUpstream() *portalv1.UpstreamSummary {
	if x != nil {
		return x.Upstream
	}
	return nil
}

type PreviewUpstreamContextRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	PublicId string                 `protobuf:"bytes,1,opt,name=public_id,json=publicId,proto3" json:"public_id,omitempty"`
	// Zitadel subject of the user whose per-link context the admin
	// wants to spot-check against the upstream's defaults_json.
	UserId        string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewUpstreamContextRequest) Reset() {
	*x = PreviewUpstreamContextRequest{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewUpstreamContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewUpstreamContextRequest) ProtoMessage() {}

func (x *PreviewUpstreamContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewUpstreamContextRequest.ProtoReflect.Descriptor instead.
func (*PreviewUpstreamContextRequest) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{9}
}

func (x *PreviewUpstreamContextRequest) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

func (x *PreviewUpstreamContextRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type PreviewUpstreamContextResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The merged JSON object as a string: merge(linkContext, defaultsJson).
	MergedJson    string `protobuf:"bytes,1,opt,name=merged_json,json=mergedJson,proto3" json:"merged_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewUpstreamContextResponse) Reset() {
	*x = PreviewUpstreamContextResponse{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewUpstreamContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewUpstreamContextResponse) ProtoMessage() {}

func (x *PreviewUpstreamContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewUpstreamContextResponse.ProtoReflect.Descriptor instead.
func (*PreviewUpstreamContextResponse) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{10}
}

func (x *PreviewUpstreamContextResponse) GetMergedJson() string {
	if x != nil {
		return x.MergedJson
	}
	return ""
}

type GetTenantSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantSettingsRequest) Reset() {
	*x = GetTenantSettingsRequest{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantSettingsRequest) ProtoMessage() {}

func (x *GetTenantSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantSettingsRequest.ProtoReflect.Descriptor instead.
func (*GetTenantSettingsRequest) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{11}
}

type GetTenantSettingsResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Settings *TenantSettings        `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	// Read-only Zitadel identity. The SPA renders these as a panel and
	// uses zitadel_org_id to build Console deep-links.
	ZitadelOrgId string `protobuf:"bytes,2,opt,name=zitadel_org_id,json=zitadelOrgId,proto3" json:"zitadel_org_id,omitempty"`
	// Limen Gateway project ID (Zitadel-side). Constant per Limen
	// instance, echoed here so the SPA can render the
	// /ui/console/granted-projects/<projectId>/grant/<grantId> deep-link
	// for managing this tenant's role assignments without a separate
	// discovery round-trip.
	ZitadelProjectId string `protobuf:"bytes,3,opt,name=zitadel_project_id,json=zitadelProjectId,proto3" json:"zitadel_project_id,omitempty"`
	// ID of the project grant that grants the Limen project to this
	// tenant's org. Empty when the grant cannot be resolved (Zitadel
	// unreachable, grant missing) — the SPA renders the
	// role-assignment card disabled in that case.
	ZitadelProjectGrantId string `protobuf:"bytes,4,opt,name=zitadel_project_grant_id,json=zitadelProjectGrantId,proto3" json:"zitadel_project_grant_id,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetTenantSettingsResponse) Reset() {
	*x = GetTenantSettingsResponse{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantSettingsResponse) ProtoMessage() {}

func (x *GetTenantSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantSettingsResponse.ProtoReflect.Descriptor instead.
func (*GetTenantSettingsResponse) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{12}
}

func (x *GetTenantSettingsResponse) GetSettings() *TenantSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *GetTenantSettingsResponse) GetZitadelOrgId() string {
	if x != nil {
		return x.ZitadelOrgId
	}
	return ""
}

func (x *GetTenantSettingsResponse) GetZitadelProjectId() string {
	if x != nil {
		return x.ZitadelProjectId
	}
	return ""
}

func (x *GetTenantSettingsResponse) GetZitadelProjectGrantId() string {
	if x != nil {
		return x.ZitadelProjectGrantId
	}
	return ""
}

type UpdateTenantSettingsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional. Empty string means "no change".
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// One-shot toggle: when true, flip tenant_settings.invited_team_at
	// to NOW() if it is currently NULL. No-op otherwise.
	InvitedTeamAtNow bool `protobuf:"varint,2,opt,name=invited_team_at_now,json=invitedTeamAtNow,proto3" json:"invited_team_at_now,omitempty"`
	// One-shot toggle: same semantics as invited_team_at_now but for
	// tenant_settings.configured_at.
	ConfiguredAtNow bool `protobuf:"varint,3,opt,name=configured_at_now,json=configuredAtNow,proto3" json:"configured_at_now,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateTenantSettingsRequest) Reset() {
	*x = UpdateTenantSettingsRequest{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTenantSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTenantSettingsRequest) ProtoMessage() {}

func (x *UpdateTenantSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTenantSettingsRequest.ProtoReflect.Descriptor instead.
func (*UpdateTenantSettingsRequest) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateTenantSettingsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTenantSettingsRequest) GetInvitedTeamAtNow() bool {
	if x != nil {
		return x.InvitedTeamAtNow
	}
	return false
}

func (x *UpdateTenantSettingsRequest) GetConfiguredAtNow() bool {
	if x != nil {
		return x.ConfiguredAtNow
	}
	return false
}

type TenantSettings struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Name     string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PublicId string                 `protobuf:"bytes,2,opt,name=public_id,json=publicId,proto3" json:"public_id,omitempty"`
	// RFC3339; empty when unset.
	InvitedTeamAt string `protobuf:"bytes,3,opt,name=invited_team_at,json=invitedTeamAt,proto3" json:"invited_team_at,omitempty"`
	ConfiguredAt  string `protobuf:"bytes,4,opt,name=configured_at,json=configuredAt,proto3" json:"configured_at,omitempty"`
	ChoseIdeAt    string `protobuf:"bytes,5,opt,name=chose_ide_at,json=choseIdeAt,proto3" json:"chose_ide_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantSettings) Reset() {
	*x = TenantSettings{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantSettings) ProtoMessage() {}

func (x *TenantSettings) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantSettings.ProtoReflect.Descriptor instead.
func (*TenantSettings) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{14}
}

func (x *TenantSettings) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TenantSettings) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

func (x *TenantSettings) GetInvitedTeamAt() string {
	if x != nil {
		return x.InvitedTeamAt
	}
	return ""
}

func (x *TenantSettings) GetConfiguredAt() string {
	if x != nil {
		return x.ConfiguredAt
	}
	return ""
}

func (x *TenantSettings) GetChoseIdeAt() string {
	if x != nil {
		return x.ChoseIdeAt
	}
	return ""
}

type UpdateTenantSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      *TenantSettings        `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTenantSettingsResponse) Reset() {
	*x = UpdateTenantSettingsResponse{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTenantSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTenantSettingsResponse) ProtoMessage() {}

func (x *UpdateTenantSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTenantSettingsResponse.ProtoReflect.Descriptor instead.
func (*UpdateTenantSettingsResponse) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateTenantSettingsResponse) GetSettings() *TenantSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type IDEPreset struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable key: "cursor", "vscode", "claude_code", ...
	Key         string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Lucide icon name shown on the quick-setup tile.
	Icon string `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	// Raw glob patterns the preset declares. Every pattern passes
	// oauthproxy.CompilePattern at seed time.
	Patterns      []string `protobuf:"bytes,4,rep,name=patterns,proto3" json:"patterns,omitempty"`
	SortOrder     int32    `protobuf:"varint,5,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IDEPreset) Reset() {
	*x = IDEPreset{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IDEPreset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDEPreset) ProtoMessage() {}

func (x *IDEPreset) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDEPreset.ProtoReflect.Descriptor instead.
func (*IDEPreset) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{16}
}

func (x *IDEPreset) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *IDEPreset) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *IDEPreset) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *IDEPreset) GetPatterns() []string {
	if x != nil {
		return x.Patterns
	}
	return nil
}

func (x *IDEPreset) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type AllowlistEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// "ral_<ULID>" — opaque to the SPA, only used as the addressable id
	// on Update/Remove.
	PublicId string `protobuf:"bytes,1,opt,name=public_id,json=publicId,proto3" json:"public_id,omitempty"`
	// "" when the entry is a free-form admin entry (no preset link).
	IdeKey  string `protobuf:"bytes,2,opt,name=ide_key,json=ideKey,proto3" json:"ide_key,omitempty"`
	Label   string `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	Pattern string `protobuf:"bytes,4,opt,name=pattern,proto3" json:"pattern,omitempty"`
	// RFC3339.
	CreatedAt     string `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllowlistEntry) Reset() {
	*x = AllowlistEntry{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllowlistEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllowlistEntry) ProtoMessage() {}

func (x *AllowlistEntry) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllowlistEntry.ProtoReflect.Descriptor instead.
func (*AllowlistEntry) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{17}
}

func (x *AllowlistEntry) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

func (x *AllowlistEntry) GetIdeKey() string {
	if x != nil {
		return x.IdeKey
	}
	return ""
}

func (x *AllowlistEntry) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *AllowlistEntry) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *AllowlistEntry) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ListIDEPresetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIDEPresetsRequest) Reset() {
	*x = ListIDEPresetsRequest{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIDEPresetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIDEPresetsRequest) ProtoMessage() {}

func (x *ListIDEPresetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIDEPresetsRequest.ProtoReflect.Descriptor instead.
func (*ListIDEPresetsRequest) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{18}
}

type ListIDEPresetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Presets       []*IDEPreset           `protobuf:"bytes,1,rep,name=presets,proto3" json:"presets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIDEPresetsResponse) Reset() {
	*x = ListIDEPresetsResponse{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIDEPresetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIDEPresetsResponse) ProtoMessage() {}

func (x *ListIDEPresetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIDEPresetsResponse.ProtoReflect.Descriptor instead.
func (*ListIDEPresetsResponse) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{19}
}

func (x *ListIDEPresetsResponse) GetPresets() []*IDEPreset {
	if x != nil {
		return x.Presets
	}
	return nil
}

type ListAllowlistEntriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllowlistEntriesRequest) Reset() {
	*x = ListAllowlistEntriesRequest{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllowlistEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllowlistEntriesRequest) ProtoMessage() {}

func (x *ListAllowlistEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllowlistEntriesRequest.ProtoReflect.Descriptor instead.
func (*ListAllowlistEntriesRequest) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{20}
}

type ListAllowlistEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*AllowlistEntry      `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllowlistEntriesResponse) Reset() {
	*x = ListAllowlistEntriesResponse{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllowlistEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllowlistEntriesResponse) ProtoMessage() {}

func (x *ListAllowlistEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllowlistEntriesResponse.ProtoReflect.Descriptor instead.
func (*ListAllowlistEntriesResponse) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{21}
}

func (x *ListAllowlistEntriesResponse) GetEntries() []*AllowlistEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type AddAllowlistEntryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Empty for custom entries.
	IdeKey        string `protobuf:"bytes,1,opt,name=ide_key,json=ideKey,proto3" json:"ide_key,omitempty"`
	Label         string `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Pattern       string `protobuf:"bytes,3,opt,name=pattern,proto3" json:"pattern,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAllowlistEntryRequest) Reset() {
	*x = AddAllowlistEntryRequest{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAllowlistEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAllowlistEntryRequest) ProtoMessage() {}

func (x *AddAllowlistEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAllowlistEntryRequest.ProtoReflect.Descriptor instead.
func (*AddAllowlistEntryRequest) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{22}
}

func (x *AddAllowlistEntryRequest) GetIdeKey() string {
	if x != nil {
		return x.IdeKey
	}
	return ""
}

func (x *AddAllowlistEntryRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *AddAllowlistEntryRequest) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

type AddAllowlistEntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *AllowlistEntry        `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAllowlistEntryResponse) Reset() {
	*x = AddAllowlistEntryResponse{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAllowlistEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAllowlistEntryResponse) ProtoMessage() {}

func (x *AddAllowlistEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAllowlistEntryResponse.ProtoReflect.Descriptor instead.
func (*AddAllowlistEntryResponse) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{23}
}

func (x *AddAllowlistEntryResponse) GetEntry() *AllowlistEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type UpdateAllowlistEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicId      string                 `protobuf:"bytes,1,opt,name=public_id,json=publicId,proto3" json:"public_id,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Pattern       string                 `protobuf:"bytes,3,opt,name=pattern,proto3" json:"pattern,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAllowlistEntryRequest) Reset() {
	*x = UpdateAllowlistEntryRequest{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAllowlistEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAllowlistEntryRequest) ProtoMessage() {}

func (x *UpdateAllowlistEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAllowlistEntryRequest.ProtoReflect.Descriptor instead.
func (*UpdateAllowlistEntryRequest) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateAllowlistEntryRequest) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

func (x *UpdateAllowlistEntryRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *UpdateAllowlistEntryRequest) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

type UpdateAllowlistEntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *AllowlistEntry        `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAllowlistEntryResponse) Reset() {
	*x = UpdateAllowlistEntryResponse{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAllowlistEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAllowlistEntryResponse) ProtoMessage() {}

func (x *UpdateAllowlistEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAllowlistEntryResponse.ProtoReflect.Descriptor instead.
func (*UpdateAllowlistEntryResponse) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{25}
}

func (x *UpdateAllowlistEntryResponse) GetEntry() *AllowlistEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type RemoveAllowlistEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicId      string                 `protobuf:"bytes,1,opt,name=public_id,json=publicId,proto3" json:"public_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveAllowlistEntryRequest) Reset() {
	*x = RemoveAllowlistEntryRequest{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAllowlistEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAllowlistEntryRequest) ProtoMessage() {}

func (x *RemoveAllowlistEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAllowlistEntryRequest.ProtoReflect.Descriptor instead.
func (*RemoveAllowlistEntryRequest) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{26}
}

func (x *RemoveAllowlistEntryRequest) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

type RemoveAllowlistEntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveAllowlistEntryResponse) Reset() {
	*x = RemoveAllowlistEntryResponse{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAllowlistEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAllowlistEntryResponse) ProtoMessage() {}

func (x *RemoveAllowlistEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAllowlistEntryResponse.ProtoReflect.Descriptor instead.
func (*RemoveAllowlistEntryResponse) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{27}
}

type ApplyIDEPresetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdeKey        string                 `protobuf:"bytes,1,opt,name=ide_key,json=ideKey,proto3" json:"ide_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyIDEPresetRequest) Reset() {
	*x = ApplyIDEPresetRequest{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyIDEPresetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyIDEPresetRequest) ProtoMessage() {}

func (x *ApplyIDEPresetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyIDEPresetRequest.ProtoReflect.Descriptor instead.
func (*ApplyIDEPresetRequest) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{28}
}

func (x *ApplyIDEPresetRequest) GetIdeKey() string {
	if x != nil {
		return x.IdeKey
	}
	return ""
}

type ApplyIDEPresetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Rows freshly inserted by this call.
	Added int32 `protobuf:"varint,1,opt,name=added,proto3" json:"added,omitempty"`
	// Rows already present (idempotent re-apply).
	AlreadyPresent int32 `protobuf:"varint,2,opt,name=already_present,json=alreadyPresent,proto3" json:"already_present,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ApplyIDEPresetResponse) Reset() {
	*x = ApplyIDEPresetResponse{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyIDEPresetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyIDEPresetResponse) ProtoMessage() {}

func (x *ApplyIDEPresetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyIDEPresetResponse.ProtoReflect.Descriptor instead.
func (*ApplyIDEPresetResponse) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{29}
}

func (x *ApplyIDEPresetResponse) GetAdded() int32 {
	if x != nil {
		return x.Added
	}
	return 0
}

func (x *ApplyIDEPresetResponse) GetAlreadyPresent() int32 {
	if x != nil {
		return x.AlreadyPresent
	}
	return 0
}

type RemoveIDEPresetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdeKey        string                 `protobuf:"bytes,1,opt,name=ide_key,json=ideKey,proto3" json:"ide_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveIDEPresetRequest) Reset() {
	*x = RemoveIDEPresetRequest{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveIDEPresetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveIDEPresetRequest) ProtoMessage() {}

func (x *RemoveIDEPresetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveIDEPresetRequest.ProtoReflect.Descriptor instead.
func (*RemoveIDEPresetRequest) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{30}
}

func (x *RemoveIDEPresetRequest) GetIdeKey() string {
	if x != nil {
		return x.IdeKey
	}
	return ""
}

type RemoveIDEPresetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Removed       int32                  `protobuf:"varint,1,opt,name=removed,proto3" json:"removed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveIDEPresetResponse) Reset() {
	*x = RemoveIDEPresetResponse{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveIDEPresetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveIDEPresetResponse) ProtoMessage() {}

func (x *RemoveIDEPresetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveIDEPresetResponse.ProtoReflect.Descriptor instead.
func (*RemoveIDEPresetResponse) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{31}
}

func (x *RemoveIDEPresetResponse) GetRemoved() int32 {
	if x != nil {
		return x.Removed
	}
	return 0
}

type MarkIDEChoiceSkippedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkIDEChoiceSkippedRequest) Reset() {
	*x = MarkIDEChoiceSkippedRequest{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkIDEChoiceSkippedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkIDEChoiceSkippedRequest) ProtoMessage() {}

func (x *MarkIDEChoiceSkippedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkIDEChoiceSkippedRequest.ProtoReflect.Descriptor instead.
func (*MarkIDEChoiceSkippedRequest) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{32}
}

type MarkIDEChoiceSkippedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      *TenantSettings        `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkIDEChoiceSkippedResponse) Reset() {
	*x = MarkIDEChoiceSkippedResponse{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkIDEChoiceSkippedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkIDEChoiceSkippedResponse) ProtoMessage() {}

func (x *MarkIDEChoiceSkippedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkIDEChoiceSkippedResponse.ProtoReflect.Descriptor instead.
func (*MarkIDEChoiceSkippedResponse) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{33}
}

func (x *MarkIDEChoiceSkippedResponse) GetSettings() *TenantSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type DeleteTenantRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Typed confirmation: caller must send the tenant's PublicID
	// verbatim. Mismatches reject with invalid_argument.
	PublicIdConfirmation string `protobuf:"bytes,1,opt,name=public_id_confirmation,json=publicIdConfirmation,proto3" json:"public_id_confirmation,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DeleteTenantRequest) Reset() {
	*x = DeleteTenantRequest{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTenantRequest) ProtoMessage() {}

func (x *DeleteTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTenantRequest.ProtoReflect.Descriptor instead.
func (*DeleteTenantRequest) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{34}
}

func (x *DeleteTenantRequest) GetPublicIdConfirmation() string {
	if x != nil {
		return x.PublicIdConfirmation
	}
	return ""
}

type DeleteTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTenantResponse) Reset() {
	*x = DeleteTenantResponse{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTenantResponse) ProtoMessage() {}

func (x *DeleteTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTenantResponse.ProtoReflect.Descriptor instead.
func (*DeleteTenantResponse) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{35}
}

type Member struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Zitadel user id.
	UserId      string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email       string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	DisplayName string `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// UNSPECIFIED when the user exists in the org but has no grant on
	// the Limen project (invited but not yet authorized — the row is
	// still surfaced so the admin can fix the missing grant).
	Role  MemberRole  `protobuf:"varint,4,opt,name=role,proto3,enum=limen.admin.v1.MemberRole" json:"role,omitempty"`
	State MemberState `protobuf:"varint,5,opt,name=state,proto3,enum=limen.admin.v1.MemberState" json:"state,omitempty"`
	// RFC3339; empty when Zitadel has no last-login record.
	LastLogin     string `protobuf:"bytes,6,opt,name=last_login,json=lastLogin,proto3" json:"last_login,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{36}
}

func (x *Member) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Member) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Member) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Member) GetRole() MemberRole {
	if x != nil {
		return x.Role
	}
	return MemberRole_MEMBER_ROLE_UNSPECIFIED
}

func (x *Member) GetState() MemberState {
	if x != nil {
		return x.State
	}
	return MemberState_MEMBER_STATE_UNSPECIFIED
}

func (x *Member) GetLastLogin() string {
	if x != nil {
		return x.LastLogin
	}
	return ""
}

type ListMembersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional substring; applied server-side as a Zitadel
	// DisplayNameQuery / EmailQuery OR. Empty returns everyone.
	Search string `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"`
	// UNSPECIFIED returns everyone regardless of role.
	RoleFilter    MemberRole `protobuf:"varint,2,opt,name=role_filter,json=roleFilter,proto3,enum=limen.admin.v1.MemberRole" json:"role_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersRequest) Reset() {
	*x = ListMembersRequest{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersRequest) ProtoMessage() {}

func (x *ListMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersRequest.ProtoReflect.Descriptor instead.
func (*ListMembersRequest) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{37}
}

func (x *ListMembersRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListMembersRequest) GetRoleFilter() MemberRole {
	if x != nil {
		return x.RoleFilter
	}
	return MemberRole_MEMBER_ROLE_UNSPECIFIED
}

type ListMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*Member              `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersResponse) Reset() {
	*x = ListMembersResponse{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersResponse) ProtoMessage() {}

func (x *ListMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersResponse.ProtoReflect.Descriptor instead.
func (*ListMembersResponse) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{38}
}

func (x *ListMembersResponse) GetMembers() []*Member {
	if x != nil {
		return x.Members
	}
	return nil
}

type InviteMemberRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Email      string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	GivenName  string                 `protobuf:"bytes,2,opt,name=given_name,json=givenName,proto3" json:"given_name,omitempty"`
	FamilyName string                 `protobuf:"bytes,3,opt,name=family_name,json=familyName,proto3" json:"family_name,omitempty"`
	// Required. UNSPECIFIED rejects with invalid_argument.
	Role          MemberRole `protobuf:"varint,4,opt,name=role,proto3,enum=limen.admin.v1.MemberRole" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteMemberRequest) Reset() {
	*x = InviteMemberRequest{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteMemberRequest) ProtoMessage() {}

func (x *InviteMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteMemberRequest.ProtoReflect.Descriptor instead.
func (*InviteMemberRequest) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{39}
}

func (x *InviteMemberRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *InviteMemberRequest) GetGivenName() string {
	if x != nil {
		return x.GivenName
	}
	return ""
}

func (x *InviteMemberRequest) GetFamilyName() string {
	if x != nil {
		return x.FamilyName
	}
	return ""
}

func (x *InviteMemberRequest) GetRole() MemberRole {
	if x != nil {
		return x.Role
	}
	return MemberRole_MEMBER_ROLE_UNSPECIFIED
}

type InviteMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        *Member                `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteMemberResponse) Reset() {
	*x = InviteMemberResponse{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteMemberResponse) ProtoMessage() {}

func (x *InviteMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteMemberResponse.ProtoReflect.Descriptor instead.
func (*InviteMemberResponse) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{40}
}

func (x *InviteMemberResponse) GetMember() *Member {
	if x != nil {
		return x.Member
	}
	return nil
}

type UpdateMemberRoleRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	UserId string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Required. UNSPECIFIED rejects with invalid_argument.
	Role          MemberRole `protobuf:"varint,2,opt,name=role,proto3,enum=limen.admin.v1.MemberRole" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMemberRoleRequest) Reset() {
	*x = UpdateMemberRoleRequest{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMemberRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMemberRoleRequest) ProtoMessage() {}

func (x *UpdateMemberRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMemberRoleRequest.ProtoReflect.Descriptor instead.
func (*UpdateMemberRoleRequest) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{41}
}

func (x *UpdateMemberRoleRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateMemberRoleRequest) GetRole() MemberRole {
	if x != nil {
		return x.Role
	}
	return MemberRole_MEMBER_ROLE_UNSPECIFIED
}

type UpdateMemberRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        *Member                `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMemberRoleResponse) Reset() {
	*x = UpdateMemberRoleResponse{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMemberRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMemberRoleResponse) ProtoMessage() {}

func (x *UpdateMemberRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMemberRoleResponse.ProtoReflect.Descriptor instead.
func (*UpdateMemberRoleResponse) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{42}
}

func (x *UpdateMemberRoleResponse) GetMember() *Member {
	if x != nil {
		return x.Member
	}
	return nil
}

type RemoveMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMemberRequest) Reset() {
	*x = RemoveMemberRequest{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMemberRequest) ProtoMessage() {}

func (x *RemoveMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMemberRequest.ProtoReflect.Descriptor instead.
func (*RemoveMemberRequest) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{43}
}

func (x *RemoveMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RemoveMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMemberResponse) Reset() {
	*x = RemoveMemberResponse{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMemberResponse) ProtoMessage() {}

func (x *RemoveMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMemberResponse.ProtoReflect.Descriptor instead.
func (*RemoveMemberResponse) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{44}
}

var File_limen_admin_v1_admin_proto protoreflect.FileDescriptor

const file_limen_admin_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x1alimen/admin/v1/admin.proto\x12\x0elimen.admin.v1\x1a\x1climen/portal/v1/portal.proto\"W\n" +
	"\x13OAuthClientOverride\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12#\n" +
	"\rclient_secret\x18\x02 \x01(\tR\fclientSecret\"\xe9\x03\n" +
	"\x15CreateUpstreamRequest\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x17\n" +
	"\amcp_url\x18\x03 \x01(\tR\x06mcpUrl\x12#\n" +
	"\rstrategy_type\x18\x04 \x01(\tR\fstrategyType\x12*\n" +
	"\x11strategy_sub_mode\x18\x05 \x01(\tR\x0fstrategySubMode\x12b\n" +
	"\x0fstrategy_config\x18\x06 \x03(\v29.limen.admin.v1.CreateUpstreamRequest.StrategyConfigEntryR\x0estrategyConfig\x12W\n" +
	"\x15oauth_client_override\x18\a \x01(\v2#.limen.admin.v1.OAuthClientOverrideR\x13oauthClientOverride\x12#\n" +
	"\rdefaults_json\x18\b \x01(\tR\fdefaultsJson\x1aA\n" +
	"\x13StrategyConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa7\x01\n" +
	"\x16CreateUpstreamResponse\x12<\n" +
	"\bupstream\x18\x01 \x01(\v2 .limen.portal.v1.UpstreamSummaryR\bupstream\x12.\n" +
	"\x13requires_admin_link\x18\x02 \x01(\bR\x11requiresAdminLink\x12\x1f\n" +
	"\vconnect_url\x18\x03 \x01(\tR\n" +
	"connectUrl\"|\n" +
	"\x15UpdateUpstreamRequest\x12\x1b\n" +
	"\tpublic_id\x18\x01 \x01(\tR\bpublicId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12#\n" +
	"\rdefaults_json\x18\x03 \x01(\tR\fdefaultsJson\"V\n" +
	"\x16UpdateUpstreamResponse\x12<\n" +
	"\bupstream\x18\x01 \x01(\v2 .limen.portal.v1.UpstreamSummaryR\bupstream\"4\n" +
	"\x15DeleteUpstreamRequest\x12\x1b\n" +
	"\tpublic_id\x18\x01 \x01(\tR\bpublicId\"\x18\n" +
	"\x16DeleteUpstreamResponse\"<\n" +
	"\x1dReindexUpstreamCatalogRequest\x12\x1b\n" +
	"\tpublic_id\x18\x01 \x01(\tR\bpublicId\"^\n" +
	"\x1eReindexUpstreamCatalogResponse\x12<\n" +
	"\bupstream\x18\x01 \x01(\v2 .limen.portal.v1.UpstreamSummaryR\bupstream\"U\n" +
	"\x1dPreviewUpstreamContextRequest\x12\x1b\n" +
	"\tpublic_id\x18\x01 \x01(\tR\bpublicId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"A\n" +
	"\x1ePreviewUpstreamContextResponse\x12\x1f\n" +
	"\vmerged_json\x18\x01 \x01(\tR\n" +
	"mergedJson\"\x1a\n" +
	"\x18GetTenantSettingsRequest\"\xe4\x01\n" +
	"\x19GetTenantSettingsResponse\x12:\n" +
	"\bsettings\x18\x01 \x01(\v2\x1e.limen.admin.v1.TenantSettingsR\bsettings\x12$\n" +
	"\x0ezitadel_org_id\x18\x02 \x01(\tR\fzitadelOrgId\x12,\n" +
	"\x12zitadel_project_id\x18\x03 \x01(\tR\x10zitadelProjectId\x127\n" +
	"\x18zitadel_project_grant_id\x18\x04 \x01(\tR\x15zitadelProjectGrantId\"\x8c\x01\n" +
	"\x1bUpdateTenantSettingsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12-\n" +
	"\x13invited_team_at_now\x18\x02 \x01(\bR\x10invitedTeamAtNow\x12*\n" +
	"\x11configured_at_now\x18\x03 \x01(\bR\x0fconfiguredAtNow\"\xb0\x01\n" +
	"\x0eTenantSettings\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tpublic_id\x18\x02 \x01(\tR\bpublicId\x12&\n" +
	"\x0finvited_team_at\x18\x03 \x01(\tR\rinvitedTeamAt\x12#\n" +
	"\rconfigured_at\x18\x04 \x01(\tR\fconfiguredAt\x12 \n" +
	"\fchose_ide_at\x18\x05 \x01(\tR\n" +
	"choseIdeAt\"Z\n" +
	"\x1cUpdateTenantSettingsResponse\x12:\n" +
	"\bsettings\x18\x01 \x01(\v2\x1e.limen.admin.v1.TenantSettingsR\bsettings\"\x8f\x01\n" +
	"\tIDEPreset\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\x12\x1a\n" +
	"\bpatterns\x18\x04 \x03(\tR\bpatterns\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x05 \x01(\x05R\tsortOrder\"\x95\x01\n" +
	"\x0eAllowlistEntry\x12\x1b\n" +
	"\tpublic_id\x18\x01 \x01(\tR\bpublicId\x12\x17\n" +
	"\aide_key\x18\x02 \x01(\tR\x06ideKey\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\x12\x18\n" +
	"\apattern\x18\x04 \x01(\tR\apattern\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"\x17\n" +
	"\x15ListIDEPresetsRequest\"M\n" +
	"\x16ListIDEPresetsResponse\x123\n" +
	"\apresets\x18\x01 \x03(\v2\x19.limen.admin.v1.IDEPresetR\apresets\"\x1d\n" +
	"\x1bListAllowlistEntriesRequest\"X\n" +
	"\x1cListAllowlistEntriesResponse\x128\n" +
	"\aentries\x18\x01 \x03(\v2\x1e.limen.admin.v1.AllowlistEntryR\aentries\"c\n" +
	"\x18AddAllowlistEntryRequest\x12\x17\n" +
	"\aide_key\x18\x01 \x01(\tR\x06ideKey\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x18\n" +
	"\apattern\x18\x03 \x01(\tR\apattern\"Q\n" +
	"\x19AddAllowlistEntryResponse\x124\n" +
	"\x05entry\x18\x01 \x01(\v2\x1e.limen.admin.v1.AllowlistEntryR\x05entry\"j\n" +
	"\x1bUpdateAllowlistEntryRequest\x12\x1b\n" +
	"\tpublic_id\x18\x01 \x01(\tR\bpublicId\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x18\n" +
	"\apattern\x18\x03 \x01(\tR\apattern\"T\n" +
	"\x1cUpdateAllowlistEntryResponse\x124\n" +
	"\x05entry\x18\x01 \x01(\v2\x1e.limen.admin.v1.AllowlistEntryR\x05entry\":\n" +
	"\x1bRemoveAllowlistEntryRequest\x12\x1b\n" +
	"\tpublic_id\x18\x01 \x01(\tR\bpublicId\"\x1e\n" +
	"\x1cRemoveAllowlistEntryResponse\"0\n" +
	"\x15ApplyIDEPresetRequest\x12\x17\n" +
	"\aide_key\x18\x01 \x01(\tR\x06ideKey\"W\n" +
	"\x16ApplyIDEPresetResponse\x12\x14\n" +
	"\x05added\x18\x01 \x01(\x05R\x05added\x12'\n" +
	"\x0falready_present\x18\x02 \x01(\x05R\x0ealreadyPresent\"1\n" +
	"\x16RemoveIDEPresetRequest\x12\x17\n" +
	"\aide_key\x18\x01 \x01(\tR\x06ideKey\"3\n" +
	"\x17RemoveIDEPresetResponse\x12\x18\n" +
	"\aremoved\x18\x01 \x01(\x05R\aremoved\"\x1d\n" +
	"\x1bMarkIDEChoiceSkippedRequest\"Z\n" +
	"\x1cMarkIDEChoiceSkippedResponse\x12:\n" +
	"\bsettings\x18\x01 \x01(\v2\x1e.limen.admin.v1.TenantSettingsR\bsettings\"K\n" +
	"\x13DeleteTenantRequest\x124\n" +
	"\x16public_id_confirmation\x18\x01 \x01(\tR\x14publicIdConfirmation\"\x16\n" +
	"\x14DeleteTenantResponse\"\xdc\x01\n" +
	"\x06Member\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12.\n" +
	"\x04role\x18\x04 \x01(\x0e2\x1a.limen.admin.v1.MemberRoleR\x04role\x121\n" +
	"\x05state\x18\x05 \x01(\x0e2\x1b.limen.admin.v1.MemberStateR\x05state\x12\x1d\n" +
	"\n" +
	"last_login\x18\x06 \x01(\tR\tlastLogin\"i\n" +
	"\x12ListMembersRequest\x12\x16\n" +
	"\x06search\x18\x01 \x01(\tR\x06search\x12;\n" +
	"\vrole_filter\x18\x02 \x01(\x0e2\x1a.limen.admin.v1.MemberRoleR\n" +
	"roleFilter\"G\n" +
	"\x13ListMembersResponse\x120\n" +
	"\amembers\x18\x01 \x03(\v2\x16.limen.admin.v1.MemberR\amembers\"\x9b\x01\n" +
	"\x13InviteMemberRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"given_name\x18\x02 \x01(\tR\tgivenName\x12\x1f\n" +
	"\vfamily_name\x18\x03 \x01(\tR\n" +
	"familyName\x12.\n" +
	"\x04role\x18\x04 \x01(\x0e2\x1a.limen.admin.v1.MemberRoleR\x04role\"F\n" +
	"\x14InviteMemberResponse\x12.\n" +
	"\x06member\x18\x01 \x01(\v2\x16.limen.admin.v1.MemberR\x06member\"b\n" +
	"\x17UpdateMemberRoleRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12.\n" +
	"\x04role\x18\x02 \x01(\x0e2\x1a.limen.admin.v1.MemberRoleR\x04role\"J\n" +
	"\x18UpdateMemberRoleResponse\x12.\n" +
	"\x06member\x18\x01 \x01(\v2\x16.limen.admin.v1.MemberR\x06member\".\n" +
	"\x13RemoveMemberRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x16\n" +
	"\x14RemoveMemberResponse*o\n" +
	"\n" +
	"MemberRole\x12\x1b\n" +
	"\x17MEMBER_ROLE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12MEMBER_ROLE_MEMBER\x10\x01\x12\x15\n" +
	"\x11MEMBER_ROLE_ADMIN\x10\x02\x12\x15\n" +
	"\x11MEMBER_ROLE_OWNER\x10\x03*\x92\x01\n" +
	"\vMemberState\x12\x1c\n" +
	"\x18MEMBER_STATE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13MEMBER_STATE_ACTIVE\x10\x01\x12\x19\n" +
	"\x15MEMBER_STATE_INACTIVE\x10\x02\x12\x17\n" +
	"\x13MEMBER_STATE_LOCKED\x10\x03\x12\x18\n" +
	"\x14MEMBER_STATE_INITIAL\x10\x042\xac\x10\n" +
	"\fAdminService\x12_\n" +
	"\x0eCreateUpstream\x12%.limen.admin.v1.CreateUpstreamRequest\x1a&.limen.admin.v1.CreateUpstreamResponse\x12_\n" +
	"\x0eUpdateUpstream\x12%.limen.admin.v1.UpdateUpstreamRequest\x1a&.limen.admin.v1.UpdateUpstreamResponse\x12_\n" +
	"\x0eDeleteUpstream\x12%.limen.admin.v1.DeleteUpstreamRequest\x1a&.limen.admin.v1.DeleteUpstreamResponse\x12w\n" +
	"\x16ReindexUpstreamCatalog\x12-.limen.admin.v1.ReindexUpstreamCatalogRequest\x1a..limen.admin.v1.ReindexUpstreamCatalogResponse\x12w\n" +
	"\x16PreviewUpstreamContext\x12-.limen.admin.v1.PreviewUpstreamContextRequest\x1a..limen.admin.v1.PreviewUpstreamContextResponse\x12h\n" +
	"\x11GetTenantSettings\x12(.limen.admin.v1.GetTenantSettingsRequest\x1a).limen.admin.v1.GetTenantSettingsResponse\x12q\n" +
	"\x14UpdateTenantSettings\x12+.limen.admin.v1.UpdateTenantSettingsRequest\x1a,.limen.admin.v1.UpdateTenantSettingsResponse\x12_\n" +
	"\x0eListIDEPresets\x12%.limen.admin.v1.ListIDEPresetsRequest\x1a&.limen.admin.v1.ListIDEPresetsResponse\x12q\n" +
	"\x14ListAllowlistEntries\x12+.limen.admin.v1.ListAllowlistEntriesRequest\x1a,.limen.admin.v1.ListAllowlistEntriesResponse\x12h\n" +
	"\x11AddAllowlistEntry\x12(.limen.admin.v1.AddAllowlistEntryRequest\x1a).limen.admin.v1.AddAllowlistEntryResponse\x12q\n" +
	"\x14UpdateAllowlistEntry\x12+.limen.admin.v1.UpdateAllowlistEntryRequest\x1a,.limen.admin.v1.UpdateAllowlistEntryResponse\x12q\n" +
	"\x14RemoveAllowlistEntry\x12+.limen.admin.v1.RemoveAllowlistEntryRequest\x1a,.limen.admin.v1.RemoveAllowlistEntryResponse\x12_\n" +
	"\x0eApplyIDEPreset\x12%.limen.admin.v1.ApplyIDEPresetRequest\x1a&.limen.admin.v1.ApplyIDEPresetResponse\x12b\n" +
	"\x0fRemoveIDEPreset\x12&.limen.admin.v1.RemoveIDEPresetRequest\x1a'.limen.admin.v1.RemoveIDEPresetResponse\x12q\n" +
	"\x14MarkIDEChoiceSkipped\x12+.limen.admin.v1.MarkIDEChoiceSkippedRequest\x1a,.limen.admin.v1.MarkIDEChoiceSkippedResponse\x12Y\n" +
	"\fDeleteTenant\x12#.limen.admin.v1.DeleteTenantRequest\x1a$.limen.admin.v1.DeleteTenantResponse\x12V\n" +
	"\vListMembers\x12\".limen.admin.v1.ListMembersRequest\x1a#.limen.admin.v1.ListMembersResponse\x12Y\n" +
	"\fInviteMember\x12#.limen.admin.v1.InviteMemberRequest\x1a$.limen.admin.v1.InviteMemberResponse\x12e\n" +
	"\x10UpdateMemberRole\x12'.limen.admin.v1.UpdateMemberRoleRequest\x1a(.limen.admin.v1.UpdateMemberRoleResponse\x12Y\n" +
	"\fRemoveMember\x12#.limen.admin.v1.RemoveMemberRequest\x1a$.limen.admin.v1.RemoveMemberResponseB;Z9github.com/belphemur/limen/internal/admin/adminv1;adminv1b\x06proto3"

var (
	file_limen_admin_v1_admin_proto_rawDescOnce sync.Once
	file_limen_admin_v1_admin_proto_rawDescData []byte
)

func file_limen_admin_v1_admin_proto_rawDescGZIP() []byte {
	file_limen_admin_v1_admin_proto_rawDescOnce.Do(func() {
		file_limen_admin_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_limen_admin_v1_admin_proto_rawDesc), len(file_limen_admin_v1_admin_proto_rawDesc)))
	})
	return file_limen_admin_v1_admin_proto_rawDescData
}

var file_limen_admin_v1_admin_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_limen_admin_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 46)
var file_limen_admin_v1_admin_proto_goTypes = []any{
	(MemberRole)(0),                        // 0: limen.admin.v1.MemberRole
	(MemberState)(0),                       // 1: limen.admin.v1.MemberState
	(*OAuthClientOverride)(nil),            // 2: limen.admin.v1.OAuthClientOverride
	(*CreateUpstreamRequest)(nil),          // 3: limen.admin.v1.CreateUpstreamRequest
	(*CreateUpstreamResponse)(nil),         // 4: limen.admin.v1.CreateUpstreamResponse
	(*UpdateUpstreamRequest)(nil),          // 5: limen.admin.v1.UpdateUpstreamRequest
	(*UpdateUpstreamResponse)(nil),         // 6: limen.admin.v1.UpdateUpstreamResponse
	(*DeleteUpstreamRequest)(nil),          // 7: limen.admin.v1.DeleteUpstreamRequest
	(*DeleteUpstreamResponse)(nil),         // 8: limen.admin.v1.DeleteUpstreamResponse
	(*ReindexUpstreamCatalogRequest)(nil),  // 9: limen.admin.v1.ReindexUpstreamCatalogRequest
	(*ReindexUpstreamCatalogResponse)(nil), // 10: limen.admin.v1.ReindexUpstreamCatalogResponse
	(*PreviewUpstreamContextRequest)(nil),  // 11: limen.admin.v1.PreviewUpstreamContextRequest
	(*PreviewUpstreamContextResponse)(nil), // 12: limen.admin.v1.PreviewUpstreamContextResponse
	(*GetTenantSettingsRequest)(nil),       // 13: limen.admin.v1.GetTenantSettingsRequest
	(*GetTenantSettingsResponse)(nil),      // 14: limen.admin.v1.GetTenantSettingsResponse
	(*UpdateTenantSettingsRequest)(nil),    // 15: limen.admin.v1.UpdateTenantSettingsRequest
	(*TenantSettings)(nil),                 // 16: limen.admin.v1.TenantSettings
	(*UpdateTenantSettingsResponse)(nil),   // 17: limen.admin.v1.UpdateTenantSettingsResponse
	(*IDEPreset)(nil),                      // 18: limen.admin.v1.IDEPreset
	(*AllowlistEntry)(nil),                 // 19: limen.admin.v1.AllowlistEntry
	(*ListIDEPresetsRequest)(nil),          // 20: limen.admin.v1.ListIDEPresetsRequest
	(*ListIDEPresetsResponse)(nil),         // 21: limen.admin.v1.ListIDEPresetsResponse
	(*ListAllowlistEntriesRequest)(nil),    // 22: limen.admin.v1.ListAllowlistEntriesRequest
	(*ListAllowlistEntriesResponse)(nil),   // 23: limen.admin.v1.ListAllowlistEntriesResponse
	(*AddAllowlistEntryRequest)(nil),       // 24: limen.admin.v1.AddAllowlistEntryRequest
	(*AddAllowlistEntryResponse)(nil),      // 25: limen.admin.v1.AddAllowlistEntryResponse
	(*UpdateAllowlistEntryRequest)(nil),    // 26: limen.admin.v1.UpdateAllowlistEntryRequest
	(*UpdateAllowlistEntryResponse)(nil),   // 27: limen.admin.v1.UpdateAllowlistEntryResponse
	(*RemoveAllowlistEntryRequest)(nil),    // 28: limen.admin.v1.RemoveAllowlistEntryRequest
	(*RemoveAllowlistEntryResponse)(nil),   // 29: limen.admin.v1.RemoveAllowlistEntryResponse
	(*ApplyIDEPresetRequest)(nil),          // 30: limen.admin.v1.ApplyIDEPresetRequest
	(*ApplyIDEPresetResponse)(nil),         // 31: limen.admin.v1.ApplyIDEPresetResponse
	(*RemoveIDEPresetRequest)(nil),         // 32: limen.admin.v1.RemoveIDEPresetRequest
	(*RemoveIDEPresetResponse)(nil),        // 33: limen.admin.v1.RemoveIDEPresetResponse
	(*MarkIDEChoiceSkippedRequest)(nil),    // 34: limen.admin.v1.MarkIDEChoiceSkippedRequest
	(*MarkIDEChoiceSkippedResponse)(nil),   // 35: limen.admin.v1.MarkIDEChoiceSkippedResponse
	(*DeleteTenantRequest)(nil),            // 36: limen.admin.v1.DeleteTenantRequest
	(*DeleteTenantResponse)(nil),           // 37: limen.admin.v1.DeleteTenantResponse
	(*Member)(nil),                         // 38: limen.admin.v1.Member
	(*ListMembersRequest)(nil),             // 39: limen.admin.v1.ListMembersRequest
	(*ListMembersResponse)(nil),            // 40: limen.admin.v1.ListMembersResponse
	(*InviteMemberRequest)(nil),            // 41: limen.admin.v1.InviteMemberRequest
	(*InviteMemberResponse)(nil),           // 42: limen.admin.v1.InviteMemberResponse
	(*UpdateMemberRoleRequest)(nil),        // 43: limen.admin.v1.UpdateMemberRoleRequest
	(*UpdateMemberRoleResponse)(nil),       // 44: limen.admin.v1.UpdateMemberRoleResponse
	(*RemoveMemberRequest)(nil),            // 45: limen.admin.v1.RemoveMemberRequest
	(*RemoveMemberResponse)(nil),           // 46: limen.admin.v1.RemoveMemberResponse
	nil,                                    // 47: limen.admin.v1.CreateUpstreamRequest.StrategyConfigEntry
	(*portalv1.UpstreamSummary)(nil),       // 48: limen.portal.v1.UpstreamSummary
}
var file_limen_admin_v1_admin_proto_depIdxs = []int32{
	47, // 0: limen.admin.v1.CreateUpstreamRequest.strategy_config:type_name -> limen.admin.v1.CreateUpstreamRequest.StrategyConfigEntry
	2,  // 1: limen.admin.v1.CreateUpstreamRequest.oauth_client_override:type_name -> limen.admin.v1.OAuthClientOverride
	48, // 2: limen.admin.v1.CreateUpstreamResponse.upstream:type_name -> limen.portal.v1.UpstreamSummary
	48, // 3: limen.admin.v1.UpdateUpstreamResponse.upstream:type_name -> limen.portal.v1.UpstreamSummary
	48, // 4: limen.admin.v1.ReindexUpstreamCatalogResponse.upstream:type_name -> limen.portal.v1.UpstreamSummary
	16, // 5: limen.admin.v1.GetTenantSettingsResponse.settings:type_name -> limen.admin.v1.TenantSettings
	16, // 6: limen.admin.v1.UpdateTenantSettingsResponse.settings:type_name -> limen.admin.v1.TenantSettings
	18, // 7: limen.admin.v1.ListIDEPresetsResponse.presets:type_name -> limen.admin.v1.IDEPreset
	19, // 8: limen.admin.v1.ListAllowlistEntriesResponse.entries:type_name -> limen.admin.v1.AllowlistEntry
	19, // 9: limen.admin.v1.AddAllowlistEntryResponse.entry:type_name -> limen.admin.v1.AllowlistEntry
	19, // 10: limen.admin.v1.UpdateAllowlistEntryResponse.entry:type_name -> limen.admin.v1.AllowlistEntry
	16, // 11: limen.admin.v1.MarkIDEChoiceSkippedResponse.settings:type_name -> limen.admin.v1.TenantSettings
	0,  // 12: limen.admin.v1.Member.role:type_name -> limen.admin.v1.MemberRole
	1,  // 13: limen.admin.v1.Member.state:type_name -> limen.admin.v1.MemberState
	0,  // 14: limen.admin.v1.ListMembersRequest.role_filter:type_name -> limen.admin.v1.MemberRole
	38, // 15: limen.admin.v1.ListMembersResponse.members:type_name -> limen.admin.v1.Member
	0,  // 16: limen.admin.v1.InviteMemberRequest.role:type_name -> limen.admin.v1.MemberRole
	38, // 17: limen.admin.v1.InviteMemberResponse.member:type_name -> limen.admin.v1.Member
	0,  // 18: limen.admin.v1.UpdateMemberRoleRequest.role:type_name -> limen.admin.v1.MemberRole
	38, // 19: limen.admin.v1.UpdateMemberRoleResponse.member:type_name -> limen.admin.v1.Member
	3,  // 20: limen.admin.v1.AdminService.CreateUpstream:input_type -> limen.admin.v1.CreateUpstreamRequest
	5,  // 21: limen.admin.v1.AdminService.UpdateUpstream:input_type -> limen.admin.v1.UpdateUpstreamRequest
	7,  // 22: limen.admin.v1.AdminService.DeleteUpstream:input_type -> limen.admin.v1.DeleteUpstreamRequest
	9,  // 23: limen.admin.v1.AdminService.ReindexUpstreamCatalog:input_type -> limen.admin.v1.ReindexUpstreamCatalogRequest
	11, // 24: limen.admin.v1.AdminService.PreviewUpstreamContext:input_type -> limen.admin.v1.PreviewUpstreamContextRequest
	13, // 25: limen.admin.v1.AdminService.GetTenantSettings:input_type -> limen.admin.v1.GetTenantSettingsRequest
	15, // 26: limen.admin.v1.AdminService.UpdateTenantSettings:input_type -> limen.admin.v1.UpdateTenantSettingsRequest
	20, // 27: limen.admin.v1.AdminService.ListIDEPresets:input_type -> limen.admin.v1.ListIDEPresetsRequest
	22, // 28: limen.admin.v1.AdminService.ListAllowlistEntries:input_type -> limen.admin.v1.ListAllowlistEntriesRequest
	24, // 29: limen.admin.v1.AdminService.AddAllowlistEntry:input_type -> limen.admin.v1.AddAllowlistEntryRequest
	26, // 30: limen.admin.v1.AdminService.UpdateAllowlistEntry:input_type -> limen.admin.v1.UpdateAllowlistEntryRequest
	28, // 31: limen.admin.v1.AdminService.RemoveAllowlistEntry:input_type -> limen.admin.v1.RemoveAllowlistEntryRequest
	30, // 32: limen.admin.v1.AdminService.ApplyIDEPreset:input_type -> limen.admin.v1.ApplyIDEPresetRequest
	32, // 33: limen.admin.v1.AdminService.RemoveIDEPreset:input_type -> limen.admin.v1.RemoveIDEPresetRequest
	34, // 34: limen.admin.v1.AdminService.MarkIDEChoiceSkipped:input_type -> limen.admin.v1.MarkIDEChoiceSkippedRequest
	36, // 35: limen.admin.v1.AdminService.DeleteTenant:input_type -> limen.admin.v1.DeleteTenantRequest
	39, // 36: limen.admin.v1.AdminService.ListMembers:input_type -> limen.admin.v1.ListMembersRequest
	41, // 37: limen.admin.v1.AdminService.InviteMember:input_type -> limen.admin.v1.InviteMemberRequest
	43, // 38: limen.admin.v1.AdminService.UpdateMemberRole:input_type -> limen.admin.v1.UpdateMemberRoleRequest
	45, // 39: limen.admin.v1.AdminService.RemoveMember:input_type -> limen.admin.v1.RemoveMemberRequest
	4,  // 40: limen.admin.v1.AdminService.CreateUpstream:output_type -> limen.admin.v1.CreateUpstreamResponse
	6,  // 41: limen.admin.v1.AdminService.UpdateUpstream:output_type -> limen.admin.v1.UpdateUpstreamResponse
	8,  // 42: limen.admin.v1.AdminService.DeleteUpstream:output_type -> limen.admin.v1.DeleteUpstreamResponse
	10, // 43: limen.admin.v1.AdminService.ReindexUpstreamCatalog:output_type -> limen.admin.v1.ReindexUpstreamCatalogResponse
	12, // 44: limen.admin.v1.AdminService.PreviewUpstreamContext:output_type -> limen.admin.v1.PreviewUpstreamContextResponse
	14, // 45: limen.admin.v1.AdminService.GetTenantSettings:output_type -> limen.admin.v1.GetTenantSettingsResponse
	17, // 46: limen.admin.v1.AdminService.UpdateTenantSettings:output_type -> limen.admin.v1.UpdateTenantSettingsResponse
	21, // 47: limen.admin.v1.AdminService.ListIDEPresets:output_type -> limen.admin.v1.ListIDEPresetsResponse
	23, // 48: limen.admin.v1.AdminService.ListAllowlistEntries:output_type -> limen.admin.v1.ListAllowlistEntriesResponse
	25, // 49: limen.admin.v1.AdminService.AddAllowlistEntry:output_type -> limen.admin.v1.AddAllowlistEntryResponse
	27, // 50: limen.admin.v1.AdminService.UpdateAllowlistEntry:output_type -> limen.admin.v1.UpdateAllowlistEntryResponse
	29, // 51: limen.admin.v1.AdminService.RemoveAllowlistEntry:output_type -> limen.admin.v1.RemoveAllowlistEntryResponse
	31, // 52: limen.admin.v1.AdminService.ApplyIDEPreset:output_type -> limen.admin.v1.ApplyIDEPresetResponse
	33, // 53: limen.admin.v1.AdminService.RemoveIDEPreset:output_type -> limen.admin.v1.RemoveIDEPresetResponse
	35, // 54: limen.admin.v1.AdminService.MarkIDEChoiceSkipped:output_type -> limen.admin.v1.MarkIDEChoiceSkippedResponse
	37, // 55: limen.admin.v1.AdminService.DeleteTenant:output_type -> limen.admin.v1.DeleteTenantResponse
	40, // 56: limen.admin.v1.AdminService.ListMembers:output_type -> limen.admin.v1.ListMembersResponse
	42, // 57: limen.admin.v1.AdminService.InviteMember:output_type -> limen.admin.v1.InviteMemberResponse
	44, // 58: limen.admin.v1.AdminService.UpdateMemberRole:output_type -> limen.admin.v1.UpdateMemberRoleResponse
	46, // 59: limen.admin.v1.AdminService.RemoveMember:output_type -> limen.admin.v1.RemoveMemberResponse
	40, // [40:60] is the sub-list for method output_type
	20, // [20:40] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_limen_admin_v1_admin_proto_init() }
func file_limen_admin_v1_admin_proto_init() {
	if File_limen_admin_v1_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_limen_admin_v1_admin_proto_rawDesc), len(file_limen_admin_v1_admin_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   46,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_limen_admin_v1_admin_proto_goTypes,
		DependencyIndexes: file_limen_admin_v1_admin_proto_depIdxs,
		EnumInfos:         file_limen_admin_v1_admin_proto_enumTypes,
		MessageInfos:      file_limen_admin_v1_admin_proto_msgTypes,
	}.Build()
	File_limen_admin_v1_admin_proto = out.File
	file_limen_admin_v1_admin_proto_goTypes = nil
	file_limen_admin_v1_admin_proto_depIdxs = nil
}
