// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: limen/admin/v1/admin.proto

package adminv1

import (
	portalv1 "github.com/belphemur/limen/internal/portal/portalv1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OAuthClientOverride lets the admin pin a pre-registered upstream
// OAuth client (for mcp_spec ASes without DCR). Both fields are
// required when this message is present.
type OAuthClientOverride struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSecret  string                 `protobuf:"bytes,2,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OAuthClientOverride) Reset() {
	*x = OAuthClientOverride{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuthClientOverride) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuthClientOverride) ProtoMessage() {}

func (x *OAuthClientOverride) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuthClientOverride.ProtoReflect.Descriptor instead.
func (*OAuthClientOverride) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{0}
}

func (x *OAuthClientOverride) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *OAuthClientOverride) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

type CreateUpstreamRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Identifier   string                 `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	DisplayName  string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	McpUrl       string                 `protobuf:"bytes,3,opt,name=mcp_url,json=mcpUrl,proto3" json:"mcp_url,omitempty"`
	StrategyType string                 `protobuf:"bytes,4,opt,name=strategy_type,json=strategyType,proto3" json:"strategy_type,omitempty"`
	// e.g. "tenant" / "user" for static_header. Empty otherwise.
	StrategySubMode string `protobuf:"bytes,5,opt,name=strategy_sub_mode,json=strategySubMode,proto3" json:"strategy_sub_mode,omitempty"`
	// Strategy-specific static config (e.g. tenant-wide API key for
	// static_header tenant-mode).
	StrategyConfig map[string]string `protobuf:"bytes,6,rep,name=strategy_config,json=strategyConfig,proto3" json:"strategy_config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Optional pre-registered OAuth client for ASes without DCR.
	OauthClientOverride *OAuthClientOverride `protobuf:"bytes,7,opt,name=oauth_client_override,json=oauthClientOverride,proto3" json:"oauth_client_override,omitempty"`
	// JSON object serialised as a string; validated server-side via
	// gateway.validateContextBlob.
	DefaultsJson  string `protobuf:"bytes,8,opt,name=defaults_json,json=defaultsJson,proto3" json:"defaults_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUpstreamRequest) Reset() {
	*x = CreateUpstreamRequest{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUpstreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUpstreamRequest) ProtoMessage() {}

func (x *CreateUpstreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUpstreamRequest.ProtoReflect.Descriptor instead.
func (*CreateUpstreamRequest) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUpstreamRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *CreateUpstreamRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CreateUpstreamRequest) GetMcpUrl() string {
	if x != nil {
		return x.McpUrl
	}
	return ""
}

func (x *CreateUpstreamRequest) GetStrategyType() string {
	if x != nil {
		return x.StrategyType
	}
	return ""
}

func (x *CreateUpstreamRequest) GetStrategySubMode() string {
	if x != nil {
		return x.StrategySubMode
	}
	return ""
}

func (x *CreateUpstreamRequest) GetStrategyConfig() map[string]string {
	if x != nil {
		return x.StrategyConfig
	}
	return nil
}

func (x *CreateUpstreamRequest) GetOauthClientOverride() *OAuthClientOverride {
	if x != nil {
		return x.OauthClientOverride
	}
	return nil
}

func (x *CreateUpstreamRequest) GetDefaultsJson() string {
	if x != nil {
		return x.DefaultsJson
	}
	return ""
}

type CreateUpstreamResponse struct {
	state    protoimpl.MessageState    `protogen:"open.v1"`
	Upstream *portalv1.UpstreamSummary `protobuf:"bytes,1,opt,name=upstream,proto3" json:"upstream,omitempty"`
	// True when the strategy requires an owner/admin link before the
	// tool catalog can be populated (mcp_spec, static_header user-mode).
	RequiresAdminLink bool `protobuf:"varint,2,opt,name=requires_admin_link,json=requiresAdminLink,proto3" json:"requires_admin_link,omitempty"`
	// Absolute or SPA-relative URL the SPA should open to start the
	// admin-link flow. Empty when requires_admin_link is false.
	ConnectUrl    string `protobuf:"bytes,3,opt,name=connect_url,json=connectUrl,proto3" json:"connect_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUpstreamResponse) Reset() {
	*x = CreateUpstreamResponse{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUpstreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUpstreamResponse) ProtoMessage() {}

func (x *CreateUpstreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUpstreamResponse.ProtoReflect.Descriptor instead.
func (*CreateUpstreamResponse) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{2}
}

func (x *CreateUpstreamResponse) GetUpstream() *portalv1.UpstreamSummary {
	if x != nil {
		return x.Upstream
	}
	return nil
}

func (x *CreateUpstreamResponse) GetRequiresAdminLink() bool {
	if x != nil {
		return x.RequiresAdminLink
	}
	return false
}

func (x *CreateUpstreamResponse) GetConnectUrl() string {
	if x != nil {
		return x.ConnectUrl
	}
	return ""
}

type UpdateUpstreamRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	PublicId string                 `protobuf:"bytes,1,opt,name=public_id,json=publicId,proto3" json:"public_id,omitempty"`
	// Optional. Empty string clears the override; absent leaves it.
	// Use the wrapper-free convention: callers send empty strings to
	// mean "no change" — this matches the rest of PortalService.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Optional. Empty string is interpreted as "no change"; pass "{}"
	// to clear. Validated server-side.
	DefaultsJson  string `protobuf:"bytes,3,opt,name=defaults_json,json=defaultsJson,proto3" json:"defaults_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUpstreamRequest) Reset() {
	*x = UpdateUpstreamRequest{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUpstreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUpstreamRequest) ProtoMessage() {}

func (x *UpdateUpstreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUpstreamRequest.ProtoReflect.Descriptor instead.
func (*UpdateUpstreamRequest) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateUpstreamRequest) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

func (x *UpdateUpstreamRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *UpdateUpstreamRequest) GetDefaultsJson() string {
	if x != nil {
		return x.DefaultsJson
	}
	return ""
}

type UpdateUpstreamResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Upstream      *portalv1.UpstreamSummary `protobuf:"bytes,1,opt,name=upstream,proto3" json:"upstream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUpstreamResponse) Reset() {
	*x = UpdateUpstreamResponse{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUpstreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUpstreamResponse) ProtoMessage() {}

func (x *UpdateUpstreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUpstreamResponse.ProtoReflect.Descriptor instead.
func (*UpdateUpstreamResponse) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateUpstreamResponse) GetUpstream() *portalv1.UpstreamSummary {
	if x != nil {
		return x.Upstream
	}
	return nil
}

type DeleteUpstreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicId      string                 `protobuf:"bytes,1,opt,name=public_id,json=publicId,proto3" json:"public_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUpstreamRequest) Reset() {
	*x = DeleteUpstreamRequest{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUpstreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUpstreamRequest) ProtoMessage() {}

func (x *DeleteUpstreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUpstreamRequest.ProtoReflect.Descriptor instead.
func (*DeleteUpstreamRequest) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteUpstreamRequest) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

type DeleteUpstreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUpstreamResponse) Reset() {
	*x = DeleteUpstreamResponse{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUpstreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUpstreamResponse) ProtoMessage() {}

func (x *DeleteUpstreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUpstreamResponse.ProtoReflect.Descriptor instead.
func (*DeleteUpstreamResponse) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{6}
}

type ReindexUpstreamCatalogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicId      string                 `protobuf:"bytes,1,opt,name=public_id,json=publicId,proto3" json:"public_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReindexUpstreamCatalogRequest) Reset() {
	*x = ReindexUpstreamCatalogRequest{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReindexUpstreamCatalogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReindexUpstreamCatalogRequest) ProtoMessage() {}

func (x *ReindexUpstreamCatalogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReindexUpstreamCatalogRequest.ProtoReflect.Descriptor instead.
func (*ReindexUpstreamCatalogRequest) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{7}
}

func (x *ReindexUpstreamCatalogRequest) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

type ReindexUpstreamCatalogResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Upstream      *portalv1.UpstreamSummary `protobuf:"bytes,1,opt,name=upstream,proto3" json:"upstream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReindexUpstreamCatalogResponse) Reset() {
	*x = ReindexUpstreamCatalogResponse{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReindexUpstreamCatalogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReindexUpstreamCatalogResponse) ProtoMessage() {}

func (x *ReindexUpstreamCatalogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReindexUpstreamCatalogResponse.ProtoReflect.Descriptor instead.
func (*ReindexUpstreamCatalogResponse) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{8}
}

func (x *ReindexUpstreamCatalogResponse) GetUpstream() *portalv1.UpstreamSummary {
	if x != nil {
		return x.Upstream
	}
	return nil
}

type PreviewUpstreamContextRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	PublicId string                 `protobuf:"bytes,1,opt,name=public_id,json=publicId,proto3" json:"public_id,omitempty"`
	// Zitadel subject of the user whose per-link context the admin
	// wants to spot-check against the upstream's defaults_json.
	UserId        string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewUpstreamContextRequest) Reset() {
	*x = PreviewUpstreamContextRequest{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewUpstreamContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewUpstreamContextRequest) ProtoMessage() {}

func (x *PreviewUpstreamContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewUpstreamContextRequest.ProtoReflect.Descriptor instead.
func (*PreviewUpstreamContextRequest) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{9}
}

func (x *PreviewUpstreamContextRequest) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

func (x *PreviewUpstreamContextRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type PreviewUpstreamContextResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The merged JSON object as a string: merge(linkContext, defaultsJson).
	MergedJson    string `protobuf:"bytes,1,opt,name=merged_json,json=mergedJson,proto3" json:"merged_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewUpstreamContextResponse) Reset() {
	*x = PreviewUpstreamContextResponse{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewUpstreamContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewUpstreamContextResponse) ProtoMessage() {}

func (x *PreviewUpstreamContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewUpstreamContextResponse.ProtoReflect.Descriptor instead.
func (*PreviewUpstreamContextResponse) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{10}
}

func (x *PreviewUpstreamContextResponse) GetMergedJson() string {
	if x != nil {
		return x.MergedJson
	}
	return ""
}

type GetTenantSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantSettingsRequest) Reset() {
	*x = GetTenantSettingsRequest{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantSettingsRequest) ProtoMessage() {}

func (x *GetTenantSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantSettingsRequest.ProtoReflect.Descriptor instead.
func (*GetTenantSettingsRequest) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{11}
}

type GetTenantSettingsResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Settings *TenantSettings        `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	// Mirror of storage.Tenant.DCRRedirectURIAllowlist. Empty list = floor only.
	DcrRedirectUriAllowlist []string `protobuf:"bytes,2,rep,name=dcr_redirect_uri_allowlist,json=dcrRedirectUriAllowlist,proto3" json:"dcr_redirect_uri_allowlist,omitempty"`
	// Read-only Zitadel identity. The SPA renders these as a panel and
	// uses zitadel_org_id to build Console deep-links.
	ZitadelOrgId  string `protobuf:"bytes,3,opt,name=zitadel_org_id,json=zitadelOrgId,proto3" json:"zitadel_org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantSettingsResponse) Reset() {
	*x = GetTenantSettingsResponse{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantSettingsResponse) ProtoMessage() {}

func (x *GetTenantSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantSettingsResponse.ProtoReflect.Descriptor instead.
func (*GetTenantSettingsResponse) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{12}
}

func (x *GetTenantSettingsResponse) GetSettings() *TenantSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *GetTenantSettingsResponse) GetDcrRedirectUriAllowlist() []string {
	if x != nil {
		return x.DcrRedirectUriAllowlist
	}
	return nil
}

func (x *GetTenantSettingsResponse) GetZitadelOrgId() string {
	if x != nil {
		return x.ZitadelOrgId
	}
	return ""
}

type UpdateTenantSettingsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional. Empty string means "no change".
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// One-shot toggle: when true, flip tenant_settings.invited_team_at
	// to NOW() if it is currently NULL. No-op otherwise.
	InvitedTeamAtNow bool `protobuf:"varint,2,opt,name=invited_team_at_now,json=invitedTeamAtNow,proto3" json:"invited_team_at_now,omitempty"`
	// One-shot toggle: same semantics as invited_team_at_now but for
	// tenant_settings.configured_at.
	ConfiguredAtNow bool `protobuf:"varint,3,opt,name=configured_at_now,json=configuredAtNow,proto3" json:"configured_at_now,omitempty"`
	// DCR redirect-URI allowlist. Sentinel pattern: only honoured when
	// dcr_redirect_uri_allowlist_set is true; otherwise the existing
	// value is preserved (an empty repeated field is indistinguishable
	// from "leave it alone" without an explicit sentinel).
	DcrRedirectUriAllowlist    []string `protobuf:"bytes,4,rep,name=dcr_redirect_uri_allowlist,json=dcrRedirectUriAllowlist,proto3" json:"dcr_redirect_uri_allowlist,omitempty"`
	DcrRedirectUriAllowlistSet bool     `protobuf:"varint,5,opt,name=dcr_redirect_uri_allowlist_set,json=dcrRedirectUriAllowlistSet,proto3" json:"dcr_redirect_uri_allowlist_set,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *UpdateTenantSettingsRequest) Reset() {
	*x = UpdateTenantSettingsRequest{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTenantSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTenantSettingsRequest) ProtoMessage() {}

func (x *UpdateTenantSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTenantSettingsRequest.ProtoReflect.Descriptor instead.
func (*UpdateTenantSettingsRequest) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateTenantSettingsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTenantSettingsRequest) GetInvitedTeamAtNow() bool {
	if x != nil {
		return x.InvitedTeamAtNow
	}
	return false
}

func (x *UpdateTenantSettingsRequest) GetConfiguredAtNow() bool {
	if x != nil {
		return x.ConfiguredAtNow
	}
	return false
}

func (x *UpdateTenantSettingsRequest) GetDcrRedirectUriAllowlist() []string {
	if x != nil {
		return x.DcrRedirectUriAllowlist
	}
	return nil
}

func (x *UpdateTenantSettingsRequest) GetDcrRedirectUriAllowlistSet() bool {
	if x != nil {
		return x.DcrRedirectUriAllowlistSet
	}
	return false
}

type TenantSettings struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Name     string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PublicId string                 `protobuf:"bytes,2,opt,name=public_id,json=publicId,proto3" json:"public_id,omitempty"`
	// RFC3339; empty when unset.
	InvitedTeamAt string `protobuf:"bytes,3,opt,name=invited_team_at,json=invitedTeamAt,proto3" json:"invited_team_at,omitempty"`
	ConfiguredAt  string `protobuf:"bytes,4,opt,name=configured_at,json=configuredAt,proto3" json:"configured_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantSettings) Reset() {
	*x = TenantSettings{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantSettings) ProtoMessage() {}

func (x *TenantSettings) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantSettings.ProtoReflect.Descriptor instead.
func (*TenantSettings) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{14}
}

func (x *TenantSettings) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TenantSettings) GetPublicId() string {
	if x != nil {
		return x.PublicId
	}
	return ""
}

func (x *TenantSettings) GetInvitedTeamAt() string {
	if x != nil {
		return x.InvitedTeamAt
	}
	return ""
}

func (x *TenantSettings) GetConfiguredAt() string {
	if x != nil {
		return x.ConfiguredAt
	}
	return ""
}

type UpdateTenantSettingsResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Settings                *TenantSettings        `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	DcrRedirectUriAllowlist []string               `protobuf:"bytes,2,rep,name=dcr_redirect_uri_allowlist,json=dcrRedirectUriAllowlist,proto3" json:"dcr_redirect_uri_allowlist,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *UpdateTenantSettingsResponse) Reset() {
	*x = UpdateTenantSettingsResponse{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTenantSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTenantSettingsResponse) ProtoMessage() {}

func (x *UpdateTenantSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTenantSettingsResponse.ProtoReflect.Descriptor instead.
func (*UpdateTenantSettingsResponse) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateTenantSettingsResponse) GetSettings() *TenantSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *UpdateTenantSettingsResponse) GetDcrRedirectUriAllowlist() []string {
	if x != nil {
		return x.DcrRedirectUriAllowlist
	}
	return nil
}

type DeleteTenantRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Typed confirmation: caller must send the tenant's PublicID
	// verbatim. Mismatches reject with invalid_argument.
	PublicIdConfirmation string `protobuf:"bytes,1,opt,name=public_id_confirmation,json=publicIdConfirmation,proto3" json:"public_id_confirmation,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DeleteTenantRequest) Reset() {
	*x = DeleteTenantRequest{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTenantRequest) ProtoMessage() {}

func (x *DeleteTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTenantRequest.ProtoReflect.Descriptor instead.
func (*DeleteTenantRequest) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteTenantRequest) GetPublicIdConfirmation() string {
	if x != nil {
		return x.PublicIdConfirmation
	}
	return ""
}

type DeleteTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTenantResponse) Reset() {
	*x = DeleteTenantResponse{}
	mi := &file_limen_admin_v1_admin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTenantResponse) ProtoMessage() {}

func (x *DeleteTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_limen_admin_v1_admin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTenantResponse.ProtoReflect.Descriptor instead.
func (*DeleteTenantResponse) Descriptor() ([]byte, []int) {
	return file_limen_admin_v1_admin_proto_rawDescGZIP(), []int{17}
}

var File_limen_admin_v1_admin_proto protoreflect.FileDescriptor

const file_limen_admin_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x1alimen/admin/v1/admin.proto\x12\x0elimen.admin.v1\x1a\x1climen/portal/v1/portal.proto\"W\n" +
	"\x13OAuthClientOverride\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12#\n" +
	"\rclient_secret\x18\x02 \x01(\tR\fclientSecret\"\xe9\x03\n" +
	"\x15CreateUpstreamRequest\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x17\n" +
	"\amcp_url\x18\x03 \x01(\tR\x06mcpUrl\x12#\n" +
	"\rstrategy_type\x18\x04 \x01(\tR\fstrategyType\x12*\n" +
	"\x11strategy_sub_mode\x18\x05 \x01(\tR\x0fstrategySubMode\x12b\n" +
	"\x0fstrategy_config\x18\x06 \x03(\v29.limen.admin.v1.CreateUpstreamRequest.StrategyConfigEntryR\x0estrategyConfig\x12W\n" +
	"\x15oauth_client_override\x18\a \x01(\v2#.limen.admin.v1.OAuthClientOverrideR\x13oauthClientOverride\x12#\n" +
	"\rdefaults_json\x18\b \x01(\tR\fdefaultsJson\x1aA\n" +
	"\x13StrategyConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa7\x01\n" +
	"\x16CreateUpstreamResponse\x12<\n" +
	"\bupstream\x18\x01 \x01(\v2 .limen.portal.v1.UpstreamSummaryR\bupstream\x12.\n" +
	"\x13requires_admin_link\x18\x02 \x01(\bR\x11requiresAdminLink\x12\x1f\n" +
	"\vconnect_url\x18\x03 \x01(\tR\n" +
	"connectUrl\"|\n" +
	"\x15UpdateUpstreamRequest\x12\x1b\n" +
	"\tpublic_id\x18\x01 \x01(\tR\bpublicId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12#\n" +
	"\rdefaults_json\x18\x03 \x01(\tR\fdefaultsJson\"V\n" +
	"\x16UpdateUpstreamResponse\x12<\n" +
	"\bupstream\x18\x01 \x01(\v2 .limen.portal.v1.UpstreamSummaryR\bupstream\"4\n" +
	"\x15DeleteUpstreamRequest\x12\x1b\n" +
	"\tpublic_id\x18\x01 \x01(\tR\bpublicId\"\x18\n" +
	"\x16DeleteUpstreamResponse\"<\n" +
	"\x1dReindexUpstreamCatalogRequest\x12\x1b\n" +
	"\tpublic_id\x18\x01 \x01(\tR\bpublicId\"^\n" +
	"\x1eReindexUpstreamCatalogResponse\x12<\n" +
	"\bupstream\x18\x01 \x01(\v2 .limen.portal.v1.UpstreamSummaryR\bupstream\"U\n" +
	"\x1dPreviewUpstreamContextRequest\x12\x1b\n" +
	"\tpublic_id\x18\x01 \x01(\tR\bpublicId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"A\n" +
	"\x1ePreviewUpstreamContextResponse\x12\x1f\n" +
	"\vmerged_json\x18\x01 \x01(\tR\n" +
	"mergedJson\"\x1a\n" +
	"\x18GetTenantSettingsRequest\"\xba\x01\n" +
	"\x19GetTenantSettingsResponse\x12:\n" +
	"\bsettings\x18\x01 \x01(\v2\x1e.limen.admin.v1.TenantSettingsR\bsettings\x12;\n" +
	"\x1adcr_redirect_uri_allowlist\x18\x02 \x03(\tR\x17dcrRedirectUriAllowlist\x12$\n" +
	"\x0ezitadel_org_id\x18\x03 \x01(\tR\fzitadelOrgId\"\x8d\x02\n" +
	"\x1bUpdateTenantSettingsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12-\n" +
	"\x13invited_team_at_now\x18\x02 \x01(\bR\x10invitedTeamAtNow\x12*\n" +
	"\x11configured_at_now\x18\x03 \x01(\bR\x0fconfiguredAtNow\x12;\n" +
	"\x1adcr_redirect_uri_allowlist\x18\x04 \x03(\tR\x17dcrRedirectUriAllowlist\x12B\n" +
	"\x1edcr_redirect_uri_allowlist_set\x18\x05 \x01(\bR\x1adcrRedirectUriAllowlistSet\"\x8e\x01\n" +
	"\x0eTenantSettings\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tpublic_id\x18\x02 \x01(\tR\bpublicId\x12&\n" +
	"\x0finvited_team_at\x18\x03 \x01(\tR\rinvitedTeamAt\x12#\n" +
	"\rconfigured_at\x18\x04 \x01(\tR\fconfiguredAt\"\x97\x01\n" +
	"\x1cUpdateTenantSettingsResponse\x12:\n" +
	"\bsettings\x18\x01 \x01(\v2\x1e.limen.admin.v1.TenantSettingsR\bsettings\x12;\n" +
	"\x1adcr_redirect_uri_allowlist\x18\x02 \x03(\tR\x17dcrRedirectUriAllowlist\"K\n" +
	"\x13DeleteTenantRequest\x124\n" +
	"\x16public_id_confirmation\x18\x01 \x01(\tR\x14publicIdConfirmation\"\x16\n" +
	"\x14DeleteTenantResponse2\xdb\x06\n" +
	"\fAdminService\x12_\n" +
	"\x0eCreateUpstream\x12%.limen.admin.v1.CreateUpstreamRequest\x1a&.limen.admin.v1.CreateUpstreamResponse\x12_\n" +
	"\x0eUpdateUpstream\x12%.limen.admin.v1.UpdateUpstreamRequest\x1a&.limen.admin.v1.UpdateUpstreamResponse\x12_\n" +
	"\x0eDeleteUpstream\x12%.limen.admin.v1.DeleteUpstreamRequest\x1a&.limen.admin.v1.DeleteUpstreamResponse\x12w\n" +
	"\x16ReindexUpstreamCatalog\x12-.limen.admin.v1.ReindexUpstreamCatalogRequest\x1a..limen.admin.v1.ReindexUpstreamCatalogResponse\x12w\n" +
	"\x16PreviewUpstreamContext\x12-.limen.admin.v1.PreviewUpstreamContextRequest\x1a..limen.admin.v1.PreviewUpstreamContextResponse\x12h\n" +
	"\x11GetTenantSettings\x12(.limen.admin.v1.GetTenantSettingsRequest\x1a).limen.admin.v1.GetTenantSettingsResponse\x12q\n" +
	"\x14UpdateTenantSettings\x12+.limen.admin.v1.UpdateTenantSettingsRequest\x1a,.limen.admin.v1.UpdateTenantSettingsResponse\x12Y\n" +
	"\fDeleteTenant\x12#.limen.admin.v1.DeleteTenantRequest\x1a$.limen.admin.v1.DeleteTenantResponseB;Z9github.com/belphemur/limen/internal/admin/adminv1;adminv1b\x06proto3"

var (
	file_limen_admin_v1_admin_proto_rawDescOnce sync.Once
	file_limen_admin_v1_admin_proto_rawDescData []byte
)

func file_limen_admin_v1_admin_proto_rawDescGZIP() []byte {
	file_limen_admin_v1_admin_proto_rawDescOnce.Do(func() {
		file_limen_admin_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_limen_admin_v1_admin_proto_rawDesc), len(file_limen_admin_v1_admin_proto_rawDesc)))
	})
	return file_limen_admin_v1_admin_proto_rawDescData
}

var file_limen_admin_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_limen_admin_v1_admin_proto_goTypes = []any{
	(*OAuthClientOverride)(nil),            // 0: limen.admin.v1.OAuthClientOverride
	(*CreateUpstreamRequest)(nil),          // 1: limen.admin.v1.CreateUpstreamRequest
	(*CreateUpstreamResponse)(nil),         // 2: limen.admin.v1.CreateUpstreamResponse
	(*UpdateUpstreamRequest)(nil),          // 3: limen.admin.v1.UpdateUpstreamRequest
	(*UpdateUpstreamResponse)(nil),         // 4: limen.admin.v1.UpdateUpstreamResponse
	(*DeleteUpstreamRequest)(nil),          // 5: limen.admin.v1.DeleteUpstreamRequest
	(*DeleteUpstreamResponse)(nil),         // 6: limen.admin.v1.DeleteUpstreamResponse
	(*ReindexUpstreamCatalogRequest)(nil),  // 7: limen.admin.v1.ReindexUpstreamCatalogRequest
	(*ReindexUpstreamCatalogResponse)(nil), // 8: limen.admin.v1.ReindexUpstreamCatalogResponse
	(*PreviewUpstreamContextRequest)(nil),  // 9: limen.admin.v1.PreviewUpstreamContextRequest
	(*PreviewUpstreamContextResponse)(nil), // 10: limen.admin.v1.PreviewUpstreamContextResponse
	(*GetTenantSettingsRequest)(nil),       // 11: limen.admin.v1.GetTenantSettingsRequest
	(*GetTenantSettingsResponse)(nil),      // 12: limen.admin.v1.GetTenantSettingsResponse
	(*UpdateTenantSettingsRequest)(nil),    // 13: limen.admin.v1.UpdateTenantSettingsRequest
	(*TenantSettings)(nil),                 // 14: limen.admin.v1.TenantSettings
	(*UpdateTenantSettingsResponse)(nil),   // 15: limen.admin.v1.UpdateTenantSettingsResponse
	(*DeleteTenantRequest)(nil),            // 16: limen.admin.v1.DeleteTenantRequest
	(*DeleteTenantResponse)(nil),           // 17: limen.admin.v1.DeleteTenantResponse
	nil,                                    // 18: limen.admin.v1.CreateUpstreamRequest.StrategyConfigEntry
	(*portalv1.UpstreamSummary)(nil),       // 19: limen.portal.v1.UpstreamSummary
}
var file_limen_admin_v1_admin_proto_depIdxs = []int32{
	18, // 0: limen.admin.v1.CreateUpstreamRequest.strategy_config:type_name -> limen.admin.v1.CreateUpstreamRequest.StrategyConfigEntry
	0,  // 1: limen.admin.v1.CreateUpstreamRequest.oauth_client_override:type_name -> limen.admin.v1.OAuthClientOverride
	19, // 2: limen.admin.v1.CreateUpstreamResponse.upstream:type_name -> limen.portal.v1.UpstreamSummary
	19, // 3: limen.admin.v1.UpdateUpstreamResponse.upstream:type_name -> limen.portal.v1.UpstreamSummary
	19, // 4: limen.admin.v1.ReindexUpstreamCatalogResponse.upstream:type_name -> limen.portal.v1.UpstreamSummary
	14, // 5: limen.admin.v1.GetTenantSettingsResponse.settings:type_name -> limen.admin.v1.TenantSettings
	14, // 6: limen.admin.v1.UpdateTenantSettingsResponse.settings:type_name -> limen.admin.v1.TenantSettings
	1,  // 7: limen.admin.v1.AdminService.CreateUpstream:input_type -> limen.admin.v1.CreateUpstreamRequest
	3,  // 8: limen.admin.v1.AdminService.UpdateUpstream:input_type -> limen.admin.v1.UpdateUpstreamRequest
	5,  // 9: limen.admin.v1.AdminService.DeleteUpstream:input_type -> limen.admin.v1.DeleteUpstreamRequest
	7,  // 10: limen.admin.v1.AdminService.ReindexUpstreamCatalog:input_type -> limen.admin.v1.ReindexUpstreamCatalogRequest
	9,  // 11: limen.admin.v1.AdminService.PreviewUpstreamContext:input_type -> limen.admin.v1.PreviewUpstreamContextRequest
	11, // 12: limen.admin.v1.AdminService.GetTenantSettings:input_type -> limen.admin.v1.GetTenantSettingsRequest
	13, // 13: limen.admin.v1.AdminService.UpdateTenantSettings:input_type -> limen.admin.v1.UpdateTenantSettingsRequest
	16, // 14: limen.admin.v1.AdminService.DeleteTenant:input_type -> limen.admin.v1.DeleteTenantRequest
	2,  // 15: limen.admin.v1.AdminService.CreateUpstream:output_type -> limen.admin.v1.CreateUpstreamResponse
	4,  // 16: limen.admin.v1.AdminService.UpdateUpstream:output_type -> limen.admin.v1.UpdateUpstreamResponse
	6,  // 17: limen.admin.v1.AdminService.DeleteUpstream:output_type -> limen.admin.v1.DeleteUpstreamResponse
	8,  // 18: limen.admin.v1.AdminService.ReindexUpstreamCatalog:output_type -> limen.admin.v1.ReindexUpstreamCatalogResponse
	10, // 19: limen.admin.v1.AdminService.PreviewUpstreamContext:output_type -> limen.admin.v1.PreviewUpstreamContextResponse
	12, // 20: limen.admin.v1.AdminService.GetTenantSettings:output_type -> limen.admin.v1.GetTenantSettingsResponse
	15, // 21: limen.admin.v1.AdminService.UpdateTenantSettings:output_type -> limen.admin.v1.UpdateTenantSettingsResponse
	17, // 22: limen.admin.v1.AdminService.DeleteTenant:output_type -> limen.admin.v1.DeleteTenantResponse
	15, // [15:23] is the sub-list for method output_type
	7,  // [7:15] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_limen_admin_v1_admin_proto_init() }
func file_limen_admin_v1_admin_proto_init() {
	if File_limen_admin_v1_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_limen_admin_v1_admin_proto_rawDesc), len(file_limen_admin_v1_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_limen_admin_v1_admin_proto_goTypes,
		DependencyIndexes: file_limen_admin_v1_admin_proto_depIdxs,
		MessageInfos:      file_limen_admin_v1_admin_proto_msgTypes,
	}.Build()
	File_limen_admin_v1_admin_proto = out.File
	file_limen_admin_v1_admin_proto_goTypes = nil
	file_limen_admin_v1_admin_proto_depIdxs = nil
}
